/*
 * Decompiled with CFR 0.152.
 */
package dji.sdk.keyvalue.key;

import dji.sdk.keyvalue.converter.DJIValueConverter;
import dji.sdk.keyvalue.converter.EmptyValueConverter;
import dji.sdk.keyvalue.converter.SingleValueConverter;
import dji.sdk.keyvalue.key.ComponentType;
import dji.sdk.keyvalue.key.DJIActionKeyInfo;
import dji.sdk.keyvalue.key.DJIKeyInfo;
import dji.sdk.keyvalue.key.SubComponentType;
import dji.sdk.keyvalue.value.aibox.AIBoxAppInfoMsg;
import dji.sdk.keyvalue.value.aibox.AIBoxAppListMsg;
import dji.sdk.keyvalue.value.aibox.AIBoxAppSpaceInfoMsg;
import dji.sdk.keyvalue.value.aibox.AIBoxAppStateListMsg;
import dji.sdk.keyvalue.value.aibox.AIBoxDeviceOperatingInfoMsg;
import dji.sdk.keyvalue.value.aibox.AIBoxExternalStorageStateMsg;
import dji.sdk.keyvalue.value.aibox.AIBoxType;
import dji.sdk.keyvalue.value.aibox.AIBoxTypeMsg;
import dji.sdk.keyvalue.value.aibox.AIboxFileExportStatusMsg;
import dji.sdk.keyvalue.value.aibox.AppLanguageInfo;
import dji.sdk.keyvalue.value.aibox.ExcuteAIboxAppActionTypeMsg;
import dji.sdk.keyvalue.value.aibox.ExcuteAIboxFileExportMsg;
import dji.sdk.keyvalue.value.common.CalibrationFileStatus;
import dji.sdk.keyvalue.value.common.CalibrationFileStatusMsg;
import dji.sdk.keyvalue.value.common.CalibrationFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.CmdReturnCodeMsg;
import dji.sdk.keyvalue.value.common.CommonFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.EmptyMsg;
import dji.sdk.keyvalue.value.common.FileDownloadInputMsg;
import dji.sdk.keyvalue.value.common.FileDownloadSizeInfoMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapability;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapabilityMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCode;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCodeMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticPartsInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticProgress;
import dji.sdk.keyvalue.value.common.SelfDiagnosticRequestInfo;
import dji.sdk.keyvalue.value.common.UpgradeNotifyInfo;
import java.util.ArrayList;
import java.util.List;

public class DJIAiboxKey {
    protected static final List<DJIKeyInfo<?>> keyList = new ArrayList();
    private static final ComponentType componentType = ComponentType.AIBOX;
    private static final SubComponentType subComponentType = SubComponentType.IGNORE;
    public static final DJIKeyInfo<String> KeySerialNumber = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SerialNumber", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyFirmwareVersion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FirmwareVersion", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<AIBoxType> KeyAIBoxType = new DJIKeyInfo<AIBoxType>(componentType.value(), subComponentType.value(), "AIBoxType", new SingleValueConverter<AIBoxType, AIBoxTypeMsg>(AIBoxType.class, AIBoxTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<ExcuteAIboxFileExportMsg, CmdReturnCodeMsg> KeyExcuteAIboxFileExport = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ExcuteAIboxFileExport", new DJIValueConverter<ExcuteAIboxFileExportMsg>(ExcuteAIboxFileExportMsg.class), new DJIValueConverter<CmdReturnCodeMsg>(CmdReturnCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<AIboxFileExportStatusMsg> KeyAIboxFileExportStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AIboxFileExportStatus", new DJIValueConverter<AIboxFileExportStatusMsg>(AIboxFileExportStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<AIBoxExternalStorageStateMsg> KeyAIBoxExternalStorageState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AIBoxExternalStorageState", new DJIValueConverter<AIBoxExternalStorageStateMsg>(AIBoxExternalStorageStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<AIBoxDeviceOperatingInfoMsg> KeyAIBoxDeviceOperatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AIBoxDeviceOperatingInfo", new DJIValueConverter<AIBoxDeviceOperatingInfoMsg>(AIBoxDeviceOperatingInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<AIBoxAppListMsg> KeyAIBoxAppList = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AIBoxAppList", new DJIValueConverter<AIBoxAppListMsg>(AIBoxAppListMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, AIBoxAppInfoMsg> KeyQueryAIboxAppInfo = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "QueryAIboxAppInfo", SingleValueConverter.StringConverter, new DJIValueConverter<AIBoxAppInfoMsg>(AIBoxAppInfoMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<AIBoxAppSpaceInfoMsg> KeyAIboxAppSpaceInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AIboxAppSpaceInfo", new DJIValueConverter<AIBoxAppSpaceInfoMsg>(AIBoxAppSpaceInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<ExcuteAIboxAppActionTypeMsg, Integer> KeyExcuteAIboxAppAction = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ExcuteAIboxAppAction", new DJIValueConverter<ExcuteAIboxAppActionTypeMsg>(ExcuteAIboxAppActionTypeMsg.class), SingleValueConverter.IntegerConverter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<AIBoxAppStateListMsg> KeyAIBoxAppStateList = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AIBoxAppStateList", new DJIValueConverter<AIBoxAppStateListMsg>(AIBoxAppStateListMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyNetworkConnection = new DJIKeyInfo(componentType.value(), subComponentType.value(), "NetworkConnection", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<FileDownloadInputMsg, EmptyMsg> KeyStartDownloadMeshFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StartDownloadMeshFile", new DJIValueConverter<FileDownloadInputMsg>(FileDownloadInputMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopDownloadMeshFile = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopDownloadMeshFile", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<FileDownloadSizeInfoMsg> KeyMeshFileDownloadInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MeshFileDownloadInfo", new DJIValueConverter<FileDownloadSizeInfoMsg>(FileDownloadSizeInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<AppLanguageInfo> KeyAppLanguageInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AppLanguageInfo", new DJIValueConverter<AppLanguageInfo>(AppLanguageInfo.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsChannelOperationNeeded = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsChannelOperationNeeded", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyBackupChannelInfo = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "BackupChannelInfo", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyResumeChannelInfo = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "ResumeChannelInfo", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsPlayingBack = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsPlayingBack", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyEnterPlayback = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "EnterPlayback", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyExitPlayback = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "ExitPlayback", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsPlaybackPageFetchSupport = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsPlaybackPageFetchSupport", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsPlaybackFolderFetchSupport = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsPlaybackFolderFetchSupport", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyDeviceID = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DeviceID", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyConnection = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Connection", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyForceUpdateCacheValue = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ForceUpdateCacheValue", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileStatus> KeyCalibrationFileStatus = new DJIKeyInfo<CalibrationFileStatus>(componentType.value(), subComponentType.value(), "CalibrationFileStatus", new SingleValueConverter<CalibrationFileStatus, CalibrationFileStatusMsg>(CalibrationFileStatus.class, CalibrationFileStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileUpdatingInfo> KeyCalibrationFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CalibrationFileUpdatingInfo", new DJIValueConverter<CalibrationFileUpdatingInfo>(CalibrationFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyUpdateCalibrationFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "UpdateCalibrationFile", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<UpgradeNotifyInfo> KeyUpgradeNotifyInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UpgradeNotifyInfo", new DJIValueConverter<UpgradeNotifyInfo>(UpgradeNotifyInfo.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyEnforceUpgradeEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "EnforceUpgradeEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsInEnforceUpgradeStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsInEnforceUpgradeStatus", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsDirectDevice = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsDirectDevice", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CommonFileUpdatingInfo> KeyCommonFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CommonFileUpdatingInfo", new DJIValueConverter<CommonFileUpdatingInfo>(CommonFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyStartCommonFileUpdate = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StartCommonFileUpdate", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopCommonFileUpdate = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopCommonFileUpdate", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticMode = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticMode", new DJIValueConverter<SelfDiagnosticInfo>(SelfDiagnosticInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticRequestInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticRequest = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticRequest", new DJIValueConverter<SelfDiagnosticRequestInfo>(SelfDiagnosticRequestInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode> KeySelfDiagnosticCancel = new DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode>(componentType.value(), subComponentType.value(), "SelfDiagnosticCancel", EmptyValueConverter.converter, new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<SelfDiagnosticProgress> KeySelfDiagnosticStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticStatus", new DJIValueConverter<SelfDiagnosticProgress>(SelfDiagnosticProgress.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticCapability, SelfDiagnosticPartsInfo> KeySelfDiagnosticParts = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticParts", new SingleValueConverter<SelfDiagnosticCapability, SelfDiagnosticCapabilityMsg>(SelfDiagnosticCapability.class, SelfDiagnosticCapabilityMsg.class), new DJIValueConverter<SelfDiagnosticPartsInfo>(SelfDiagnosticPartsInfo.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);

    static {
        keyList.add(KeySerialNumber);
        keyList.add(KeyFirmwareVersion);
        keyList.add(KeyAIBoxType);
        keyList.add(KeyExcuteAIboxFileExport);
        keyList.add(KeyAIboxFileExportStatus);
        keyList.add(KeyAIBoxExternalStorageState);
        keyList.add(KeyAIBoxDeviceOperatingInfo);
        keyList.add(KeyAIBoxAppList);
        keyList.add(KeyQueryAIboxAppInfo);
        keyList.add(KeyAIboxAppSpaceInfo);
        keyList.add(KeyExcuteAIboxAppAction);
        keyList.add(KeyAIBoxAppStateList);
        keyList.add(KeyNetworkConnection);
        keyList.add(KeyStartDownloadMeshFile);
        keyList.add(KeyStopDownloadMeshFile);
        keyList.add(KeyMeshFileDownloadInfo);
        keyList.add(KeyAppLanguageInfo);
        keyList.add(KeyIsChannelOperationNeeded);
        keyList.add(KeyBackupChannelInfo);
        keyList.add(KeyResumeChannelInfo);
        keyList.add(KeyIsPlayingBack);
        keyList.add(KeyEnterPlayback);
        keyList.add(KeyExitPlayback);
        keyList.add(KeyIsPlaybackPageFetchSupport);
        keyList.add(KeyIsPlaybackFolderFetchSupport);
        keyList.add(KeyDeviceID);
        keyList.add(KeyConnection);
        keyList.add(KeyForceUpdateCacheValue);
        keyList.add(KeyCalibrationFileStatus);
        keyList.add(KeyCalibrationFileUpdatingInfo);
        keyList.add(KeyUpdateCalibrationFile);
        keyList.add(KeyUpgradeNotifyInfo);
        keyList.add(KeyEnforceUpgradeEnable);
        keyList.add(KeyIsInEnforceUpgradeStatus);
        keyList.add(KeyIsDirectDevice);
        keyList.add(KeyCommonFileUpdatingInfo);
        keyList.add(KeyStartCommonFileUpdate);
        keyList.add(KeyStopCommonFileUpdate);
        keyList.add(KeySelfDiagnosticMode);
        keyList.add(KeySelfDiagnosticRequest);
        keyList.add(KeySelfDiagnosticCancel);
        keyList.add(KeySelfDiagnosticStatus);
        keyList.add(KeySelfDiagnosticParts);
    }
}

