/*
 * Decompiled with CFR 0.152.
 */
package dji.sdk.keyvalue.key;

import dji.sdk.keyvalue.converter.BufferConverter;
import dji.sdk.keyvalue.converter.DJIValueConverter;
import dji.sdk.keyvalue.converter.EmptyValueConverter;
import dji.sdk.keyvalue.converter.SingleValueConverter;
import dji.sdk.keyvalue.key.ComponentType;
import dji.sdk.keyvalue.key.DJIActionKeyInfo;
import dji.sdk.keyvalue.key.DJIKeyInfo;
import dji.sdk.keyvalue.key.SubComponentType;
import dji.sdk.keyvalue.value.airlink.AirLinkFirmwareSupportInfo;
import dji.sdk.keyvalue.value.airlink.AirLinkType;
import dji.sdk.keyvalue.value.airlink.AirLinkTypeMsg;
import dji.sdk.keyvalue.value.airlink.AirlinkBandwidthMsg;
import dji.sdk.keyvalue.value.airlink.AirlinkBandwidthRangeMsg;
import dji.sdk.keyvalue.value.airlink.AirlinkFrequencyBandMsg;
import dji.sdk.keyvalue.value.airlink.AirlinkFrequencyBandRangeMsg;
import dji.sdk.keyvalue.value.airlink.AreaCodeSupport;
import dji.sdk.keyvalue.value.airlink.AreaCodeSupportMsg;
import dji.sdk.keyvalue.value.airlink.AvailableVideoSourceInfo;
import dji.sdk.keyvalue.value.airlink.Bandwidth;
import dji.sdk.keyvalue.value.airlink.CameraVideoStreamType;
import dji.sdk.keyvalue.value.airlink.CameraVideoStreamTypeMsg;
import dji.sdk.keyvalue.value.airlink.ChannelCodecFormatSetting;
import dji.sdk.keyvalue.value.airlink.ChannelPriorityMsg;
import dji.sdk.keyvalue.value.airlink.ChannelPriorityParam;
import dji.sdk.keyvalue.value.airlink.ChannelSelectionMode;
import dji.sdk.keyvalue.value.airlink.ChannelSelectionModeMsg;
import dji.sdk.keyvalue.value.airlink.ClearLTEPrivatizationServerInfo;
import dji.sdk.keyvalue.value.airlink.DongleReleaseNoteMsg;
import dji.sdk.keyvalue.value.airlink.DongleReleaseReqMsg;
import dji.sdk.keyvalue.value.airlink.FreqStrengthInfo;
import dji.sdk.keyvalue.value.airlink.FrequencyBand;
import dji.sdk.keyvalue.value.airlink.FrequencyInterferenceInfo;
import dji.sdk.keyvalue.value.airlink.FrequencyPointRSSIInfo;
import dji.sdk.keyvalue.value.airlink.LTENetDongleInfos;
import dji.sdk.keyvalue.value.airlink.LTENetcardInfos;
import dji.sdk.keyvalue.value.airlink.LTEPrivatizationServerMsg;
import dji.sdk.keyvalue.value.airlink.LightbridgeAntennaRSSI;
import dji.sdk.keyvalue.value.airlink.LinkMode;
import dji.sdk.keyvalue.value.airlink.LinkModeMsg;
import dji.sdk.keyvalue.value.airlink.LiveVideoSourceEntity;
import dji.sdk.keyvalue.value.airlink.LiveVideoSourceInfo;
import dji.sdk.keyvalue.value.airlink.LiveViewResolution;
import dji.sdk.keyvalue.value.airlink.LiveViewResolutionhMsg;
import dji.sdk.keyvalue.value.airlink.LteTestRequestMsg;
import dji.sdk.keyvalue.value.airlink.LteTriSIMModeMsg;
import dji.sdk.keyvalue.value.airlink.ManageChannelWhilePlaybackModeChangeParam;
import dji.sdk.keyvalue.value.airlink.ManageSourceParam;
import dji.sdk.keyvalue.value.airlink.ManageSourceParams;
import dji.sdk.keyvalue.value.airlink.MasterLiveVideoCameraMsg;
import dji.sdk.keyvalue.value.airlink.Mavic3AirLinkFirmwareSupportInfo;
import dji.sdk.keyvalue.value.airlink.MultiDevicesFpvSwitchMsg;
import dji.sdk.keyvalue.value.airlink.PairingState;
import dji.sdk.keyvalue.value.airlink.PairingStateMsg;
import dji.sdk.keyvalue.value.airlink.RcImuReportMsg;
import dji.sdk.keyvalue.value.airlink.RelayFuncStatusMsg;
import dji.sdk.keyvalue.value.airlink.RelayRequestPeerMsg;
import dji.sdk.keyvalue.value.airlink.SDRDistanceLossReason;
import dji.sdk.keyvalue.value.airlink.SDRDistanceLossReasonMsg;
import dji.sdk.keyvalue.value.airlink.SDRHdOffsetParams;
import dji.sdk.keyvalue.value.airlink.SNRInfo;
import dji.sdk.keyvalue.value.airlink.SNRInfoMsg;
import dji.sdk.keyvalue.value.airlink.Sub2GAuthStateMsg;
import dji.sdk.keyvalue.value.airlink.UploadMcsType;
import dji.sdk.keyvalue.value.airlink.UploadMcsTypeMsg;
import dji.sdk.keyvalue.value.airlink.VideoFeedPhysicalSource;
import dji.sdk.keyvalue.value.airlink.VideoSourceEntity;
import dji.sdk.keyvalue.value.airlink.WiFiMagneticInterferenceLevel;
import dji.sdk.keyvalue.value.airlink.WiFiMagneticInterferenceLevelMsg;
import dji.sdk.keyvalue.value.airlink.WlmAgentFreqInfo;
import dji.sdk.keyvalue.value.airlink.WlmConnectingDevicesInfo;
import dji.sdk.keyvalue.value.airlink.WlmDeviceMsg;
import dji.sdk.keyvalue.value.airlink.WlmDeviceType;
import dji.sdk.keyvalue.value.airlink.WlmDongleApnInfo;
import dji.sdk.keyvalue.value.airlink.WlmDongleListInfo;
import dji.sdk.keyvalue.value.airlink.WlmDongleSubscribeInfoMsg;
import dji.sdk.keyvalue.value.airlink.WlmDongleSubscribeInfoReqMsg;
import dji.sdk.keyvalue.value.airlink.WlmDownloadServiceMode;
import dji.sdk.keyvalue.value.airlink.WlmDownloadServiceModeMsg;
import dji.sdk.keyvalue.value.airlink.WlmESIMActivateInfo;
import dji.sdk.keyvalue.value.airlink.WlmESIMInfoMsg;
import dji.sdk.keyvalue.value.airlink.WlmLinkDiagnosisMsg;
import dji.sdk.keyvalue.value.airlink.WlmLinkMode;
import dji.sdk.keyvalue.value.airlink.WlmLinkModeMsg;
import dji.sdk.keyvalue.value.airlink.WlmLinkQualityLevelInfo;
import dji.sdk.keyvalue.value.airlink.WlmLinkStatus;
import dji.sdk.keyvalue.value.airlink.WlmLinkTestResultInfo;
import dji.sdk.keyvalue.value.airlink.WlmLiveServiceMode;
import dji.sdk.keyvalue.value.airlink.WlmLiveServiceModeMsg;
import dji.sdk.keyvalue.value.airlink.WlmNewDongleInfoMsg;
import dji.sdk.keyvalue.value.airlink.WlmReadDongleApnInfo;
import dji.sdk.keyvalue.value.airlink.WlmRttInfoList;
import dji.sdk.keyvalue.value.airlink.WlmSIMCardInfoMsg;
import dji.sdk.keyvalue.value.airlink.WlmStartLinkTestInfo;
import dji.sdk.keyvalue.value.airlink.WlmTriSIMCardISPMsg;
import dji.sdk.keyvalue.value.airlink.WlmWriteDongleApnInfo;
import dji.sdk.keyvalue.value.camera.CameraCType;
import dji.sdk.keyvalue.value.camera.CameraTypeMsg;
import dji.sdk.keyvalue.value.camera.PhysicalSourceAllocationMsg;
import dji.sdk.keyvalue.value.camera.VideoFeedPhysicalSourceMsg;
import dji.sdk.keyvalue.value.common.AreaCodeInfo;
import dji.sdk.keyvalue.value.common.CalibrationFileStatus;
import dji.sdk.keyvalue.value.common.CalibrationFileStatusMsg;
import dji.sdk.keyvalue.value.common.CalibrationFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.CommonFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.EmptyMsg;
import dji.sdk.keyvalue.value.common.HdvtMode;
import dji.sdk.keyvalue.value.common.HdvtModeMsg;
import dji.sdk.keyvalue.value.common.IntListMsg;
import dji.sdk.keyvalue.value.common.IntMinMax;
import dji.sdk.keyvalue.value.common.SDRQualityDetectReqMsg;
import dji.sdk.keyvalue.value.common.SDRQualityDetectRspMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapability;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapabilityMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCode;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCodeMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticPartsInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticProgress;
import dji.sdk.keyvalue.value.common.SelfDiagnosticRequestInfo;
import dji.sdk.keyvalue.value.common.UpgradeNotifyInfo;
import java.util.ArrayList;
import java.util.List;

public class DJIAirlinkKey {
    protected static final List<DJIKeyInfo<?>> keyList = new ArrayList();
    private static final ComponentType componentType = ComponentType.AIRLINK;
    private static final SubComponentType subComponentType = SubComponentType.IGNORE;
    public static final DJIKeyInfo<Integer> KeyLightbridgeDataRate = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LightbridgeDataRate", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyUpLinkQuality = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UpLinkQuality", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyDownLinkQuality = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DownLinkQuality", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyTTD4Existed = new DJIKeyInfo(componentType.value(), subComponentType.value(), "TTD4Existed", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyUpLinkQualityRaw = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UpLinkQualityRaw", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyDownLinkQualityRaw = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DownLinkQualityRaw", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyBaseBand = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BaseBand", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<LightbridgeAntennaRSSI> KeyRcAntennaRssi = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcAntennaRssi", new DJIValueConverter<LightbridgeAntennaRSSI>(LightbridgeAntennaRSSI.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<LightbridgeAntennaRSSI> KeyAircraftAntennaRssi = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AircraftAntennaRssi", new DJIValueConverter<LightbridgeAntennaRSSI>(LightbridgeAntennaRSSI.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CameraCType> KeyLeftCameraType = new DJIKeyInfo<CameraCType>(componentType.value(), subComponentType.value(), "LeftCameraType", new SingleValueConverter<CameraCType, CameraTypeMsg>(CameraCType.class, CameraTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CameraCType> KeyRightCameraType = new DJIKeyInfo<CameraCType>(componentType.value(), subComponentType.value(), "RightCameraType", new SingleValueConverter<CameraCType, CameraTypeMsg>(CameraCType.class, CameraTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CameraCType> KeyFPVCameraType = new DJIKeyInfo<CameraCType>(componentType.value(), subComponentType.value(), "FPVCameraType", new SingleValueConverter<CameraCType, CameraTypeMsg>(CameraCType.class, CameraTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CameraCType> KeyPrimaryVideoFeedCameraType = new DJIKeyInfo<CameraCType>(componentType.value(), subComponentType.value(), "PrimaryVideoFeedCameraType", new SingleValueConverter<CameraCType, CameraTypeMsg>(CameraCType.class, CameraTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CameraCType> KeySecondaryVideoFeedCameraType = new DJIKeyInfo<CameraCType>(componentType.value(), subComponentType.value(), "SecondaryVideoFeedCameraType", new SingleValueConverter<CameraCType, CameraTypeMsg>(CameraCType.class, CameraTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<VideoFeedPhysicalSource> KeySecondaryVideoFeedPhysicalSource = new DJIKeyInfo<VideoFeedPhysicalSource>(componentType.value(), subComponentType.value(), "SecondaryVideoFeedPhysicalSource", new SingleValueConverter<VideoFeedPhysicalSource, VideoFeedPhysicalSourceMsg>(VideoFeedPhysicalSource.class, VideoFeedPhysicalSourceMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<VideoFeedPhysicalSource> KeyPrimaryVideoFeedPhysicalSource = new DJIKeyInfo<VideoFeedPhysicalSource>(componentType.value(), subComponentType.value(), "PrimaryVideoFeedPhysicalSource", new SingleValueConverter<VideoFeedPhysicalSource, VideoFeedPhysicalSourceMsg>(VideoFeedPhysicalSource.class, VideoFeedPhysicalSourceMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyPrimaryVideoFeedBandwidth = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PrimaryVideoFeedBandwidth", SingleValueConverter.DoubleConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<PhysicalSourceAllocationMsg, EmptyMsg> KeyAllocatePhysicalSource = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "AllocatePhysicalSource", new DJIValueConverter<PhysicalSourceAllocationMsg>(PhysicalSourceAllocationMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<CameraCType> KeyMasterScreen = new DJIKeyInfo<CameraCType>(componentType.value(), subComponentType.value(), "MasterScreen", new SingleValueConverter<CameraCType, CameraTypeMsg>(CameraCType.class, CameraTypeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<WiFiMagneticInterferenceLevel> KeyWiFiMagneticInterferenceLevel = new DJIKeyInfo<WiFiMagneticInterferenceLevel>(componentType.value(), subComponentType.value(), "WiFiMagneticInterferenceLevel", new SingleValueConverter<WiFiMagneticInterferenceLevel, WiFiMagneticInterferenceLevelMsg>(WiFiMagneticInterferenceLevel.class, WiFiMagneticInterferenceLevelMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, AreaCodeSupport> KeyQueryAreaCodeSupportInfo = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "QueryAreaCodeSupportInfo", SingleValueConverter.StringConverter, new SingleValueConverter<AreaCodeSupport, AreaCodeSupportMsg>(AreaCodeSupport.class, AreaCodeSupportMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<AreaCodeInfo> KeyAreaCodeFromGround = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AreaCodeFromGround", new DJIValueConverter<AreaCodeInfo>(AreaCodeInfo.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<AirLinkType> KeyAirLinkType = new DJIKeyInfo<AirLinkType>(componentType.value(), subComponentType.value(), "AirLinkType", new SingleValueConverter<AirLinkType, AirLinkTypeMsg>(AirLinkType.class, AirLinkTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<FrequencyBand> KeyFrequencyBand = new DJIKeyInfo<FrequencyBand>(componentType.value(), subComponentType.value(), "FrequencyBand", new SingleValueConverter<FrequencyBand, AirlinkFrequencyBandMsg>(FrequencyBand.class, AirlinkFrequencyBandMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("AirlinkFrequencyBand");
    public static final DJIKeyInfo<List<FrequencyBand>> KeyFrequencyBandRange = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "FrequencyBandRange", new SingleValueConverter<List, AirlinkFrequencyBandRangeMsg>(List.class, AirlinkFrequencyBandRangeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("AirlinkFrequencyBandRange");
    public static final DJIKeyInfo<Boolean> KeyIsDualBandSupported = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsDualBandSupported", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsSub2GSupported = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsSub2GSupported", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIs5Dot7GSupported = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Is5Dot7GSupported", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIs1Dot4GSupported = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Is1Dot4GSupported", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyFrequencyPoint = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FrequencyPoint", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("FrequencyPointIndex");
    public static final DJIKeyInfo<List<Integer>> KeyAvailableChannelNumbers = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "AvailableChannelNumbers", new SingleValueConverter<List, IntListMsg>(List.class, IntListMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyChannelNumber = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ChannelNumber", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<ChannelSelectionMode> KeyChannelSelectionMode = new DJIKeyInfo<ChannelSelectionMode>(componentType.value(), subComponentType.value(), "ChannelSelectionMode", new SingleValueConverter<ChannelSelectionMode, ChannelSelectionModeMsg>(ChannelSelectionMode.class, ChannelSelectionModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Bandwidth> KeyBandwidth = new DJIKeyInfo<Bandwidth>(componentType.value(), subComponentType.value(), "Bandwidth", new SingleValueConverter<Bandwidth, AirlinkBandwidthMsg>(Bandwidth.class, AirlinkBandwidthMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("AirlinkBandwidth");
    public static final DJIKeyInfo<List<Bandwidth>> KeyAirlinkBandwidthRange = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "AirlinkBandwidthRange", new SingleValueConverter<List, AirlinkBandwidthRangeMsg>(List.class, AirlinkBandwidthRangeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<IntMinMax> KeyFrequencyPointRange = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FrequencyPointRange", new DJIValueConverter<IntMinMax>(IntMinMax.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("FrequencyPointIndexRange");
    public static final DJIKeyInfo<List<SNRInfo>> KeySNRInfo = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "SNRInfo", new SingleValueConverter<List, SNRInfoMsg>(List.class, SNRInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<SDRHdOffsetParams> KeySDRHdOffsetParams = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SDRHdOffsetParams", new DJIValueConverter<SDRHdOffsetParams>(SDRHdOffsetParams.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<FrequencyInterferenceInfo>> KeyFrequencyInterference = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "FrequencyInterference", new SingleValueConverter<List, FrequencyPointRSSIInfo>(List.class, FrequencyPointRSSIInfo.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("FrequencyPointRSSIInfo");
    public static final DJIKeyInfo<FreqStrengthInfo> KeyFreqStrengthInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FreqStrengthInfo", new DJIValueConverter<FreqStrengthInfo>(FreqStrengthInfo.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyLinkSignalQuality = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LinkSignalQuality", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyDynamicDataRate = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DynamicDataRate", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<MasterLiveVideoCameraMsg> KeyMasterLiveVideoCamera = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MasterLiveVideoCamera", new DJIValueConverter<MasterLiveVideoCameraMsg>(MasterLiveVideoCameraMsg.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIs5G = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Is5G", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeySDRAveragePower = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SDRAveragePower", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<SDRDistanceLossReason> KeySDRDistanceLossReason = new DJIKeyInfo<SDRDistanceLossReason>(componentType.value(), subComponentType.value(), "SDRDistanceLossReason", new SingleValueConverter<SDRDistanceLossReason, SDRDistanceLossReasonMsg>(SDRDistanceLossReason.class, SDRDistanceLossReasonMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeySDRCurrentDataRate = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SDRCurrentDataRate", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<CameraVideoStreamType, EmptyMsg> KeySendCameraVideoCapability = new DJIActionKeyInfo<CameraVideoStreamType, EmptyMsg>(componentType.value(), subComponentType.value(), "SendCameraVideoCapability", new SingleValueConverter<CameraVideoStreamType, CameraVideoStreamTypeMsg>(CameraVideoStreamType.class, CameraVideoStreamTypeMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<Integer, Integer> KeySendMaxDecodeFramerate = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SendMaxDecodeFramerate", SingleValueConverter.IntegerConverter, SingleValueConverter.IntegerConverter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<Boolean, EmptyMsg> KeyEnableAutoFramerate = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "EnableAutoFramerate", SingleValueConverter.BooleanConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<LinkMode> KeyLinkModeControlLinkMode = new DJIKeyInfo<LinkMode>(componentType.value(), subComponentType.value(), "LinkModeControlLinkMode", new SingleValueConverter<LinkMode, LinkModeMsg>(LinkMode.class, LinkModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<LinkMode> KeyRelayLinkModeControlLinkMode = new DJIKeyInfo<LinkMode>(componentType.value(), subComponentType.value(), "RelayLinkModeControlLinkMode", new SingleValueConverter<LinkMode, LinkModeMsg>(LinkMode.class, LinkModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyLinkModeControlPerforming = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LinkModeControlPerforming", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyUpLinkBandwidth = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UpLinkBandwidth", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsWlmServiceModeSupport = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsWlmServiceModeSupport", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<WlmDownloadServiceMode> KeyWlmDownloadServiceMode = new DJIKeyInfo<WlmDownloadServiceMode>(componentType.value(), subComponentType.value(), "WlmDownloadServiceMode", new SingleValueConverter<WlmDownloadServiceMode, WlmDownloadServiceModeMsg>(WlmDownloadServiceMode.class, WlmDownloadServiceModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<WlmLinkQualityLevelInfo> KeyWlmLinkQualityLevel;
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyResetFactorySettings;
    public static final DJIKeyInfo<WlmLinkStatus> KeyWlmLinkStatus;
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyRequestPairing;
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopPairing;
    public static final DJIKeyInfo<WlmDongleListInfo> KeyWlmAircraftDongleListInfo;
    public static final DJIKeyInfo<WlmDongleListInfo> KeyWlmRcDongleListInfo;
    public static final DJIKeyInfo<WlmDongleListInfo> KeyWlmDockDongleInfo;
    public static final DJIKeyInfo<WlmNewDongleInfoMsg> KeyWlmUavNewDongleInfo;
    public static final DJIKeyInfo<WlmNewDongleInfoMsg> KeyWlmRcNewDongleInfo;
    public static final DJIKeyInfo<WlmNewDongleInfoMsg> KeyWlmDockNewDongleInfo;
    public static final DJIKeyInfo<WlmRttInfoList> KeyWlmUpCmdRttInfo;
    public static final DJIKeyInfo<LTENetDongleInfos> KeyLTENetDongleInfo;
    public static final DJIKeyInfo<WlmConnectingDevicesInfo> KeyWlmConnectingDevices;
    public static final DJIKeyInfo<PairingState> KeyPairingState;
    public static final DJIActionKeyInfo<WlmStartLinkTestInfo, EmptyMsg> KeyWlmStartLinkTest;
    public static final DJIActionKeyInfo<Integer, EmptyMsg> KeyWlmStopLinkTest;
    public static final DJIKeyInfo<WlmLinkTestResultInfo> KeyWlmLinkTestResultInfo;
    public static final DJIKeyInfo<Integer> KeySDRMaxUploadRate;
    public static final DJIKeyInfo<UploadMcsType> KeyUploadMcsMode;
    public static final DJIActionKeyInfo<WlmWriteDongleApnInfo, EmptyMsg> KeyWlmWriteDongleApnInfo;
    public static final DJIActionKeyInfo<WlmReadDongleApnInfo, WlmDongleApnInfo> KeyWlmReadDongleApnInfo;
    public static final DJIActionKeyInfo<WlmAgentFreqInfo, EmptyMsg> KeyReportWlmAgentFreqInfo;
    public static final DJIKeyInfo<Mavic3AirLinkFirmwareSupportInfo> KeyMavic3AirLinkFirmwareSupportInfo;
    public static final DJIKeyInfo<AirLinkFirmwareSupportInfo> KeyAirLinkFirmwareSupportInfo;
    public static final DJIKeyInfo<RelayFuncStatusMsg> KeyRelayFuncStatus;
    public static final DJIActionKeyInfo<RelayRequestPeerMsg, EmptyMsg> KeyRelayRequestPeer;
    public static final DJIActionKeyInfo<byte[], byte[]> KeyRelayFuncTLV;
    public static final DJIKeyInfo<MultiDevicesFpvSwitchMsg> KeyMultiDevicesFpvSwitch;
    public static final DJIKeyInfo<HdvtMode> KeyHdvtMode;
    public static final DJIActionKeyInfo<DongleReleaseReqMsg, DongleReleaseNoteMsg> KeyQueryWlmDongleUpgradeReleaseNote;
    public static final DJIActionKeyInfo<LteTestRequestMsg, EmptyMsg> KeyRequestLteTest;
    public static final DJIActionKeyInfo<WlmDongleSubscribeInfoReqMsg, WlmDongleSubscribeInfoMsg> KeyReadWlmDongleSubscribeInfo;
    public static final DJIKeyInfo<LTEPrivatizationServerMsg> KeyAircraftLTEPrivatizationServerInfo;
    public static final DJIKeyInfo<LTEPrivatizationServerMsg> KeyRcLTEPrivatizationServerInfo;
    public static final DJIActionKeyInfo<ClearLTEPrivatizationServerInfo, EmptyMsg> KeyClearLTEPrivatizationServerInfo;
    public static final DJIKeyInfo<LteTriSIMModeMsg> KeyLteTriSIMModeSwitch;
    public static final DJIActionKeyInfo<WlmDeviceType, LteTriSIMModeMsg> KeyLteTriSIMMode;
    public static final DJIKeyInfo<WlmSIMCardInfoMsg> KeyWlmUavSIMCardInfo;
    public static final DJIKeyInfo<WlmSIMCardInfoMsg> KeyWlmRcSIMCardInfo;
    public static final DJIKeyInfo<WlmLinkDiagnosisMsg> KeyWlmUavLinkDiagnosis;
    public static final DJIActionKeyInfo<WlmESIMInfoMsg, Boolean> KeyWlmUavESIMOptionInfo;
    public static final DJIKeyInfo<WlmLinkDiagnosisMsg> KeyWlmRcLinkDiagnosis;
    public static final DJIKeyInfo<WlmLinkDiagnosisMsg> KeyWlmDockLinkDiagnosis;
    public static final DJIKeyInfo<WlmTriSIMCardISPMsg> KeyWlmUavTriSIMCardISP;
    public static final DJIKeyInfo<WlmTriSIMCardISPMsg> KeyWlmRcTriSIMCardISP;
    public static final DJIKeyInfo<LTENetcardInfos> KeyLTENetInfo;
    public static final DJIActionKeyInfo<WlmESIMInfoMsg, Boolean> KeyWlmRcESIMOptionInfo;
    public static final DJIKeyInfo<WlmESIMActivateInfo> KeyWlmUavESIMActivateInfo;
    public static final DJIKeyInfo<WlmESIMActivateInfo> KeyWlmRcESIMActivateInfo;
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyWlmStopUavESIMActivateInfo;
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyWlmStopRcESIMActivateInfo;
    public static final DJIKeyInfo<Sub2GAuthStateMsg> KeySub2GAuthState;
    public static final DJIActionKeyInfo<SDRQualityDetectReqMsg, SDRQualityDetectRspMsg> KeySDRQualityDetect;
    public static final DJIActionKeyInfo<RcImuReportMsg, EmptyMsg> KeyRcImuReport;
    public static final DJIKeyInfo<List<ChannelPriorityParam>> KeyChannelPriority;
    public static final DJIActionKeyInfo<Integer, EmptyMsg> KeyM300RTKRequestIFrame;
    public static final DJIActionKeyInfo<Integer, EmptyMsg> KeyPM430RequestIFrameReset;
    public static final DJIKeyInfo<List<VideoSourceEntity>> KeyAvailableVideoSource;
    public static final DJIKeyInfo<List<LiveVideoSourceEntity>> KeyLiveVideoSource;
    public static final DJIKeyInfo<List<VideoSourceEntity>> KeyAvailablePlaybackSource;
    public static final DJIKeyInfo<List<LiveVideoSourceEntity>> KeyLivePlaybackSource;
    public static final DJIKeyInfo<List<LiveVideoSourceEntity>> KeyLiveLTEVideoSource;
    public static final DJIActionKeyInfo<List<ManageSourceParam>, EmptyMsg> KeyManageSDRSource;
    public static final DJIActionKeyInfo<List<ManageSourceParam>, EmptyMsg> KeyManageLTESource;
    public static final DJIKeyInfo<ChannelCodecFormatSetting> KeyChannelCodecFormat;
    public static final DJIKeyInfo<Integer> KeyMasterScreenSource;
    public static final DJIActionKeyInfo<ManageChannelWhilePlaybackModeChangeParam, Integer> KeyManageChannelWhilePlaybackModeChange;
    public static final DJIKeyInfo<LiveViewResolution> KeyLiveViewMaxResolution;
    public static final DJIKeyInfo<LiveViewResolution> KeyLiveViewCurrentResolution;
    public static final DJIKeyInfo<LiveViewResolution> KeyLiveViewSetResolution;
    public static final DJIKeyInfo<Integer> KeyMasterScreenInfoNew;
    public static final DJIKeyInfo<Integer> KeyMasterGimbal;
    public static final DJIKeyInfo<Integer> KeyDeviceID;
    public static final DJIKeyInfo<Boolean> KeyConnection;
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyForceUpdateCacheValue;
    public static final DJIKeyInfo<CalibrationFileStatus> KeyCalibrationFileStatus;
    public static final DJIKeyInfo<CalibrationFileUpdatingInfo> KeyCalibrationFileUpdatingInfo;
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyUpdateCalibrationFile;
    public static final DJIKeyInfo<UpgradeNotifyInfo> KeyUpgradeNotifyInfo;
    public static final DJIKeyInfo<Boolean> KeyEnforceUpgradeEnable;
    public static final DJIKeyInfo<Boolean> KeyIsInEnforceUpgradeStatus;
    public static final DJIKeyInfo<Boolean> KeyIsDirectDevice;
    public static final DJIKeyInfo<CommonFileUpdatingInfo> KeyCommonFileUpdatingInfo;
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyStartCommonFileUpdate;
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopCommonFileUpdate;
    public static final DJIActionKeyInfo<SelfDiagnosticInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticMode;
    public static final DJIActionKeyInfo<SelfDiagnosticRequestInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticRequest;
    public static final DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode> KeySelfDiagnosticCancel;
    public static final DJIKeyInfo<SelfDiagnosticProgress> KeySelfDiagnosticStatus;
    public static final DJIActionKeyInfo<SelfDiagnosticCapability, SelfDiagnosticPartsInfo> KeySelfDiagnosticParts;

    static {
        KeyWlmLinkMode = new DJIKeyInfo<WlmLinkMode>(componentType.value(), subComponentType.value(), "WlmLinkMode", new SingleValueConverter<WlmLinkMode, WlmLinkModeMsg>(WlmLinkMode.class, WlmLinkModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyWlmLinkQualityLevel = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmLinkQualityLevel", new DJIValueConverter<WlmLinkQualityLevelInfo>(WlmLinkQualityLevelInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("WlmLinkQuality");
        KeyResetFactorySettings = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "ResetFactorySettings", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyWlmLinkStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmLinkStatus", new DJIValueConverter<WlmLinkStatus>(WlmLinkStatus.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("WlmLinkState");
        KeyRequestPairing = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "RequestPairing", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyStopPairing = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopPairing", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyWlmAircraftDongleListInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmAircraftDongleListInfo", new DJIValueConverter<WlmDongleListInfo>(WlmDongleListInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("WlmUavDongleInfo");
        KeyWlmRcDongleListInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmRcDongleListInfo", new DJIValueConverter<WlmDongleListInfo>(WlmDongleListInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("WlmRcDongleInfo");
        KeyWlmDockDongleInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmDockDongleInfo", new DJIValueConverter<WlmDongleListInfo>(WlmDongleListInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyWlmUavNewDongleInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmUavNewDongleInfo", new DJIValueConverter<WlmNewDongleInfoMsg>(WlmNewDongleInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyWlmRcNewDongleInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmRcNewDongleInfo", new DJIValueConverter<WlmNewDongleInfoMsg>(WlmNewDongleInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyWlmDockNewDongleInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmDockNewDongleInfo", new DJIValueConverter<WlmNewDongleInfoMsg>(WlmNewDongleInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyWlmUpCmdRttInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmUpCmdRttInfo", new DJIValueConverter<WlmRttInfoList>(WlmRttInfoList.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyLTENetDongleInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LTENetDongleInfo", new DJIValueConverter<LTENetDongleInfos>(LTENetDongleInfos.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyWlmConnectingDevices = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmConnectingDevices", new DJIValueConverter<WlmConnectingDevicesInfo>(WlmConnectingDevicesInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyPairingState = new DJIKeyInfo<PairingState>(componentType.value(), subComponentType.value(), "PairingState", new SingleValueConverter<PairingState, PairingStateMsg>(PairingState.class, PairingStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyWlmStartLinkTest = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "WlmStartLinkTest", new DJIValueConverter<WlmStartLinkTestInfo>(WlmStartLinkTestInfo.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false).setInnerIdentifier("StartWlmLinkTest");
        KeyWlmStopLinkTest = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "WlmStopLinkTest", SingleValueConverter.IntegerConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false).setInnerIdentifier("StopWlmLinkTest");
        KeyWlmLinkTestResultInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmLinkTestResultInfo", new DJIValueConverter<WlmLinkTestResultInfo>(WlmLinkTestResultInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeySDRMaxUploadRate = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SDRMaxUploadRate", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyUploadMcsMode = new DJIKeyInfo<UploadMcsType>(componentType.value(), subComponentType.value(), "UploadMcsMode", new SingleValueConverter<UploadMcsType, UploadMcsTypeMsg>(UploadMcsType.class, UploadMcsTypeMsg.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
        KeyWlmWriteDongleApnInfo = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "WlmWriteDongleApnInfo", new DJIValueConverter<WlmWriteDongleApnInfo>(WlmWriteDongleApnInfo.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false).setInnerIdentifier("WriteWlmDongleApnInfo");
        KeyWlmReadDongleApnInfo = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "WlmReadDongleApnInfo", new DJIValueConverter<WlmReadDongleApnInfo>(WlmReadDongleApnInfo.class), new DJIValueConverter<WlmDongleApnInfo>(WlmDongleApnInfo.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false).setInnerIdentifier("ReadWlmDongleApnInfo");
        KeyReportWlmAgentFreqInfo = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ReportWlmAgentFreqInfo", new DJIValueConverter<WlmAgentFreqInfo>(WlmAgentFreqInfo.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyMavic3AirLinkFirmwareSupportInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Mavic3AirLinkFirmwareSupportInfo", new DJIValueConverter<Mavic3AirLinkFirmwareSupportInfo>(Mavic3AirLinkFirmwareSupportInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("WM260AirLinkFirmwareSupportInfo");
        KeyAirLinkFirmwareSupportInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AirLinkFirmwareSupportInfo", new DJIValueConverter<AirLinkFirmwareSupportInfo>(AirLinkFirmwareSupportInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyRelayFuncStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelayFuncStatus", new DJIValueConverter<RelayFuncStatusMsg>(RelayFuncStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyRelayRequestPeer = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RelayRequestPeer", new DJIValueConverter<RelayRequestPeerMsg>(RelayRequestPeerMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyRelayFuncTLV = new DJIActionKeyInfo<byte[], byte[]>(componentType.value(), subComponentType.value(), "RelayFuncTLV", BufferConverter.converter, BufferConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyMultiDevicesFpvSwitch = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MultiDevicesFpvSwitch", new DJIValueConverter<MultiDevicesFpvSwitchMsg>(MultiDevicesFpvSwitchMsg.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
        KeyHdvtMode = new DJIKeyInfo<HdvtMode>(componentType.value(), subComponentType.value(), "HdvtMode", new SingleValueConverter<HdvtMode, HdvtModeMsg>(HdvtMode.class, HdvtModeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyQueryWlmDongleUpgradeReleaseNote = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "QueryWlmDongleUpgradeReleaseNote", new DJIValueConverter<DongleReleaseReqMsg>(DongleReleaseReqMsg.class), new DJIValueConverter<DongleReleaseNoteMsg>(DongleReleaseNoteMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyRequestLteTest = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RequestLteTest", new DJIValueConverter<LteTestRequestMsg>(LteTestRequestMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyWlmLiveServiceMode = new DJIKeyInfo<WlmLiveServiceMode>(componentType.value(), subComponentType.value(), "WlmLiveServiceMode", new SingleValueConverter<WlmLiveServiceMode, WlmLiveServiceModeMsg>(WlmLiveServiceMode.class, WlmLiveServiceModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyReadWlmDongleSubscribeInfo = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ReadWlmDongleSubscribeInfo", new DJIValueConverter<WlmDongleSubscribeInfoReqMsg>(WlmDongleSubscribeInfoReqMsg.class), new DJIValueConverter<WlmDongleSubscribeInfoMsg>(WlmDongleSubscribeInfoMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyAircraftLTEPrivatizationServerInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AircraftLTEPrivatizationServerInfo", new DJIValueConverter<LTEPrivatizationServerMsg>(LTEPrivatizationServerMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyRcLTEPrivatizationServerInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcLTEPrivatizationServerInfo", new DJIValueConverter<LTEPrivatizationServerMsg>(LTEPrivatizationServerMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyClearLTEPrivatizationServerInfo = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ClearLTEPrivatizationServerInfo", new DJIValueConverter<ClearLTEPrivatizationServerInfo>(ClearLTEPrivatizationServerInfo.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyLteTriSIMModeSwitch = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LteTriSIMModeSwitch", new DJIValueConverter<LteTriSIMModeMsg>(LteTriSIMModeMsg.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
        KeyLteTriSIMMode = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "LteTriSIMMode", new SingleValueConverter<WlmDeviceType, WlmDeviceMsg>(WlmDeviceType.class, WlmDeviceMsg.class), new DJIValueConverter<LteTriSIMModeMsg>(LteTriSIMModeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyWlmUavSIMCardInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmUavSIMCardInfo", new DJIValueConverter<WlmSIMCardInfoMsg>(WlmSIMCardInfoMsg.class)).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
        KeyWlmRcSIMCardInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmRcSIMCardInfo", new DJIValueConverter<WlmSIMCardInfoMsg>(WlmSIMCardInfoMsg.class)).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
        KeyWlmUavLinkDiagnosis = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmUavLinkDiagnosis", new DJIValueConverter<WlmLinkDiagnosisMsg>(WlmLinkDiagnosisMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyWlmUavESIMOptionInfo = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "WlmUavESIMOptionInfo", new DJIValueConverter<WlmESIMInfoMsg>(WlmESIMInfoMsg.class), SingleValueConverter.BooleanConverter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyWlmRcLinkDiagnosis = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmRcLinkDiagnosis", new DJIValueConverter<WlmLinkDiagnosisMsg>(WlmLinkDiagnosisMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyWlmDockLinkDiagnosis = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmDockLinkDiagnosis", new DJIValueConverter<WlmLinkDiagnosisMsg>(WlmLinkDiagnosisMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyWlmUavTriSIMCardISP = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmUavTriSIMCardISP", new DJIValueConverter<WlmTriSIMCardISPMsg>(WlmTriSIMCardISPMsg.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
        KeyWlmRcTriSIMCardISP = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmRcTriSIMCardISP", new DJIValueConverter<WlmTriSIMCardISPMsg>(WlmTriSIMCardISPMsg.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
        KeyLTENetInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LTENetInfo", new DJIValueConverter<LTENetcardInfos>(LTENetcardInfos.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyWlmRcESIMOptionInfo = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "WlmRcESIMOptionInfo", new DJIValueConverter<WlmESIMInfoMsg>(WlmESIMInfoMsg.class), SingleValueConverter.BooleanConverter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyWlmUavESIMActivateInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmUavESIMActivateInfo", new DJIValueConverter<WlmESIMActivateInfo>(WlmESIMActivateInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyWlmRcESIMActivateInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WlmRcESIMActivateInfo", new DJIValueConverter<WlmESIMActivateInfo>(WlmESIMActivateInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyWlmStopUavESIMActivateInfo = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "WlmStopUavESIMActivateInfo", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyWlmStopRcESIMActivateInfo = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "WlmStopRcESIMActivateInfo", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeySub2GAuthState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Sub2GAuthState", new DJIValueConverter<Sub2GAuthStateMsg>(Sub2GAuthStateMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
        KeySDRQualityDetect = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SDRQualityDetect", new DJIValueConverter<SDRQualityDetectReqMsg>(SDRQualityDetectReqMsg.class), new DJIValueConverter<SDRQualityDetectRspMsg>(SDRQualityDetectRspMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyRcImuReport = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RcImuReport", new DJIValueConverter<RcImuReportMsg>(RcImuReportMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyChannelPriority = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "ChannelPriority", new SingleValueConverter<List, ChannelPriorityMsg>(List.class, ChannelPriorityMsg.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
        KeyM300RTKRequestIFrame = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "M300RTKRequestIFrame", SingleValueConverter.IntegerConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false).setInnerIdentifier("PM430RequestIFrame");
        KeyPM430RequestIFrameReset = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "PM430RequestIFrameReset", SingleValueConverter.IntegerConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyAvailableVideoSource = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "AvailableVideoSource", new SingleValueConverter<List, AvailableVideoSourceInfo>(List.class, AvailableVideoSourceInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyLiveVideoSource = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "LiveVideoSource", new SingleValueConverter<List, LiveVideoSourceInfo>(List.class, LiveVideoSourceInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyAvailablePlaybackSource = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "AvailablePlaybackSource", new SingleValueConverter<List, AvailableVideoSourceInfo>(List.class, AvailableVideoSourceInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyLivePlaybackSource = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "LivePlaybackSource", new SingleValueConverter<List, LiveVideoSourceInfo>(List.class, LiveVideoSourceInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyLiveLTEVideoSource = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "LiveLTEVideoSource", new SingleValueConverter<List, LiveVideoSourceInfo>(List.class, LiveVideoSourceInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyManageSDRSource = new DJIActionKeyInfo<List, EmptyMsg>(componentType.value(), subComponentType.value(), "ManageSDRSource", new SingleValueConverter<List, ManageSourceParams>(List.class, ManageSourceParams.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyManageLTESource = new DJIActionKeyInfo<List, EmptyMsg>(componentType.value(), subComponentType.value(), "ManageLTESource", new SingleValueConverter<List, ManageSourceParams>(List.class, ManageSourceParams.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyChannelCodecFormat = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ChannelCodecFormat", new DJIValueConverter<ChannelCodecFormatSetting>(ChannelCodecFormatSetting.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
        KeyMasterScreenSource = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MasterScreenSource", SingleValueConverter.IntegerConverter).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
        KeyManageChannelWhilePlaybackModeChange = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ManageChannelWhilePlaybackModeChange", new DJIValueConverter<ManageChannelWhilePlaybackModeChangeParam>(ManageChannelWhilePlaybackModeChangeParam.class), SingleValueConverter.IntegerConverter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyLiveViewMaxResolution = new DJIKeyInfo<LiveViewResolution>(componentType.value(), subComponentType.value(), "LiveViewMaxResolution", new SingleValueConverter<LiveViewResolution, LiveViewResolutionhMsg>(LiveViewResolution.class, LiveViewResolutionhMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyLiveViewCurrentResolution = new DJIKeyInfo<LiveViewResolution>(componentType.value(), subComponentType.value(), "LiveViewCurrentResolution", new SingleValueConverter<LiveViewResolution, LiveViewResolutionhMsg>(LiveViewResolution.class, LiveViewResolutionhMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyLiveViewSetResolution = new DJIKeyInfo<LiveViewResolution>(componentType.value(), subComponentType.value(), "LiveViewSetResolution", new SingleValueConverter<LiveViewResolution, LiveViewResolutionhMsg>(LiveViewResolution.class, LiveViewResolutionhMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyMasterScreenInfoNew = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MasterScreenInfoNew", SingleValueConverter.IntegerConverter).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
        KeyMasterGimbal = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MasterGimbal", SingleValueConverter.IntegerConverter).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
        KeyDeviceID = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DeviceID", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyConnection = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Connection", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyForceUpdateCacheValue = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ForceUpdateCacheValue", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyCalibrationFileStatus = new DJIKeyInfo<CalibrationFileStatus>(componentType.value(), subComponentType.value(), "CalibrationFileStatus", new SingleValueConverter<CalibrationFileStatus, CalibrationFileStatusMsg>(CalibrationFileStatus.class, CalibrationFileStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyCalibrationFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CalibrationFileUpdatingInfo", new DJIValueConverter<CalibrationFileUpdatingInfo>(CalibrationFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyUpdateCalibrationFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "UpdateCalibrationFile", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyUpgradeNotifyInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UpgradeNotifyInfo", new DJIValueConverter<UpgradeNotifyInfo>(UpgradeNotifyInfo.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
        KeyEnforceUpgradeEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "EnforceUpgradeEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
        KeyIsInEnforceUpgradeStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsInEnforceUpgradeStatus", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyIsDirectDevice = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsDirectDevice", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyCommonFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CommonFileUpdatingInfo", new DJIValueConverter<CommonFileUpdatingInfo>(CommonFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeyStartCommonFileUpdate = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StartCommonFileUpdate", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeyStopCommonFileUpdate = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopCommonFileUpdate", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeySelfDiagnosticMode = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticMode", new DJIValueConverter<SelfDiagnosticInfo>(SelfDiagnosticInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeySelfDiagnosticRequest = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticRequest", new DJIValueConverter<SelfDiagnosticRequestInfo>(SelfDiagnosticRequestInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeySelfDiagnosticCancel = new DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode>(componentType.value(), subComponentType.value(), "SelfDiagnosticCancel", EmptyValueConverter.converter, new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        KeySelfDiagnosticStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticStatus", new DJIValueConverter<SelfDiagnosticProgress>(SelfDiagnosticProgress.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
        KeySelfDiagnosticParts = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticParts", new SingleValueConverter<SelfDiagnosticCapability, SelfDiagnosticCapabilityMsg>(SelfDiagnosticCapability.class, SelfDiagnosticCapabilityMsg.class), new DJIValueConverter<SelfDiagnosticPartsInfo>(SelfDiagnosticPartsInfo.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
        keyList.add(KeyLightbridgeDataRate);
        keyList.add(KeyUpLinkQuality);
        keyList.add(KeyDownLinkQuality);
        keyList.add(KeyTTD4Existed);
        keyList.add(KeyUpLinkQualityRaw);
        keyList.add(KeyDownLinkQualityRaw);
        keyList.add(KeyBaseBand);
        keyList.add(KeyRcAntennaRssi);
        keyList.add(KeyAircraftAntennaRssi);
        keyList.add(KeyLeftCameraType);
        keyList.add(KeyRightCameraType);
        keyList.add(KeyFPVCameraType);
        keyList.add(KeyPrimaryVideoFeedCameraType);
        keyList.add(KeySecondaryVideoFeedCameraType);
        keyList.add(KeySecondaryVideoFeedPhysicalSource);
        keyList.add(KeyPrimaryVideoFeedPhysicalSource);
        keyList.add(KeyPrimaryVideoFeedBandwidth);
        keyList.add(KeyAllocatePhysicalSource);
        keyList.add(KeyMasterScreen);
        keyList.add(KeyWiFiMagneticInterferenceLevel);
        keyList.add(KeyQueryAreaCodeSupportInfo);
        keyList.add(KeyAreaCodeFromGround);
        keyList.add(KeyAirLinkType);
        keyList.add(KeyFrequencyBand);
        keyList.add(KeyFrequencyBandRange);
        keyList.add(KeyIsDualBandSupported);
        keyList.add(KeyIsSub2GSupported);
        keyList.add(KeyIs5Dot7GSupported);
        keyList.add(KeyIs1Dot4GSupported);
        keyList.add(KeyFrequencyPoint);
        keyList.add(KeyAvailableChannelNumbers);
        keyList.add(KeyChannelNumber);
        keyList.add(KeyChannelSelectionMode);
        keyList.add(KeyBandwidth);
        keyList.add(KeyAirlinkBandwidthRange);
        keyList.add(KeyFrequencyPointRange);
        keyList.add(KeySNRInfo);
        keyList.add(KeySDRHdOffsetParams);
        keyList.add(KeyFrequencyInterference);
        keyList.add(KeyFreqStrengthInfo);
        keyList.add(KeyLinkSignalQuality);
        keyList.add(KeyDynamicDataRate);
        keyList.add(KeyMasterLiveVideoCamera);
        keyList.add(KeyIs5G);
        keyList.add(KeySDRAveragePower);
        keyList.add(KeySDRDistanceLossReason);
        keyList.add(KeySDRCurrentDataRate);
        keyList.add(KeySendCameraVideoCapability);
        keyList.add(KeySendMaxDecodeFramerate);
        keyList.add(KeyEnableAutoFramerate);
        keyList.add(KeyLinkModeControlLinkMode);
        keyList.add(KeyRelayLinkModeControlLinkMode);
        keyList.add(KeyLinkModeControlPerforming);
        keyList.add(KeyUpLinkBandwidth);
        keyList.add(KeyIsWlmServiceModeSupport);
        keyList.add(KeyWlmDownloadServiceMode);
        keyList.add(KeyWlmLinkQualityLevel);
        keyList.add(KeyResetFactorySettings);
        keyList.add(KeyWlmLinkStatus);
        keyList.add(KeyRequestPairing);
        keyList.add(KeyStopPairing);
        keyList.add(KeyWlmAircraftDongleListInfo);
        keyList.add(KeyWlmRcDongleListInfo);
        keyList.add(KeyWlmDockDongleInfo);
        keyList.add(KeyWlmUavNewDongleInfo);
        keyList.add(KeyWlmRcNewDongleInfo);
        keyList.add(KeyWlmDockNewDongleInfo);
        keyList.add(KeyWlmUpCmdRttInfo);
        keyList.add(KeyLTENetDongleInfo);
        keyList.add(KeyWlmConnectingDevices);
        keyList.add(KeyPairingState);
        keyList.add(KeyWlmStartLinkTest);
        keyList.add(KeyWlmStopLinkTest);
        keyList.add(KeyWlmLinkTestResultInfo);
        keyList.add(KeySDRMaxUploadRate);
        keyList.add(KeyUploadMcsMode);
        keyList.add(KeyWlmWriteDongleApnInfo);
        keyList.add(KeyWlmReadDongleApnInfo);
        keyList.add(KeyReportWlmAgentFreqInfo);
        keyList.add(KeyMavic3AirLinkFirmwareSupportInfo);
        keyList.add(KeyAirLinkFirmwareSupportInfo);
        keyList.add(KeyRelayFuncStatus);
        keyList.add(KeyRelayRequestPeer);
        keyList.add(KeyRelayFuncTLV);
        keyList.add(KeyMultiDevicesFpvSwitch);
        keyList.add(KeyHdvtMode);
        keyList.add(KeyQueryWlmDongleUpgradeReleaseNote);
        keyList.add(KeyRequestLteTest);
        keyList.add(KeyReadWlmDongleSubscribeInfo);
        keyList.add(KeyAircraftLTEPrivatizationServerInfo);
        keyList.add(KeyRcLTEPrivatizationServerInfo);
        keyList.add(KeyClearLTEPrivatizationServerInfo);
        keyList.add(KeyLteTriSIMModeSwitch);
        keyList.add(KeyLteTriSIMMode);
        keyList.add(KeyWlmUavSIMCardInfo);
        keyList.add(KeyWlmRcSIMCardInfo);
        keyList.add(KeyWlmUavLinkDiagnosis);
        keyList.add(KeyWlmUavESIMOptionInfo);
        keyList.add(KeyWlmRcLinkDiagnosis);
        keyList.add(KeyWlmDockLinkDiagnosis);
        keyList.add(KeyWlmUavTriSIMCardISP);
        keyList.add(KeyWlmRcTriSIMCardISP);
        keyList.add(KeyLTENetInfo);
        keyList.add(KeyWlmRcESIMOptionInfo);
        keyList.add(KeyWlmUavESIMActivateInfo);
        keyList.add(KeyWlmRcESIMActivateInfo);
        keyList.add(KeyWlmStopUavESIMActivateInfo);
        keyList.add(KeyWlmStopRcESIMActivateInfo);
        keyList.add(KeySub2GAuthState);
        keyList.add(KeySDRQualityDetect);
        keyList.add(KeyRcImuReport);
        keyList.add(KeyChannelPriority);
        keyList.add(KeyM300RTKRequestIFrame);
        keyList.add(KeyPM430RequestIFrameReset);
        keyList.add(KeyAvailableVideoSource);
        keyList.add(KeyLiveVideoSource);
        keyList.add(KeyAvailablePlaybackSource);
        keyList.add(KeyLivePlaybackSource);
        keyList.add(KeyLiveLTEVideoSource);
        keyList.add(KeyManageSDRSource);
        keyList.add(KeyManageLTESource);
        keyList.add(KeyChannelCodecFormat);
        keyList.add(KeyMasterScreenSource);
        keyList.add(KeyManageChannelWhilePlaybackModeChange);
        keyList.add(KeyLiveViewMaxResolution);
        keyList.add(KeyLiveViewCurrentResolution);
        keyList.add(KeyLiveViewSetResolution);
        keyList.add(KeyMasterScreenInfoNew);
        keyList.add(KeyMasterGimbal);
        keyList.add(KeyDeviceID);
        keyList.add(KeyConnection);
        keyList.add(KeyForceUpdateCacheValue);
        keyList.add(KeyCalibrationFileStatus);
        keyList.add(KeyCalibrationFileUpdatingInfo);
        keyList.add(KeyUpdateCalibrationFile);
        keyList.add(KeyUpgradeNotifyInfo);
        keyList.add(KeyEnforceUpgradeEnable);
        keyList.add(KeyIsInEnforceUpgradeStatus);
        keyList.add(KeyIsDirectDevice);
        keyList.add(KeyCommonFileUpdatingInfo);
        keyList.add(KeyStartCommonFileUpdate);
        keyList.add(KeyStopCommonFileUpdate);
        keyList.add(KeySelfDiagnosticMode);
        keyList.add(KeySelfDiagnosticRequest);
        keyList.add(KeySelfDiagnosticCancel);
        keyList.add(KeySelfDiagnosticStatus);
        keyList.add(KeySelfDiagnosticParts);
    }
}

