/*
 * Decompiled with CFR 0.152.
 */
package dji.sdk.keyvalue.key;

import dji.sdk.keyvalue.converter.DJIValueConverter;
import dji.sdk.keyvalue.converter.EmptyValueConverter;
import dji.sdk.keyvalue.converter.SingleValueConverter;
import dji.sdk.keyvalue.key.ComponentType;
import dji.sdk.keyvalue.key.DJIActionKeyInfo;
import dji.sdk.keyvalue.key.DJIKeyInfo;
import dji.sdk.keyvalue.key.SubComponentType;
import dji.sdk.keyvalue.value.common.CalibrationFileStatus;
import dji.sdk.keyvalue.value.common.CalibrationFileStatusMsg;
import dji.sdk.keyvalue.value.common.CalibrationFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.CommonFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.EmptyMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapability;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapabilityMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCode;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCodeMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticPartsInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticProgress;
import dji.sdk.keyvalue.value.common.SelfDiagnosticRequestInfo;
import dji.sdk.keyvalue.value.common.UpgradeNotifyInfo;
import dji.sdk.keyvalue.value.lidar.EchoMode;
import dji.sdk.keyvalue.value.lidar.EchoModeMsg;
import dji.sdk.keyvalue.value.lidar.EchoModeRangeMsg;
import dji.sdk.keyvalue.value.lidar.HighSensitivityMode;
import dji.sdk.keyvalue.value.lidar.HighSensitivityModeSwitchMsg;
import dji.sdk.keyvalue.value.lidar.LidarCurWorkStateMsg;
import dji.sdk.keyvalue.value.lidar.LidarDataSampleRateMode;
import dji.sdk.keyvalue.value.lidar.LidarDataSampleRateMsg;
import dji.sdk.keyvalue.value.lidar.LidarDataSampleRateRangeMsg;
import dji.sdk.keyvalue.value.lidar.LidarSelfCalibrationStateMsg;
import dji.sdk.keyvalue.value.lidar.PayloadPOSStatusInfoMsg;
import dji.sdk.keyvalue.value.lidar.PointCloudExclusiveMsg;
import dji.sdk.keyvalue.value.lidar.PointCloudExclusiveStatus;
import dji.sdk.keyvalue.value.lidar.PointCloudRecordCommand;
import dji.sdk.keyvalue.value.lidar.PointCloudRecordMsg;
import dji.sdk.keyvalue.value.lidar.PointCloudRecordStatus;
import dji.sdk.keyvalue.value.lidar.PointCloudRecordStatusMsg;
import dji.sdk.keyvalue.value.lidar.ScanMode;
import dji.sdk.keyvalue.value.lidar.ScanModeMsg;
import dji.sdk.keyvalue.value.lidar.ScanModeRangeMsg;
import dji.sdk.keyvalue.value.lidar.VisibleLightPixelMode;
import dji.sdk.keyvalue.value.lidar.VisibleLightPixelMsg;
import java.util.ArrayList;
import java.util.List;

public class DJILidarKey {
    protected static final List<DJIKeyInfo<?>> keyList = new ArrayList();
    private static final ComponentType componentType = ComponentType.LIDAR;
    private static final SubComponentType subComponentType = SubComponentType.IGNORE;
    public static final DJIKeyInfo<String> KeySerialNumber = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SerialNumber", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyFirmwareVersion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FirmwareVersion", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<PointCloudRecordCommand, EmptyMsg> KeyPointCloudRecord = new DJIActionKeyInfo<PointCloudRecordCommand, EmptyMsg>(componentType.value(), subComponentType.value(), "PointCloudRecord", new SingleValueConverter<PointCloudRecordCommand, PointCloudRecordMsg>(PointCloudRecordCommand.class, PointCloudRecordMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<PointCloudExclusiveStatus> KeyPointCloudExclusiveStatus = new DJIKeyInfo<PointCloudExclusiveStatus>(componentType.value(), subComponentType.value(), "PointCloudExclusiveStatus", new SingleValueConverter<PointCloudExclusiveStatus, PointCloudExclusiveMsg>(PointCloudExclusiveStatus.class, PointCloudExclusiveMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<PointCloudRecordStatus> KeyPointCloudRecordStatus = new DJIKeyInfo<PointCloudRecordStatus>(componentType.value(), subComponentType.value(), "PointCloudRecordStatus", new SingleValueConverter<PointCloudRecordStatus, PointCloudRecordStatusMsg>(PointCloudRecordStatus.class, PointCloudRecordStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<ScanMode> KeyScanMode = new DJIKeyInfo<ScanMode>(componentType.value(), subComponentType.value(), "ScanMode", new SingleValueConverter<ScanMode, ScanModeMsg>(ScanMode.class, ScanModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<EchoMode> KeyEchoMode = new DJIKeyInfo<EchoMode>(componentType.value(), subComponentType.value(), "EchoMode", new SingleValueConverter<EchoMode, EchoModeMsg>(EchoMode.class, EchoModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<HighSensitivityMode> KeyHighSensitivityModeSwitch = new DJIKeyInfo<HighSensitivityMode>(componentType.value(), subComponentType.value(), "HighSensitivityModeSwitch", new SingleValueConverter<HighSensitivityMode, HighSensitivityModeSwitchMsg>(HighSensitivityMode.class, HighSensitivityModeSwitchMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<VisibleLightPixelMode> KeyVisibleLightPixel = new DJIKeyInfo<VisibleLightPixelMode>(componentType.value(), subComponentType.value(), "VisibleLightPixel", new SingleValueConverter<VisibleLightPixelMode, VisibleLightPixelMsg>(VisibleLightPixelMode.class, VisibleLightPixelMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<LidarDataSampleRateMode> KeyLidarDataSampleRate = new DJIKeyInfo<LidarDataSampleRateMode>(componentType.value(), subComponentType.value(), "LidarDataSampleRate", new SingleValueConverter<LidarDataSampleRateMode, LidarDataSampleRateMsg>(LidarDataSampleRateMode.class, LidarDataSampleRateMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<PayloadPOSStatusInfoMsg> KeyPayloadPOSStatusInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PayloadPOSStatusInfo", new DJIValueConverter<PayloadPOSStatusInfoMsg>(PayloadPOSStatusInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, Integer> KeyStartLidarSelfCalibration = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StartLidarSelfCalibration", EmptyValueConverter.converter, SingleValueConverter.IntegerConverter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, Integer> KeyStopLidarSelfCalibration = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StopLidarSelfCalibration", EmptyValueConverter.converter, SingleValueConverter.IntegerConverter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, Integer> KeyConfirmLidarSelfCalibrationResult = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ConfirmLidarSelfCalibrationResult", EmptyValueConverter.converter, SingleValueConverter.IntegerConverter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<LidarSelfCalibrationStateMsg> KeyLidarSelfCalibrationState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LidarSelfCalibrationState", new DJIValueConverter<LidarSelfCalibrationStateMsg>(LidarSelfCalibrationStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<LidarDataSampleRateMode>> KeyLidarDataSampleRateRange = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "LidarDataSampleRateRange", new SingleValueConverter<List, LidarDataSampleRateRangeMsg>(List.class, LidarDataSampleRateRangeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<ScanMode>> KeyScanModeRange = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "ScanModeRange", new SingleValueConverter<List, ScanModeRangeMsg>(List.class, ScanModeRangeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<EchoMode>> KeyEchoModeRange = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "EchoModeRange", new SingleValueConverter<List, EchoModeRangeMsg>(List.class, EchoModeRangeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyLidarParamWaylineHeight = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LidarParamWaylineHeight", SingleValueConverter.IntegerConverter).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<LidarCurWorkStateMsg> KeyLidarDataCurWorkState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LidarDataCurWorkState", new DJIValueConverter<LidarCurWorkStateMsg>(LidarCurWorkStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyDeviceID = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DeviceID", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyConnection = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Connection", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyForceUpdateCacheValue = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ForceUpdateCacheValue", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileStatus> KeyCalibrationFileStatus = new DJIKeyInfo<CalibrationFileStatus>(componentType.value(), subComponentType.value(), "CalibrationFileStatus", new SingleValueConverter<CalibrationFileStatus, CalibrationFileStatusMsg>(CalibrationFileStatus.class, CalibrationFileStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileUpdatingInfo> KeyCalibrationFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CalibrationFileUpdatingInfo", new DJIValueConverter<CalibrationFileUpdatingInfo>(CalibrationFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyUpdateCalibrationFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "UpdateCalibrationFile", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<UpgradeNotifyInfo> KeyUpgradeNotifyInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UpgradeNotifyInfo", new DJIValueConverter<UpgradeNotifyInfo>(UpgradeNotifyInfo.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyEnforceUpgradeEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "EnforceUpgradeEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsInEnforceUpgradeStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsInEnforceUpgradeStatus", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsDirectDevice = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsDirectDevice", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CommonFileUpdatingInfo> KeyCommonFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CommonFileUpdatingInfo", new DJIValueConverter<CommonFileUpdatingInfo>(CommonFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyStartCommonFileUpdate = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StartCommonFileUpdate", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopCommonFileUpdate = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopCommonFileUpdate", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticMode = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticMode", new DJIValueConverter<SelfDiagnosticInfo>(SelfDiagnosticInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticRequestInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticRequest = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticRequest", new DJIValueConverter<SelfDiagnosticRequestInfo>(SelfDiagnosticRequestInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode> KeySelfDiagnosticCancel = new DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode>(componentType.value(), subComponentType.value(), "SelfDiagnosticCancel", EmptyValueConverter.converter, new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<SelfDiagnosticProgress> KeySelfDiagnosticStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticStatus", new DJIValueConverter<SelfDiagnosticProgress>(SelfDiagnosticProgress.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticCapability, SelfDiagnosticPartsInfo> KeySelfDiagnosticParts = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticParts", new SingleValueConverter<SelfDiagnosticCapability, SelfDiagnosticCapabilityMsg>(SelfDiagnosticCapability.class, SelfDiagnosticCapabilityMsg.class), new DJIValueConverter<SelfDiagnosticPartsInfo>(SelfDiagnosticPartsInfo.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);

    static {
        keyList.add(KeySerialNumber);
        keyList.add(KeyFirmwareVersion);
        keyList.add(KeyPointCloudRecord);
        keyList.add(KeyPointCloudExclusiveStatus);
        keyList.add(KeyPointCloudRecordStatus);
        keyList.add(KeyScanMode);
        keyList.add(KeyEchoMode);
        keyList.add(KeyHighSensitivityModeSwitch);
        keyList.add(KeyVisibleLightPixel);
        keyList.add(KeyLidarDataSampleRate);
        keyList.add(KeyPayloadPOSStatusInfo);
        keyList.add(KeyStartLidarSelfCalibration);
        keyList.add(KeyStopLidarSelfCalibration);
        keyList.add(KeyConfirmLidarSelfCalibrationResult);
        keyList.add(KeyLidarSelfCalibrationState);
        keyList.add(KeyLidarDataSampleRateRange);
        keyList.add(KeyScanModeRange);
        keyList.add(KeyEchoModeRange);
        keyList.add(KeyLidarParamWaylineHeight);
        keyList.add(KeyLidarDataCurWorkState);
        keyList.add(KeyDeviceID);
        keyList.add(KeyConnection);
        keyList.add(KeyForceUpdateCacheValue);
        keyList.add(KeyCalibrationFileStatus);
        keyList.add(KeyCalibrationFileUpdatingInfo);
        keyList.add(KeyUpdateCalibrationFile);
        keyList.add(KeyUpgradeNotifyInfo);
        keyList.add(KeyEnforceUpgradeEnable);
        keyList.add(KeyIsInEnforceUpgradeStatus);
        keyList.add(KeyIsDirectDevice);
        keyList.add(KeyCommonFileUpdatingInfo);
        keyList.add(KeyStartCommonFileUpdate);
        keyList.add(KeyStopCommonFileUpdate);
        keyList.add(KeySelfDiagnosticMode);
        keyList.add(KeySelfDiagnosticRequest);
        keyList.add(KeySelfDiagnosticCancel);
        keyList.add(KeySelfDiagnosticStatus);
        keyList.add(KeySelfDiagnosticParts);
    }
}

