/*
 * Decompiled with CFR 0.152.
 */
package dji.sdk.keyvalue.key;

import dji.sdk.keyvalue.converter.DJIValueConverter;
import dji.sdk.keyvalue.converter.EmptyValueConverter;
import dji.sdk.keyvalue.converter.SingleValueConverter;
import dji.sdk.keyvalue.key.ComponentType;
import dji.sdk.keyvalue.key.DJIActionKeyInfo;
import dji.sdk.keyvalue.key.DJIKeyInfo;
import dji.sdk.keyvalue.key.SubComponentType;
import dji.sdk.keyvalue.value.common.CalibrationFileStatus;
import dji.sdk.keyvalue.value.common.CalibrationFileStatusMsg;
import dji.sdk.keyvalue.value.common.CalibrationFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.CommonFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.EmptyMsg;
import dji.sdk.keyvalue.value.common.LocationCoordinate3D;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapability;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapabilityMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCode;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCodeMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticPartsInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticProgress;
import dji.sdk.keyvalue.value.common.SelfDiagnosticRequestInfo;
import dji.sdk.keyvalue.value.common.UpgradeNotifyInfo;
import dji.sdk.keyvalue.value.rtkbasestation.RTKReferenceStationSource;
import dji.sdk.keyvalue.value.rtkbasestation.RTKReferenceStationSourceMsg;
import dji.sdk.keyvalue.value.rtkmobilestation.DistanceToHomeInfo;
import dji.sdk.keyvalue.value.rtkmobilestation.NtripNetworkRtkConfigInfo;
import dji.sdk.keyvalue.value.rtkmobilestation.RTKAntennaType;
import dji.sdk.keyvalue.value.rtkmobilestation.RTKAntennaTypeMsg;
import dji.sdk.keyvalue.value.rtkmobilestation.RTKError;
import dji.sdk.keyvalue.value.rtkmobilestation.RTKErrorMsg;
import dji.sdk.keyvalue.value.rtkmobilestation.RTKHeading;
import dji.sdk.keyvalue.value.rtkmobilestation.RTKHomePointInfo;
import dji.sdk.keyvalue.value.rtkmobilestation.RTKLocation;
import dji.sdk.keyvalue.value.rtkmobilestation.RTKSatelliteInfo;
import dji.sdk.keyvalue.value.rtkmobilestation.RTKSingnalType;
import dji.sdk.keyvalue.value.rtkmobilestation.RTKSingnalTypeMsg;
import dji.sdk.keyvalue.value.rtkmobilestation.RTKTakeoffAltitudeInfo;
import dji.sdk.keyvalue.value.rtkmobilestation.RTKUndulationType;
import dji.sdk.keyvalue.value.rtkmobilestation.RTKUndulationTypeMsg;
import java.util.ArrayList;
import java.util.List;

public class DJIRtkMobileStationKey {
    protected static final List<DJIKeyInfo<?>> keyList = new ArrayList();
    private static final ComponentType componentType = ComponentType.RTKMOBILESTATION;
    private static final SubComponentType subComponentType = SubComponentType.IGNORE;
    public static final DJIKeyInfo<RTKReferenceStationSource> KeyFCRealRTKReferenceSource = new DJIKeyInfo<RTKReferenceStationSource>(componentType.value(), subComponentType.value(), "FCRealRTKReferenceSource", new SingleValueConverter<RTKReferenceStationSource, RTKReferenceStationSourceMsg>(RTKReferenceStationSource.class, RTKReferenceStationSourceMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyRTKDongleSN = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKDongleSN", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<NtripNetworkRtkConfigInfo> KeyNtripNetworkRtkConfigInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "NtripNetworkRtkConfigInfo", new DJIValueConverter<NtripNetworkRtkConfigInfo>(NtripNetworkRtkConfigInfo.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsRTKDongleConnect = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsRTKDongleConnect", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyRTKEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<LocationCoordinate3D> KeyRTKFusionMobileStationLocation = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKFusionMobileStationLocation", new DJIValueConverter<LocationCoordinate3D>(LocationCoordinate3D.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyRTKFusionMobileHeading = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKFusionMobileHeading", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsRTKConnected = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsRTKConnected", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsRTKWorking = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsRTKWorking", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyRTKSatelliteCount = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKSatelliteCount", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKError> KeyRTKError = new DJIKeyInfo<RTKError>(componentType.value(), subComponentType.value(), "RTKError", new SingleValueConverter<RTKError, RTKErrorMsg>(RTKError.class, RTKErrorMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKLocation> KeyRTKLocation = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKLocation", new DJIValueConverter<RTKLocation>(RTKLocation.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyLatitudeStandardDeviation = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LatitudeStandardDeviation", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyLongitudeStandardDeviation = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LongitudeStandardDeviation", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyHeightStandardDeviation = new DJIKeyInfo(componentType.value(), subComponentType.value(), "HeightStandardDeviation", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKSatelliteInfo> KeyRTKSatelliteInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKSatelliteInfo", new DJIValueConverter<RTKSatelliteInfo>(RTKSatelliteInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKHeading> KeyRTKHeading = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKHeading", new DJIValueConverter<RTKHeading>(RTKHeading.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKAntennaType> KeyRTKAntennaType = new DJIKeyInfo<RTKAntennaType>(componentType.value(), subComponentType.value(), "RTKAntennaType", new SingleValueConverter<RTKAntennaType, RTKAntennaTypeMsg>(RTKAntennaType.class, RTKAntennaTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsRTKBeingUsed = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsRTKBeingUsed", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsInRTKMode = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsInRTKMode", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyRTKAbsoluteAltitude = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKAbsoluteAltitude", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKHomePointInfo> KeyRTKHomePointInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKHomePointInfo", new DJIValueConverter<RTKHomePointInfo>(RTKHomePointInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKTakeoffAltitudeInfo> KeyRTKTakeoffAltitudeInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKTakeoffAltitudeInfo", new DJIValueConverter<RTKTakeoffAltitudeInfo>(RTKTakeoffAltitudeInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyRTKUndulation = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKUndulation", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyGPSAltitudeOfAircraftCentre = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GPSAltitudeOfAircraftCentre", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<DistanceToHomeInfo> KeyDistanceToHomeInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DistanceToHomeInfo", new DJIValueConverter<DistanceToHomeInfo>(DistanceToHomeInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKUndulationType> KeyRTKUndulationType = new DJIKeyInfo<RTKUndulationType>(componentType.value(), subComponentType.value(), "RTKUndulationType", new SingleValueConverter<RTKUndulationType, RTKUndulationTypeMsg>(RTKUndulationType.class, RTKUndulationTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKSingnalType> KeyRTKSingnalType = new DJIKeyInfo<RTKSingnalType>(componentType.value(), subComponentType.value(), "RTKSingnalType", new SingleValueConverter<RTKSingnalType, RTKSingnalTypeMsg>(RTKSingnalType.class, RTKSingnalTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsRTKFusionDataUsable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsRTKFusionDataUsable", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyRTKKeepStatusEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKKeepStatusEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyRTKkeepStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKkeepStatus", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyRTKPositioningStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKPositioningStatus", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStartDroneRtkCalibration = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StartDroneRtkCalibration", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyDeviceID = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DeviceID", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyConnection = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Connection", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyForceUpdateCacheValue = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ForceUpdateCacheValue", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileStatus> KeyCalibrationFileStatus = new DJIKeyInfo<CalibrationFileStatus>(componentType.value(), subComponentType.value(), "CalibrationFileStatus", new SingleValueConverter<CalibrationFileStatus, CalibrationFileStatusMsg>(CalibrationFileStatus.class, CalibrationFileStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileUpdatingInfo> KeyCalibrationFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CalibrationFileUpdatingInfo", new DJIValueConverter<CalibrationFileUpdatingInfo>(CalibrationFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyUpdateCalibrationFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "UpdateCalibrationFile", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<UpgradeNotifyInfo> KeyUpgradeNotifyInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UpgradeNotifyInfo", new DJIValueConverter<UpgradeNotifyInfo>(UpgradeNotifyInfo.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyEnforceUpgradeEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "EnforceUpgradeEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsInEnforceUpgradeStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsInEnforceUpgradeStatus", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsDirectDevice = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsDirectDevice", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CommonFileUpdatingInfo> KeyCommonFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CommonFileUpdatingInfo", new DJIValueConverter<CommonFileUpdatingInfo>(CommonFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyStartCommonFileUpdate = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StartCommonFileUpdate", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopCommonFileUpdate = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopCommonFileUpdate", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticMode = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticMode", new DJIValueConverter<SelfDiagnosticInfo>(SelfDiagnosticInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticRequestInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticRequest = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticRequest", new DJIValueConverter<SelfDiagnosticRequestInfo>(SelfDiagnosticRequestInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode> KeySelfDiagnosticCancel = new DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode>(componentType.value(), subComponentType.value(), "SelfDiagnosticCancel", EmptyValueConverter.converter, new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<SelfDiagnosticProgress> KeySelfDiagnosticStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticStatus", new DJIValueConverter<SelfDiagnosticProgress>(SelfDiagnosticProgress.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticCapability, SelfDiagnosticPartsInfo> KeySelfDiagnosticParts = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticParts", new SingleValueConverter<SelfDiagnosticCapability, SelfDiagnosticCapabilityMsg>(SelfDiagnosticCapability.class, SelfDiagnosticCapabilityMsg.class), new DJIValueConverter<SelfDiagnosticPartsInfo>(SelfDiagnosticPartsInfo.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);

    static {
        keyList.add(KeyFCRealRTKReferenceSource);
        keyList.add(KeyRTKDongleSN);
        keyList.add(KeyNtripNetworkRtkConfigInfo);
        keyList.add(KeyIsRTKDongleConnect);
        keyList.add(KeyRTKEnable);
        keyList.add(KeyRTKFusionMobileStationLocation);
        keyList.add(KeyRTKFusionMobileHeading);
        keyList.add(KeyIsRTKConnected);
        keyList.add(KeyIsRTKWorking);
        keyList.add(KeyRTKSatelliteCount);
        keyList.add(KeyRTKError);
        keyList.add(KeyRTKLocation);
        keyList.add(KeyLatitudeStandardDeviation);
        keyList.add(KeyLongitudeStandardDeviation);
        keyList.add(KeyHeightStandardDeviation);
        keyList.add(KeyRTKSatelliteInfo);
        keyList.add(KeyRTKHeading);
        keyList.add(KeyRTKAntennaType);
        keyList.add(KeyIsRTKBeingUsed);
        keyList.add(KeyIsInRTKMode);
        keyList.add(KeyRTKAbsoluteAltitude);
        keyList.add(KeyRTKHomePointInfo);
        keyList.add(KeyRTKTakeoffAltitudeInfo);
        keyList.add(KeyRTKUndulation);
        keyList.add(KeyGPSAltitudeOfAircraftCentre);
        keyList.add(KeyDistanceToHomeInfo);
        keyList.add(KeyRTKUndulationType);
        keyList.add(KeyRTKSingnalType);
        keyList.add(KeyIsRTKFusionDataUsable);
        keyList.add(KeyRTKKeepStatusEnable);
        keyList.add(KeyRTKkeepStatus);
        keyList.add(KeyRTKPositioningStatus);
        keyList.add(KeyStartDroneRtkCalibration);
        keyList.add(KeyDeviceID);
        keyList.add(KeyConnection);
        keyList.add(KeyForceUpdateCacheValue);
        keyList.add(KeyCalibrationFileStatus);
        keyList.add(KeyCalibrationFileUpdatingInfo);
        keyList.add(KeyUpdateCalibrationFile);
        keyList.add(KeyUpgradeNotifyInfo);
        keyList.add(KeyEnforceUpgradeEnable);
        keyList.add(KeyIsInEnforceUpgradeStatus);
        keyList.add(KeyIsDirectDevice);
        keyList.add(KeyCommonFileUpdatingInfo);
        keyList.add(KeyStartCommonFileUpdate);
        keyList.add(KeyStopCommonFileUpdate);
        keyList.add(KeySelfDiagnosticMode);
        keyList.add(KeySelfDiagnosticRequest);
        keyList.add(KeySelfDiagnosticCancel);
        keyList.add(KeySelfDiagnosticStatus);
        keyList.add(KeySelfDiagnosticParts);
    }
}

