/*
 * Decompiled with CFR 0.152.
 */
package dji.sdk.keyvalue.key;

import dji.sdk.keyvalue.converter.DJIValueConverter;
import dji.sdk.keyvalue.converter.EmptyValueConverter;
import dji.sdk.keyvalue.converter.SingleValueConverter;
import dji.sdk.keyvalue.key.ComponentType;
import dji.sdk.keyvalue.key.DJIActionKeyInfo;
import dji.sdk.keyvalue.key.DJIKeyInfo;
import dji.sdk.keyvalue.key.SubComponentType;
import dji.sdk.keyvalue.value.common.Attitude;
import dji.sdk.keyvalue.value.common.CalibrationFileStatus;
import dji.sdk.keyvalue.value.common.CalibrationFileStatusMsg;
import dji.sdk.keyvalue.value.common.CalibrationFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.CommonFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.EmptyMsg;
import dji.sdk.keyvalue.value.common.LocationCoordinate3D;
import dji.sdk.keyvalue.value.common.RelayProductTypeListMsg;
import dji.sdk.keyvalue.value.common.SDRQualityDetectReqMsg;
import dji.sdk.keyvalue.value.common.SDRQualityDetectRspMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapability;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapabilityMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCode;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCodeMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticPartsInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticProgress;
import dji.sdk.keyvalue.value.common.SelfDiagnosticRequestInfo;
import dji.sdk.keyvalue.value.common.UpgradeNotifyInfo;
import dji.sdk.keyvalue.value.relay.RelayBatteryInfoMsg;
import dji.sdk.keyvalue.value.relay.RelayPDInfoMsg;
import dji.sdk.keyvalue.value.relay.RelayPOEInfoMsg;
import dji.sdk.keyvalue.value.relay.RelayPowerSupplyMsg;
import dji.sdk.keyvalue.value.relay.RelayRtkCoordCaliMsg;
import dji.sdk.keyvalue.value.relay.RelayRtkCoordConfigMsg;
import dji.sdk.keyvalue.value.relay.RelayRtkCoordRealtimeMsg;
import dji.sdk.keyvalue.value.relay.RelayRtkNumSatelliteMsg;
import dji.sdk.keyvalue.value.relay.RelaySDRSignalInfo;
import dji.sdk.keyvalue.value.relay.RelaySDRSignalInfoMsg;
import dji.sdk.keyvalue.value.relay.RelaySdrRoleType;
import dji.sdk.keyvalue.value.relay.RelaySdrRoleTypeMsg;
import dji.sdk.keyvalue.value.relay.RelaySearchStatusMsg;
import dji.sdk.keyvalue.value.relay.RelayType;
import dji.sdk.keyvalue.value.relay.RelayTypeMsg;
import dji.sdk.keyvalue.value.relay.RelayTypeStatisticsMsg;
import dji.sdk.keyvalue.value.relay.RelayWorkMode;
import dji.sdk.keyvalue.value.relay.RelayWorkModeMsg;
import dji.sdk.keyvalue.value.relay.RelayWorkModeProductInfo;
import dji.sdk.keyvalue.value.relay.RelayWorkModeProductSwitchState;
import dji.sdk.keyvalue.value.relay.RelayWorkModeProductSwitchStateMsg;
import dji.sdk.keyvalue.value.relay.RelayWorkStatus;
import dji.sdk.keyvalue.value.relay.RelayWorkStatusMsg;
import dji.sdk.keyvalue.value.relay.SDRBlockingInfoMsg;
import dji.sdk.keyvalue.value.relay.SyncDataInRelayNetMsg;
import java.util.ArrayList;
import java.util.List;

public class DJIRelayKey {
    protected static final List<DJIKeyInfo<?>> keyList = new ArrayList();
    private static final ComponentType componentType = ComponentType.RELAY;
    private static final SubComponentType subComponentType = SubComponentType.IGNORE;
    public static final DJIKeyInfo<String> KeyRelaySerialNumber = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelaySerialNumber", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RelayType> KeyRelayType = new DJIKeyInfo<RelayType>(componentType.value(), subComponentType.value(), "RelayType", new SingleValueConverter<RelayType, RelayTypeMsg>(RelayType.class, RelayTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RelayWorkMode> KeyRelayWorkMode = new DJIKeyInfo<RelayWorkMode>(componentType.value(), subComponentType.value(), "RelayWorkMode", new SingleValueConverter<RelayWorkMode, RelayWorkModeMsg>(RelayWorkMode.class, RelayWorkModeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RelayWorkStatus> KeyRelayWorkStatus = new DJIKeyInfo<RelayWorkStatus>(componentType.value(), subComponentType.value(), "RelayWorkStatus", new SingleValueConverter<RelayWorkStatus, RelayWorkStatusMsg>(RelayWorkStatus.class, RelayWorkStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RelayPOEInfoMsg> KeyRelayPOEInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelayPOEInfo", new DJIValueConverter<RelayPOEInfoMsg>(RelayPOEInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RelayPDInfoMsg> KeyRelayPDInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelayPDInfo", new DJIValueConverter<RelayPDInfoMsg>(RelayPDInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RelayPowerSupplyMsg> KeyRelayPowerSupply = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelayPowerSupply", new DJIValueConverter<RelayPowerSupplyMsg>(RelayPowerSupplyMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RelayBatteryInfoMsg> KeyRelayBatteryInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelayBatteryInfo", new DJIValueConverter<RelayBatteryInfoMsg>(RelayBatteryInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<RelaySDRSignalInfo>> KeyRelaySDRSignalInfo = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "RelaySDRSignalInfo", new SingleValueConverter<List, RelaySDRSignalInfoMsg>(List.class, RelaySDRSignalInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RelayRtkCoordRealtimeMsg> KeyRelayRtkCoordRealtime = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelayRtkCoordRealtime", new DJIValueConverter<RelayRtkCoordRealtimeMsg>(RelayRtkCoordRealtimeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RelayRtkCoordCaliMsg> KeyRelayRtkCoordCali = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelayRtkCoordCali", new DJIValueConverter<RelayRtkCoordCaliMsg>(RelayRtkCoordCaliMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RelayRtkCoordConfigMsg> KeyRelayRtkCoordConfig = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelayRtkCoordConfig", new DJIValueConverter<RelayRtkCoordConfigMsg>(RelayRtkCoordConfigMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RelayRtkNumSatelliteMsg> KeyRelayRtkNumSatellite = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelayRtkNumSatellite", new DJIValueConverter<RelayRtkNumSatelliteMsg>(RelayRtkNumSatelliteMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyRelayRtkGNSSSignalLevel = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelayRtkGNSSSignalLevel", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyRelayFirmwareVersion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelayFirmwareVersion", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyRelayRequestPairing = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "RelayRequestPairing", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyRelayStopPairing = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "RelayStopPairing", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<RelayWorkModeProductInfo> KeyRelaySupportProducts = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelaySupportProducts", new DJIValueConverter<RelayWorkModeProductInfo>(RelayWorkModeProductInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RelayWorkModeProductSwitchState> KeyRelayWorkProductTypeSwitchState = new DJIKeyInfo<RelayWorkModeProductSwitchState>(componentType.value(), subComponentType.value(), "RelayWorkProductTypeSwitchState", new SingleValueConverter<RelayWorkModeProductSwitchState, RelayWorkModeProductSwitchStateMsg>(RelayWorkModeProductSwitchState.class, RelayWorkModeProductSwitchStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<SDRQualityDetectReqMsg, SDRQualityDetectRspMsg> KeySDRQualityDetect = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SDRQualityDetect", new DJIValueConverter<SDRQualityDetectReqMsg>(SDRQualityDetectReqMsg.class), new DJIValueConverter<SDRQualityDetectRspMsg>(SDRQualityDetectRspMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyLatitudeStandardDeviation = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LatitudeStandardDeviation", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyLongitudeStandardDeviation = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LongitudeStandardDeviation", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyHeightStandardDeviation = new DJIKeyInfo(componentType.value(), subComponentType.value(), "HeightStandardDeviation", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyRelayCountryCode = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelayCountryCode", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RelaySdrRoleType> KeyRelayRoleType = new DJIKeyInfo<RelaySdrRoleType>(componentType.value(), subComponentType.value(), "RelayRoleType", new SingleValueConverter<RelaySdrRoleType, RelaySdrRoleTypeMsg>(RelaySdrRoleType.class, RelaySdrRoleTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsDirectToRc = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsDirectToRc", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<LocationCoordinate3D> KeyAircraftLocation3D = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AircraftLocation3D", new DJIValueConverter<LocationCoordinate3D>(LocationCoordinate3D.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyTakeoffLocationAltitude = new DJIKeyInfo(componentType.value(), subComponentType.value(), "TakeoffLocationAltitude", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Attitude> KeyAircraftAttitude = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AircraftAttitude", new DJIValueConverter<Attitude>(Attitude.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("Attitude");
    public static final DJIKeyInfo<Boolean> KeyAreMotorsOn = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AreMotorsOn", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsFlying = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsFlying", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyBatteryPercentNeededToGoHome = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryPercentNeededToGoHome", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyBatteryPercentNeededToLand = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryPercentNeededToLand", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyRemainingFlightTime = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RemainingFlightTime", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyWorkingFlightTime = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WorkingFlightTime", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyChargeRemainingInPercent = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ChargeRemainingInPercent", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyTotalRemainingInPercent = new DJIKeyInfo(componentType.value(), subComponentType.value(), "TotalRemainingInPercent", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<SDRBlockingInfoMsg> KeySDRBlockingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SDRBlockingInfo", new DJIValueConverter<SDRBlockingInfoMsg>(SDRBlockingInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStartRcRelayPairing = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StartRcRelayPairing", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopRcRelayPairing = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopRcRelayPairing", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyDirectLinkRcDeviceId = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DirectLinkRcDeviceId", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<SyncDataInRelayNetMsg> KeySyncDataInRelayNet = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SyncDataInRelayNet", new DJIValueConverter<SyncDataInRelayNetMsg>(SyncDataInRelayNetMsg.class)).canGet(false).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsRelayLinked = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsRelayLinked", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeySubscribeRelayUavAutoAlignment = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "SubscribeRelayUavAutoAlignment", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyUnsubscribeRelayUavAutoAlignment = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "UnsubscribeRelayUavAutoAlignment", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, RelayProductTypeListMsg> KeySupportRelayedByProductTypeRange = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SupportRelayedByProductTypeRange", EmptyValueConverter.converter, new DJIValueConverter<RelayProductTypeListMsg>(RelayProductTypeListMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, RelayProductTypeListMsg> KeySupportRelayProductTypeRange = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SupportRelayProductTypeRange", EmptyValueConverter.converter, new DJIValueConverter<RelayProductTypeListMsg>(RelayProductTypeListMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<RelaySearchStatusMsg> KeyRelaySearchStatusPush = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelaySearchStatusPush", new DJIValueConverter<RelaySearchStatusMsg>(RelaySearchStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RelayType> KeyRelayTypeForOtherDev = new DJIKeyInfo<RelayType>(componentType.value(), subComponentType.value(), "RelayTypeForOtherDev", new SingleValueConverter<RelayType, RelayTypeMsg>(RelayType.class, RelayTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RelayTypeStatisticsMsg> KeyRelayTypeStatistics = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelayTypeStatistics", new DJIValueConverter<RelayTypeStatisticsMsg>(RelayTypeStatisticsMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyDeviceID = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DeviceID", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyConnection = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Connection", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyForceUpdateCacheValue = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ForceUpdateCacheValue", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileStatus> KeyCalibrationFileStatus = new DJIKeyInfo<CalibrationFileStatus>(componentType.value(), subComponentType.value(), "CalibrationFileStatus", new SingleValueConverter<CalibrationFileStatus, CalibrationFileStatusMsg>(CalibrationFileStatus.class, CalibrationFileStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileUpdatingInfo> KeyCalibrationFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CalibrationFileUpdatingInfo", new DJIValueConverter<CalibrationFileUpdatingInfo>(CalibrationFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyUpdateCalibrationFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "UpdateCalibrationFile", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<UpgradeNotifyInfo> KeyUpgradeNotifyInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UpgradeNotifyInfo", new DJIValueConverter<UpgradeNotifyInfo>(UpgradeNotifyInfo.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyEnforceUpgradeEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "EnforceUpgradeEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsInEnforceUpgradeStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsInEnforceUpgradeStatus", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsDirectDevice = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsDirectDevice", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CommonFileUpdatingInfo> KeyCommonFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CommonFileUpdatingInfo", new DJIValueConverter<CommonFileUpdatingInfo>(CommonFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyStartCommonFileUpdate = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StartCommonFileUpdate", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopCommonFileUpdate = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopCommonFileUpdate", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticMode = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticMode", new DJIValueConverter<SelfDiagnosticInfo>(SelfDiagnosticInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticRequestInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticRequest = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticRequest", new DJIValueConverter<SelfDiagnosticRequestInfo>(SelfDiagnosticRequestInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode> KeySelfDiagnosticCancel = new DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode>(componentType.value(), subComponentType.value(), "SelfDiagnosticCancel", EmptyValueConverter.converter, new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<SelfDiagnosticProgress> KeySelfDiagnosticStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticStatus", new DJIValueConverter<SelfDiagnosticProgress>(SelfDiagnosticProgress.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticCapability, SelfDiagnosticPartsInfo> KeySelfDiagnosticParts = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticParts", new SingleValueConverter<SelfDiagnosticCapability, SelfDiagnosticCapabilityMsg>(SelfDiagnosticCapability.class, SelfDiagnosticCapabilityMsg.class), new DJIValueConverter<SelfDiagnosticPartsInfo>(SelfDiagnosticPartsInfo.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);

    static {
        keyList.add(KeyRelaySerialNumber);
        keyList.add(KeyRelayType);
        keyList.add(KeyRelayWorkMode);
        keyList.add(KeyRelayWorkStatus);
        keyList.add(KeyRelayPOEInfo);
        keyList.add(KeyRelayPDInfo);
        keyList.add(KeyRelayPowerSupply);
        keyList.add(KeyRelayBatteryInfo);
        keyList.add(KeyRelaySDRSignalInfo);
        keyList.add(KeyRelayRtkCoordRealtime);
        keyList.add(KeyRelayRtkCoordCali);
        keyList.add(KeyRelayRtkCoordConfig);
        keyList.add(KeyRelayRtkNumSatellite);
        keyList.add(KeyRelayRtkGNSSSignalLevel);
        keyList.add(KeyRelayFirmwareVersion);
        keyList.add(KeyRelayRequestPairing);
        keyList.add(KeyRelayStopPairing);
        keyList.add(KeyRelaySupportProducts);
        keyList.add(KeyRelayWorkProductTypeSwitchState);
        keyList.add(KeySDRQualityDetect);
        keyList.add(KeyLatitudeStandardDeviation);
        keyList.add(KeyLongitudeStandardDeviation);
        keyList.add(KeyHeightStandardDeviation);
        keyList.add(KeyRelayCountryCode);
        keyList.add(KeyRelayRoleType);
        keyList.add(KeyIsDirectToRc);
        keyList.add(KeyAircraftLocation3D);
        keyList.add(KeyTakeoffLocationAltitude);
        keyList.add(KeyAircraftAttitude);
        keyList.add(KeyAreMotorsOn);
        keyList.add(KeyIsFlying);
        keyList.add(KeyBatteryPercentNeededToGoHome);
        keyList.add(KeyBatteryPercentNeededToLand);
        keyList.add(KeyRemainingFlightTime);
        keyList.add(KeyWorkingFlightTime);
        keyList.add(KeyChargeRemainingInPercent);
        keyList.add(KeyTotalRemainingInPercent);
        keyList.add(KeySDRBlockingInfo);
        keyList.add(KeyStartRcRelayPairing);
        keyList.add(KeyStopRcRelayPairing);
        keyList.add(KeyDirectLinkRcDeviceId);
        keyList.add(KeySyncDataInRelayNet);
        keyList.add(KeyIsRelayLinked);
        keyList.add(KeySubscribeRelayUavAutoAlignment);
        keyList.add(KeyUnsubscribeRelayUavAutoAlignment);
        keyList.add(KeySupportRelayedByProductTypeRange);
        keyList.add(KeySupportRelayProductTypeRange);
        keyList.add(KeyRelaySearchStatusPush);
        keyList.add(KeyRelayTypeForOtherDev);
        keyList.add(KeyRelayTypeStatistics);
        keyList.add(KeyDeviceID);
        keyList.add(KeyConnection);
        keyList.add(KeyForceUpdateCacheValue);
        keyList.add(KeyCalibrationFileStatus);
        keyList.add(KeyCalibrationFileUpdatingInfo);
        keyList.add(KeyUpdateCalibrationFile);
        keyList.add(KeyUpgradeNotifyInfo);
        keyList.add(KeyEnforceUpgradeEnable);
        keyList.add(KeyIsInEnforceUpgradeStatus);
        keyList.add(KeyIsDirectDevice);
        keyList.add(KeyCommonFileUpdatingInfo);
        keyList.add(KeyStartCommonFileUpdate);
        keyList.add(KeyStopCommonFileUpdate);
        keyList.add(KeySelfDiagnosticMode);
        keyList.add(KeySelfDiagnosticRequest);
        keyList.add(KeySelfDiagnosticCancel);
        keyList.add(KeySelfDiagnosticStatus);
        keyList.add(KeySelfDiagnosticParts);
    }
}

