/*
 * Decompiled with CFR 0.152.
 */
package dji.sdk.keyvalue.key;

import dji.sdk.keyvalue.converter.DJIValueConverter;
import dji.sdk.keyvalue.converter.EmptyValueConverter;
import dji.sdk.keyvalue.converter.SingleValueConverter;
import dji.sdk.keyvalue.key.ComponentType;
import dji.sdk.keyvalue.key.DJIActionKeyInfo;
import dji.sdk.keyvalue.key.DJIKeyInfo;
import dji.sdk.keyvalue.key.SubComponentType;
import dji.sdk.keyvalue.value.common.CalibrationFileStatus;
import dji.sdk.keyvalue.value.common.CalibrationFileStatusMsg;
import dji.sdk.keyvalue.value.common.CalibrationFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.CommonFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.DeviceSecretResult;
import dji.sdk.keyvalue.value.common.EmptyMsg;
import dji.sdk.keyvalue.value.common.LocationCoordinate3D;
import dji.sdk.keyvalue.value.common.RTKCalibrationControlMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapability;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapabilityMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCode;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCodeMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticPartsInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticProgress;
import dji.sdk.keyvalue.value.common.SelfDiagnosticRequestInfo;
import dji.sdk.keyvalue.value.common.UpgradeNotifyInfo;
import dji.sdk.keyvalue.value.rtkbasestation.DPSStatus;
import dji.sdk.keyvalue.value.rtkbasestation.DPSStatusMsg;
import dji.sdk.keyvalue.value.rtkbasestation.DebugRTKSNRInfo;
import dji.sdk.keyvalue.value.rtkbasestation.DroneNestRtkCalibrationControl;
import dji.sdk.keyvalue.value.rtkbasestation.DroneNestRtkCalibrationControlMsg;
import dji.sdk.keyvalue.value.rtkbasestation.DroneNestRtkCoordCaliMsg;
import dji.sdk.keyvalue.value.rtkbasestation.DroneNestRtkCoordConfigMsg;
import dji.sdk.keyvalue.value.rtkbasestation.DroneNestRtkCoordRealtimeMsg;
import dji.sdk.keyvalue.value.rtkbasestation.DroneNestRtkNumSatelliteMsg;
import dji.sdk.keyvalue.value.rtkbasestation.DroneNestRtkStatisticalResultMsg;
import dji.sdk.keyvalue.value.rtkbasestation.NetworkRTKParam;
import dji.sdk.keyvalue.value.rtkbasestation.PPPActivateStateMsg;
import dji.sdk.keyvalue.value.rtkbasestation.RTKAuthEncrpytReqMsg;
import dji.sdk.keyvalue.value.rtkbasestation.RTKBaseStationBatteryState;
import dji.sdk.keyvalue.value.rtkbasestation.RTKBaseStationConnectInfoList;
import dji.sdk.keyvalue.value.rtkbasestation.RTKBaseStationConnectStateMsg;
import dji.sdk.keyvalue.value.rtkbasestation.RTKBaseStationResetPasswordInfo;
import dji.sdk.keyvalue.value.rtkbasestation.RTKCalibrationReferenceStationSourceMsg;
import dji.sdk.keyvalue.value.rtkbasestation.RTKConnectType;
import dji.sdk.keyvalue.value.rtkbasestation.RTKConnectTypeMsg;
import dji.sdk.keyvalue.value.rtkbasestation.RTKCustomNetworkServiceStateMsg;
import dji.sdk.keyvalue.value.rtkbasestation.RTKCustomNetworkSetting;
import dji.sdk.keyvalue.value.rtkbasestation.RTKDPSNetworkConfig;
import dji.sdk.keyvalue.value.rtkbasestation.RTKDongleActivateInfo;
import dji.sdk.keyvalue.value.rtkbasestation.RTKGNDLinkStatusMsg;
import dji.sdk.keyvalue.value.rtkbasestation.RTKPPPRealtimeInfoMsg;
import dji.sdk.keyvalue.value.rtkbasestation.RTKReferenceStationSource;
import dji.sdk.keyvalue.value.rtkbasestation.RTKReferenceStationSourceMsg;
import dji.sdk.keyvalue.value.rtkbasestation.RTKSNRInfo;
import dji.sdk.keyvalue.value.rtkbasestation.RTKServiceState;
import dji.sdk.keyvalue.value.rtkbasestation.RTKStationConnetState;
import dji.sdk.keyvalue.value.rtkbasestation.RTKStationInfo;
import dji.sdk.keyvalue.value.rtkbasestation.RTKSurveyorPointInfo;
import dji.sdk.keyvalue.value.rtkbasestation.RTKSurveyorPointMsg;
import dji.sdk.keyvalue.value.rtkbasestation.RtcmDataMsg;
import dji.sdk.keyvalue.value.rtkbasestation.RtkAccessInfo;
import java.util.ArrayList;
import java.util.List;

public class DJIRtkBaseStationKey {
    protected static final List<DJIKeyInfo<?>> keyList = new ArrayList();
    private static final ComponentType componentType = ComponentType.RTKBASESTATION;
    private static final SubComponentType subComponentType = SubComponentType.IGNORE;
    public static final DJIKeyInfo<String> KeySerialNumber = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SerialNumber", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyFirmwareVersion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FirmwareVersion", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKReferenceStationSource> KeyRTKReferenceStationSource = new DJIKeyInfo<RTKReferenceStationSource>(componentType.value(), subComponentType.value(), "RTKReferenceStationSource", new SingleValueConverter<RTKReferenceStationSource, RTKReferenceStationSourceMsg>(RTKReferenceStationSource.class, RTKReferenceStationSourceMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<LocationCoordinate3D> KeyRTKBaseStationReferencingPosition = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKBaseStationReferencingPosition", new DJIValueConverter<LocationCoordinate3D>(LocationCoordinate3D.class)).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyRTKBaseStationReferencingPositionReset = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "RTKBaseStationReferencingPositionReset", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<RTKCustomNetworkSetting> KeyRTKCustomNetworkSetting = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKCustomNetworkSetting", new DJIValueConverter<RTKCustomNetworkSetting>(RTKCustomNetworkSetting.class)).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKDPSNetworkConfig> KeyRTKDPSNetworkConfig = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKDPSNetworkConfig", new DJIValueConverter<RTKDPSNetworkConfig>(RTKDPSNetworkConfig.class)).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyRTKCustomNetworkServiceEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKCustomNetworkServiceEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyRTKCalibrationCustomNetworkServiceEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKCalibrationCustomNetworkServiceEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKServiceState> KeyRTKCustomNetworkServiceState = new DJIKeyInfo<RTKServiceState>(componentType.value(), subComponentType.value(), "RTKCustomNetworkServiceState", new SingleValueConverter<RTKServiceState, RTKCustomNetworkServiceStateMsg>(RTKServiceState.class, RTKCustomNetworkServiceStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKBaseStationBatteryState> KeyRTKBaseStationBatteryState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKBaseStationBatteryState", new DJIValueConverter<RTKBaseStationBatteryState>(RTKBaseStationBatteryState.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<Long, EmptyMsg> KeyRTKDongleActivate = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RTKDongleActivate", SingleValueConverter.LongConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyRTKDongleDeactivate = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "RTKDongleDeactivate", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<RTKDongleActivateInfo> KeyRTKDongleActivateInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKDongleActivateInfo", new DJIValueConverter<RTKDongleActivateInfo>(RTKDongleActivateInfo.class)).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<RTKAuthEncrpytReqMsg, String> KeyRTKAuthEncrpyt = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RTKAuthEncrpyt", new DJIValueConverter<RTKAuthEncrpytReqMsg>(RTKAuthEncrpytReqMsg.class), SingleValueConverter.StringConverter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyRTKNetworkUserId = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKNetworkUserId", SingleValueConverter.StringConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, NetworkRTKParam> KeyRTKNetworkBindDevice = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RTKNetworkBindDevice", EmptyValueConverter.converter, new DJIValueConverter<NetworkRTKParam>(NetworkRTKParam.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, NetworkRTKParam> KeyRTKNetworkRenewOrder = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RTKNetworkRenewOrder", EmptyValueConverter.converter, new DJIValueConverter<NetworkRTKParam>(NetworkRTKParam.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, NetworkRTKParam> KeyRTKNetworkActivateA = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RTKNetworkActivateA", EmptyValueConverter.converter, new DJIValueConverter<NetworkRTKParam>(NetworkRTKParam.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, NetworkRTKParam> KeyRTKNetworkActivateB = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RTKNetworkActivateB", EmptyValueConverter.converter, new DJIValueConverter<NetworkRTKParam>(NetworkRTKParam.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, NetworkRTKParam> KeyRTKNetworkRequestToUse = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RTKNetworkRequestToUse", EmptyValueConverter.converter, new DJIValueConverter<NetworkRTKParam>(NetworkRTKParam.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<String, NetworkRTKParam> KeyRTKEncDataRequest = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RTKEncDataRequest", SingleValueConverter.StringConverter, new DJIValueConverter<NetworkRTKParam>(NetworkRTKParam.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<RTKStationInfo> KeyRTKBaseStationConnectInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKBaseStationConnectInfo", new DJIValueConverter<RTKStationInfo>(RTKStationInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<DPSStatus> KeyDPSState = new DJIKeyInfo<DPSStatus>(componentType.value(), subComponentType.value(), "DPSState", new SingleValueConverter<DPSStatus, DPSStatusMsg>(DPSStatus.class, DPSStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKStationConnetState> KeyRTKBaseStationConnectState = new DJIKeyInfo<RTKStationConnetState>(componentType.value(), subComponentType.value(), "RTKBaseStationConnectState", new SingleValueConverter<RTKStationConnetState, RTKBaseStationConnectStateMsg>(RTKStationConnetState.class, RTKBaseStationConnectStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyRTKBaseStationStartSearch = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "RTKBaseStationStartSearch", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyRTKBaseStationLogInAsAdmin = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RTKBaseStationLogInAsAdmin", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyRTKBaseStationName = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKBaseStationName", SingleValueConverter.StringConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyRTKRoverDeviceName = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKRoverDeviceName", SingleValueConverter.StringConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<RTKBaseStationResetPasswordInfo, EmptyMsg> KeyRTKBaseStationResetPassword = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RTKBaseStationResetPassword", new DJIValueConverter<RTKBaseStationResetPasswordInfo>(RTKBaseStationResetPasswordInfo.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyRTKBaseStationStopSearch = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "RTKBaseStationStopSearch", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<List<RTKStationInfo>> KeyRTKBaseStationList = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "RTKBaseStationList", new SingleValueConverter<List, RTKBaseStationConnectInfoList>(List.class, RTKBaseStationConnectInfoList.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<Integer, EmptyMsg> KeyRTKBaseStationConnectAccordingId = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RTKBaseStationConnectAccordingId", SingleValueConverter.IntegerConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<RTKConnectType> KeyRTKConnectType = new DJIKeyInfo<RTKConnectType>(componentType.value(), subComponentType.value(), "RTKConnectType", new SingleValueConverter<RTKConnectType, RTKConnectTypeMsg>(RTKConnectType.class, RTKConnectTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<RtcmDataMsg, EmptyMsg> KeyRTKSendRtcmToFC = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RTKSendRtcmToFC", new DJIValueConverter<RtcmDataMsg>(RtcmDataMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyRTKBaseStationSNREnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKBaseStationSNREnable", SingleValueConverter.BooleanConverter).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<DebugRTKSNRInfo> KeyDebugGeneralRTKSNRInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DebugGeneralRTKSNRInfo", new DJIValueConverter<DebugRTKSNRInfo>(DebugRTKSNRInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKSNRInfo> KeyAnt1GPSSNRData = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Ant1GPSSNRData", new DJIValueConverter<RTKSNRInfo>(RTKSNRInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKSNRInfo> KeyAnt1GNSSSNRData = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Ant1GNSSSNRData", new DJIValueConverter<RTKSNRInfo>(RTKSNRInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKSNRInfo> KeyAnt1BDSSNRData = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Ant1BDSSNRData", new DJIValueConverter<RTKSNRInfo>(RTKSNRInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKSNRInfo> KeyAnt1GSNSSNRData = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Ant1GSNSSNRData", new DJIValueConverter<RTKSNRInfo>(RTKSNRInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKSNRInfo> KeyAnt2GPSSNRData = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Ant2GPSSNRData", new DJIValueConverter<RTKSNRInfo>(RTKSNRInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKSNRInfo> KeyAnt2GNSSSNRData = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Ant2GNSSSNRData", new DJIValueConverter<RTKSNRInfo>(RTKSNRInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKSNRInfo> KeyAnt2BDSSNRData = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Ant2BDSSNRData", new DJIValueConverter<RTKSNRInfo>(RTKSNRInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKSNRInfo> KeyAnt2GSNSSNRData = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Ant2GSNSSNRData", new DJIValueConverter<RTKSNRInfo>(RTKSNRInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKSNRInfo> KeyAntBaseStationGPSSNRData = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AntBaseStationGPSSNRData", new DJIValueConverter<RTKSNRInfo>(RTKSNRInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKSNRInfo> KeyAntBaseStationGNSSSNRData = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AntBaseStationGNSSSNRData", new DJIValueConverter<RTKSNRInfo>(RTKSNRInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKSNRInfo> KeyAntBaseStationBDSSNRData = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AntBaseStationBDSSNRData", new DJIValueConverter<RTKSNRInfo>(RTKSNRInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKSNRInfo> KeyAntBaseStationGSNSSNRData = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AntBaseStationGSNSSNRData", new DJIValueConverter<RTKSNRInfo>(RTKSNRInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<DroneNestRtkCoordRealtimeMsg> KeyDroneNestRtkCoordRealtime = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DroneNestRtkCoordRealtime", new DJIValueConverter<DroneNestRtkCoordRealtimeMsg>(DroneNestRtkCoordRealtimeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<DroneNestRtkCoordCaliMsg> KeyDroneNestRtkCoordCali = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DroneNestRtkCoordCali", new DJIValueConverter<DroneNestRtkCoordCaliMsg>(DroneNestRtkCoordCaliMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<DroneNestRtkCoordConfigMsg> KeyDroneNestRtkCoordConfig = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DroneNestRtkCoordConfig", new DJIValueConverter<DroneNestRtkCoordConfigMsg>(DroneNestRtkCoordConfigMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<DroneNestRtkNumSatelliteMsg> KeyDroneNestRtkNumSatellite = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DroneNestRtkNumSatellite", new DJIValueConverter<DroneNestRtkNumSatelliteMsg>(DroneNestRtkNumSatelliteMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyBaseStationConfigVersion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BaseStationConfigVersion", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<DroneNestRtkCalibrationControl, EmptyMsg> KeyDroneNestRtkCalibrationControl = new DJIActionKeyInfo<DroneNestRtkCalibrationControl, EmptyMsg>(componentType.value(), subComponentType.value(), "DroneNestRtkCalibrationControl", new SingleValueConverter<DroneNestRtkCalibrationControl, DroneNestRtkCalibrationControlMsg>(DroneNestRtkCalibrationControl.class, DroneNestRtkCalibrationControlMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<RTKCalibrationControlMsg, EmptyMsg> KeyRTKCalibrationControl = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RTKCalibrationControl", new DJIValueConverter<RTKCalibrationControlMsg>(RTKCalibrationControlMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<RTKCalibrationReferenceStationSourceMsg> KeyRTKCalibrationReferenceStationSource = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKCalibrationReferenceStationSource", new DJIValueConverter<RTKCalibrationReferenceStationSourceMsg>(RTKCalibrationReferenceStationSourceMsg.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RTKPPPRealtimeInfoMsg> KeyRTKPPPRealtimeInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKPPPRealtimeInfo", new DJIValueConverter<RTKPPPRealtimeInfoMsg>(RTKPPPRealtimeInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyDroneNestRtkReboot = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "DroneNestRtkReboot", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyDroneNestRtkBaseStationMode = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DroneNestRtkBaseStationMode", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyDroneNestRtkGNSSSignalLevel = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DroneNestRtkGNSSSignalLevel", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RtkAccessInfo> KeyRtkAccessInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RtkAccessInfo", new DJIValueConverter<RtkAccessInfo>(RtkAccessInfo.class)).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RtkAccessInfo> KeySharedRtkAccessInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SharedRtkAccessInfo", new DJIValueConverter<RtkAccessInfo>(RtkAccessInfo.class)).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyFreeSharedRtkAccess = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "FreeSharedRtkAccess", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, DeviceSecretResult> KeySharedRtkEncDataRequest = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SharedRtkEncDataRequest", EmptyValueConverter.converter, new DJIValueConverter<DeviceSecretResult>(DeviceSecretResult.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<DroneNestRtkStatisticalResultMsg> KeyDroneNestRtkStatisticalResult = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DroneNestRtkStatisticalResult", new DJIValueConverter<DroneNestRtkStatisticalResultMsg>(DroneNestRtkStatisticalResultMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<NetworkRTKParam, RtkAccessInfo> KeyGetRtkAccessInfoByParam = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "GetRtkAccessInfoByParam", new DJIValueConverter<NetworkRTKParam>(NetworkRTKParam.class), new DJIValueConverter<RtkAccessInfo>(RtkAccessInfo.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<RTKCustomNetworkSetting> KeyNetworkRtkConfigInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "NetworkRtkConfigInfo", new DJIValueConverter<RTKCustomNetworkSetting>(RTKCustomNetworkSetting.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<RTKSurveyorPointMsg, EmptyMsg> KeyRTKSurveyorPoint = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RTKSurveyorPoint", new DJIValueConverter<RTKSurveyorPointMsg>(RTKSurveyorPointMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<RTKSurveyorPointInfo> KeyRTKSurveyorPointInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKSurveyorPointInfo", new DJIValueConverter<RTKSurveyorPointInfo>(RTKSurveyorPointInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyRTKSurveyorPointReset = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "RTKSurveyorPointReset", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<RTKGNDLinkStatusMsg> KeyRTKGNDLinkStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RTKGNDLinkStatus", new DJIValueConverter<RTKGNDLinkStatusMsg>(RTKGNDLinkStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<PPPActivateStateMsg> KeyPPPActivateState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PPPActivateState", new DJIValueConverter<PPPActivateStateMsg>(PPPActivateStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyPPPIsValid = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PPPIsValid", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyDeviceID = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DeviceID", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyConnection = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Connection", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyForceUpdateCacheValue = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ForceUpdateCacheValue", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileStatus> KeyCalibrationFileStatus = new DJIKeyInfo<CalibrationFileStatus>(componentType.value(), subComponentType.value(), "CalibrationFileStatus", new SingleValueConverter<CalibrationFileStatus, CalibrationFileStatusMsg>(CalibrationFileStatus.class, CalibrationFileStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileUpdatingInfo> KeyCalibrationFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CalibrationFileUpdatingInfo", new DJIValueConverter<CalibrationFileUpdatingInfo>(CalibrationFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyUpdateCalibrationFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "UpdateCalibrationFile", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<UpgradeNotifyInfo> KeyUpgradeNotifyInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UpgradeNotifyInfo", new DJIValueConverter<UpgradeNotifyInfo>(UpgradeNotifyInfo.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyEnforceUpgradeEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "EnforceUpgradeEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsInEnforceUpgradeStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsInEnforceUpgradeStatus", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsDirectDevice = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsDirectDevice", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CommonFileUpdatingInfo> KeyCommonFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CommonFileUpdatingInfo", new DJIValueConverter<CommonFileUpdatingInfo>(CommonFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyStartCommonFileUpdate = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StartCommonFileUpdate", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopCommonFileUpdate = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopCommonFileUpdate", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticMode = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticMode", new DJIValueConverter<SelfDiagnosticInfo>(SelfDiagnosticInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticRequestInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticRequest = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticRequest", new DJIValueConverter<SelfDiagnosticRequestInfo>(SelfDiagnosticRequestInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode> KeySelfDiagnosticCancel = new DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode>(componentType.value(), subComponentType.value(), "SelfDiagnosticCancel", EmptyValueConverter.converter, new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<SelfDiagnosticProgress> KeySelfDiagnosticStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticStatus", new DJIValueConverter<SelfDiagnosticProgress>(SelfDiagnosticProgress.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticCapability, SelfDiagnosticPartsInfo> KeySelfDiagnosticParts = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticParts", new SingleValueConverter<SelfDiagnosticCapability, SelfDiagnosticCapabilityMsg>(SelfDiagnosticCapability.class, SelfDiagnosticCapabilityMsg.class), new DJIValueConverter<SelfDiagnosticPartsInfo>(SelfDiagnosticPartsInfo.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);

    static {
        keyList.add(KeySerialNumber);
        keyList.add(KeyFirmwareVersion);
        keyList.add(KeyRTKReferenceStationSource);
        keyList.add(KeyRTKBaseStationReferencingPosition);
        keyList.add(KeyRTKBaseStationReferencingPositionReset);
        keyList.add(KeyRTKCustomNetworkSetting);
        keyList.add(KeyRTKDPSNetworkConfig);
        keyList.add(KeyRTKCustomNetworkServiceEnable);
        keyList.add(KeyRTKCalibrationCustomNetworkServiceEnable);
        keyList.add(KeyRTKCustomNetworkServiceState);
        keyList.add(KeyRTKBaseStationBatteryState);
        keyList.add(KeyRTKDongleActivate);
        keyList.add(KeyRTKDongleDeactivate);
        keyList.add(KeyRTKDongleActivateInfo);
        keyList.add(KeyRTKAuthEncrpyt);
        keyList.add(KeyRTKNetworkUserId);
        keyList.add(KeyRTKNetworkBindDevice);
        keyList.add(KeyRTKNetworkRenewOrder);
        keyList.add(KeyRTKNetworkActivateA);
        keyList.add(KeyRTKNetworkActivateB);
        keyList.add(KeyRTKNetworkRequestToUse);
        keyList.add(KeyRTKEncDataRequest);
        keyList.add(KeyRTKBaseStationConnectInfo);
        keyList.add(KeyDPSState);
        keyList.add(KeyRTKBaseStationConnectState);
        keyList.add(KeyRTKBaseStationStartSearch);
        keyList.add(KeyRTKBaseStationLogInAsAdmin);
        keyList.add(KeyRTKBaseStationName);
        keyList.add(KeyRTKRoverDeviceName);
        keyList.add(KeyRTKBaseStationResetPassword);
        keyList.add(KeyRTKBaseStationStopSearch);
        keyList.add(KeyRTKBaseStationList);
        keyList.add(KeyRTKBaseStationConnectAccordingId);
        keyList.add(KeyRTKConnectType);
        keyList.add(KeyRTKSendRtcmToFC);
        keyList.add(KeyRTKBaseStationSNREnable);
        keyList.add(KeyDebugGeneralRTKSNRInfo);
        keyList.add(KeyAnt1GPSSNRData);
        keyList.add(KeyAnt1GNSSSNRData);
        keyList.add(KeyAnt1BDSSNRData);
        keyList.add(KeyAnt1GSNSSNRData);
        keyList.add(KeyAnt2GPSSNRData);
        keyList.add(KeyAnt2GNSSSNRData);
        keyList.add(KeyAnt2BDSSNRData);
        keyList.add(KeyAnt2GSNSSNRData);
        keyList.add(KeyAntBaseStationGPSSNRData);
        keyList.add(KeyAntBaseStationGNSSSNRData);
        keyList.add(KeyAntBaseStationBDSSNRData);
        keyList.add(KeyAntBaseStationGSNSSNRData);
        keyList.add(KeyDroneNestRtkCoordRealtime);
        keyList.add(KeyDroneNestRtkCoordCali);
        keyList.add(KeyDroneNestRtkCoordConfig);
        keyList.add(KeyDroneNestRtkNumSatellite);
        keyList.add(KeyBaseStationConfigVersion);
        keyList.add(KeyDroneNestRtkCalibrationControl);
        keyList.add(KeyRTKCalibrationControl);
        keyList.add(KeyRTKCalibrationReferenceStationSource);
        keyList.add(KeyRTKPPPRealtimeInfo);
        keyList.add(KeyDroneNestRtkReboot);
        keyList.add(KeyDroneNestRtkBaseStationMode);
        keyList.add(KeyDroneNestRtkGNSSSignalLevel);
        keyList.add(KeyRtkAccessInfo);
        keyList.add(KeySharedRtkAccessInfo);
        keyList.add(KeyFreeSharedRtkAccess);
        keyList.add(KeySharedRtkEncDataRequest);
        keyList.add(KeyDroneNestRtkStatisticalResult);
        keyList.add(KeyGetRtkAccessInfoByParam);
        keyList.add(KeyNetworkRtkConfigInfo);
        keyList.add(KeyRTKSurveyorPoint);
        keyList.add(KeyRTKSurveyorPointInfo);
        keyList.add(KeyRTKSurveyorPointReset);
        keyList.add(KeyRTKGNDLinkStatus);
        keyList.add(KeyPPPActivateState);
        keyList.add(KeyPPPIsValid);
        keyList.add(KeyDeviceID);
        keyList.add(KeyConnection);
        keyList.add(KeyForceUpdateCacheValue);
        keyList.add(KeyCalibrationFileStatus);
        keyList.add(KeyCalibrationFileUpdatingInfo);
        keyList.add(KeyUpdateCalibrationFile);
        keyList.add(KeyUpgradeNotifyInfo);
        keyList.add(KeyEnforceUpgradeEnable);
        keyList.add(KeyIsInEnforceUpgradeStatus);
        keyList.add(KeyIsDirectDevice);
        keyList.add(KeyCommonFileUpdatingInfo);
        keyList.add(KeyStartCommonFileUpdate);
        keyList.add(KeyStopCommonFileUpdate);
        keyList.add(KeySelfDiagnosticMode);
        keyList.add(KeySelfDiagnosticRequest);
        keyList.add(KeySelfDiagnosticCancel);
        keyList.add(KeySelfDiagnosticStatus);
        keyList.add(KeySelfDiagnosticParts);
    }
}

