/*
 * Decompiled with CFR 0.152.
 */
package dji.sdk.keyvalue.key;

import dji.sdk.keyvalue.converter.BufferConverter;
import dji.sdk.keyvalue.converter.DJIValueConverter;
import dji.sdk.keyvalue.converter.EmptyValueConverter;
import dji.sdk.keyvalue.converter.SingleValueConverter;
import dji.sdk.keyvalue.key.ComponentType;
import dji.sdk.keyvalue.key.DJIActionKeyInfo;
import dji.sdk.keyvalue.key.DJIKeyInfo;
import dji.sdk.keyvalue.key.SubComponentType;
import dji.sdk.keyvalue.value.battery.BatteryCellVoltages;
import dji.sdk.keyvalue.value.battery.BatteryCollectEvent;
import dji.sdk.keyvalue.value.battery.BatteryCommunicationStatusMsg;
import dji.sdk.keyvalue.value.battery.BatteryCommunicationStatusType;
import dji.sdk.keyvalue.value.battery.BatteryConnectionStateMsg;
import dji.sdk.keyvalue.value.battery.BatteryException;
import dji.sdk.keyvalue.value.battery.BatteryHeatingState;
import dji.sdk.keyvalue.value.battery.BatteryHeatingStateMsg;
import dji.sdk.keyvalue.value.battery.BatteryHwType;
import dji.sdk.keyvalue.value.battery.BatteryHwTypeMsg;
import dji.sdk.keyvalue.value.battery.BatteryLedsInfo;
import dji.sdk.keyvalue.value.battery.BatteryLifeDataInfo;
import dji.sdk.keyvalue.value.battery.BatteryOverviewMsg;
import dji.sdk.keyvalue.value.battery.BatteryOverviewValue;
import dji.sdk.keyvalue.value.battery.BatterySelfDischargeInfo;
import dji.sdk.keyvalue.value.battery.BatteryTemperatureException;
import dji.sdk.keyvalue.value.battery.IndustryBatteryType;
import dji.sdk.keyvalue.value.battery.IndustryBatteryTypeMsg;
import dji.sdk.keyvalue.value.battery.MGBatteryParams;
import dji.sdk.keyvalue.value.battery.MGSOPPowerMsg;
import dji.sdk.keyvalue.value.battery.MooringLineLengthMsg;
import dji.sdk.keyvalue.value.battery.SOPTemperatureLevel;
import dji.sdk.keyvalue.value.battery.SOPTemperatureLevelMsg;
import dji.sdk.keyvalue.value.battery.SmartBatterySocWarning;
import dji.sdk.keyvalue.value.battery.SmartBatterySocWarningMsg;
import dji.sdk.keyvalue.value.camera.DateTime;
import dji.sdk.keyvalue.value.common.CalibrationFileStatus;
import dji.sdk.keyvalue.value.common.CalibrationFileStatusMsg;
import dji.sdk.keyvalue.value.common.CalibrationFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.CommonFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.Date;
import dji.sdk.keyvalue.value.common.EmptyMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapability;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapabilityMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCode;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCodeMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticPartsInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticProgress;
import dji.sdk.keyvalue.value.common.SelfDiagnosticRequestInfo;
import dji.sdk.keyvalue.value.common.UpgradeNotifyInfo;
import dji.sdk.keyvalue.value.flightcontroller.BatteryCollectEventMsg;
import dji.sdk.keyvalue.value.flightcontroller.BatteryVersion2LifeDataInfo;
import java.util.ArrayList;
import java.util.List;

public class DJIBatteryKey {
    protected static final List<DJIKeyInfo<?>> keyList = new ArrayList();
    private static final ComponentType componentType = ComponentType.BATTERY;
    private static final SubComponentType subComponentType = SubComponentType.IGNORE;
    public static final DJIKeyInfo<Integer> KeyFullChargeCapacity = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FullChargeCapacity", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyChargeRemaining = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ChargeRemaining", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyChargeRemainingInPercent = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ChargeRemainingInPercent", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyBatteryIsInvalid = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryIsInvalid", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<DateTime> KeyBatteryProductionDate = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryProductionDate", new DJIValueConverter<DateTime>(DateTime.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyVoltage = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Voltage", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyCurrent = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Current", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyBatteryTemperature = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryTemperature", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyNumberOfDischarges = new DJIKeyInfo(componentType.value(), subComponentType.value(), "NumberOfDischarges", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyNumberOfCells = new DJIKeyInfo(componentType.value(), subComponentType.value(), "NumberOfCells", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyLifetimeRemainingInPercent = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LifetimeRemainingInPercent", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsAnyBatteryDisconnected = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsAnyBatteryDisconnected", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<BatteryTemperatureException> KeyBatteryTemperatureException = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryTemperatureException", new DJIValueConverter<BatteryTemperatureException>(BatteryTemperatureException.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsVoltageDifferenceDetected = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsVoltageDifferenceDetected", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsLowCellVoltageDetected = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsLowCellVoltageDetected", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsCellDamaged = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsCellDamaged", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsFirmwareDifferenceDetected = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsFirmwareDifferenceDetected", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyNumberOfConnectedBatteries = new DJIKeyInfo(componentType.value(), subComponentType.value(), "NumberOfConnectedBatteries", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<BatteryOverviewValue>> KeyBatteryOverviews = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "BatteryOverviews", new SingleValueConverter<List, BatteryOverviewMsg>(List.class, BatteryOverviewMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<BatteryCommunicationStatusType> KeyBatteryCommunicationStatus = new DJIKeyInfo<BatteryCommunicationStatusType>(componentType.value(), subComponentType.value(), "BatteryCommunicationStatus", new SingleValueConverter<BatteryCommunicationStatusType, BatteryCommunicationStatusMsg>(BatteryCommunicationStatusType.class, BatteryCommunicationStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<BatteryHeatingState> KeyHeatingState = new DJIKeyInfo<BatteryHeatingState>(componentType.value(), subComponentType.value(), "HeatingState", new SingleValueConverter<BatteryHeatingState, BatteryHeatingStateMsg>(BatteryHeatingState.class, BatteryHeatingStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Date> KeyBatteryManufacturedDate = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryManufacturedDate", new DJIValueConverter<Date>(Date.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<Integer>> KeyCellVoltages = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "CellVoltages", new SingleValueConverter<List, BatteryCellVoltages>(List.class, BatteryCellVoltages.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyBatteryIsBeingCharged = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryIsBeingCharged", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyBatteryLife = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryLife", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyAccessoryIsBeingCharged = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AccessoryIsBeingCharged", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyAccessoryChargeRemainingInPercent = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AccessoryChargeRemainingInPercent", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeySerialNumber = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SerialNumber", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyFirmwareVersion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FirmwareVersion", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyBatteryMCUFirmwareVersion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryMCUFirmwareVersion", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyBatteryAFEFirmwareVersion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryAFEFirmwareVersion", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<BatteryException> KeyBatteryException = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryException", new DJIValueConverter<BatteryException>(BatteryException.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<BatteryConnectionStateMsg> KeyIsCommunicationException = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsCommunicationException", new DJIValueConverter<BatteryConnectionStateMsg>(BatteryConnectionStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsBatterySOHStateSupport = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsBatterySOHStateSupport", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<BatteryCollectEvent, byte[]> KeyQueryBatteryCollectData = new DJIActionKeyInfo<BatteryCollectEvent, byte[]>(componentType.value(), subComponentType.value(), "QueryBatteryCollectData", new SingleValueConverter<BatteryCollectEvent, BatteryCollectEventMsg>(BatteryCollectEvent.class, BatteryCollectEventMsg.class), BufferConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<BatterySelfDischargeInfo> KeyBatterySelfDischargeInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatterySelfDischargeInfo", new DJIValueConverter<BatterySelfDischargeInfo>(BatterySelfDischargeInfo.class)).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyBatteryBreakCellIndex = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryBreakCellIndex", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<BatteryLifeDataInfo> KeyBatteryLifeData = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryLifeData", new DJIValueConverter<BatteryLifeDataInfo>(BatteryLifeDataInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<BatteryVersion2LifeDataInfo> KeyBatteryVersion2LifeData = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryVersion2LifeData", new DJIValueConverter<BatteryVersion2LifeDataInfo>(BatteryVersion2LifeDataInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<SmartBatterySocWarning> KeySmartBatterySocWarning = new DJIKeyInfo<SmartBatterySocWarning>(componentType.value(), subComponentType.value(), "SmartBatterySocWarning", new SingleValueConverter<SmartBatterySocWarning, SmartBatterySocWarningMsg>(SmartBatterySocWarning.class, SmartBatterySocWarningMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<MGSOPPowerMsg> KeyMGSOPPower = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MGSOPPower", new DJIValueConverter<MGSOPPowerMsg>(MGSOPPowerMsg.class)).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyBatteryIsOutOfDate = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryIsOutOfDate", SingleValueConverter.BooleanConverter).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyBatterySelfDischargeInDays = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatterySelfDischargeInDays", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<BatteryLedsInfo> KeyBatteryLEDsEnabled = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryLEDsEnabled", new DJIValueConverter<BatteryLedsInfo>(BatteryLedsInfo.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsInLoaderState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsInLoaderState", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<BatteryHwType> KeyBatteryHwType = new DJIKeyInfo<BatteryHwType>(componentType.value(), subComponentType.value(), "BatteryHwType", new SingleValueConverter<BatteryHwType, BatteryHwTypeMsg>(BatteryHwType.class, BatteryHwTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<SOPTemperatureLevel> KeySOPTemperatureLevel = new DJIKeyInfo<SOPTemperatureLevel>(componentType.value(), subComponentType.value(), "SOPTemperatureLevel", new SingleValueConverter<SOPTemperatureLevel, SOPTemperatureLevelMsg>(SOPTemperatureLevel.class, SOPTemperatureLevelMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsSelfDischarge = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsSelfDischarge", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<MGBatteryParams> KeyMGBatteryParamsManager = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MGBatteryParamsManager", new DJIValueConverter<MGBatteryParams>(MGBatteryParams.class)).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Long> KeyBatteryHighVoltageStorageTime = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryHighVoltageStorageTime", SingleValueConverter.LongConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("BatteryHighVoltageStorageSec");
    public static final DJIKeyInfo<IndustryBatteryType> KeyIndustryBatteryType = new DJIKeyInfo<IndustryBatteryType>(componentType.value(), subComponentType.value(), "IndustryBatteryType", new SingleValueConverter<IndustryBatteryType, IndustryBatteryTypeMsg>(IndustryBatteryType.class, IndustryBatteryTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<MooringLineLengthMsg> KeyMooringLineLength = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MooringLineLength", new DJIValueConverter<MooringLineLengthMsg>(MooringLineLengthMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyDeviceID = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DeviceID", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyConnection = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Connection", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyForceUpdateCacheValue = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ForceUpdateCacheValue", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileStatus> KeyCalibrationFileStatus = new DJIKeyInfo<CalibrationFileStatus>(componentType.value(), subComponentType.value(), "CalibrationFileStatus", new SingleValueConverter<CalibrationFileStatus, CalibrationFileStatusMsg>(CalibrationFileStatus.class, CalibrationFileStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileUpdatingInfo> KeyCalibrationFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CalibrationFileUpdatingInfo", new DJIValueConverter<CalibrationFileUpdatingInfo>(CalibrationFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyUpdateCalibrationFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "UpdateCalibrationFile", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<UpgradeNotifyInfo> KeyUpgradeNotifyInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UpgradeNotifyInfo", new DJIValueConverter<UpgradeNotifyInfo>(UpgradeNotifyInfo.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyEnforceUpgradeEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "EnforceUpgradeEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsInEnforceUpgradeStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsInEnforceUpgradeStatus", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsDirectDevice = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsDirectDevice", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CommonFileUpdatingInfo> KeyCommonFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CommonFileUpdatingInfo", new DJIValueConverter<CommonFileUpdatingInfo>(CommonFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyStartCommonFileUpdate = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StartCommonFileUpdate", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopCommonFileUpdate = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopCommonFileUpdate", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticMode = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticMode", new DJIValueConverter<SelfDiagnosticInfo>(SelfDiagnosticInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticRequestInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticRequest = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticRequest", new DJIValueConverter<SelfDiagnosticRequestInfo>(SelfDiagnosticRequestInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode> KeySelfDiagnosticCancel = new DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode>(componentType.value(), subComponentType.value(), "SelfDiagnosticCancel", EmptyValueConverter.converter, new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<SelfDiagnosticProgress> KeySelfDiagnosticStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticStatus", new DJIValueConverter<SelfDiagnosticProgress>(SelfDiagnosticProgress.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticCapability, SelfDiagnosticPartsInfo> KeySelfDiagnosticParts = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticParts", new SingleValueConverter<SelfDiagnosticCapability, SelfDiagnosticCapabilityMsg>(SelfDiagnosticCapability.class, SelfDiagnosticCapabilityMsg.class), new DJIValueConverter<SelfDiagnosticPartsInfo>(SelfDiagnosticPartsInfo.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);

    static {
        keyList.add(KeyFullChargeCapacity);
        keyList.add(KeyChargeRemaining);
        keyList.add(KeyChargeRemainingInPercent);
        keyList.add(KeyBatteryIsInvalid);
        keyList.add(KeyBatteryProductionDate);
        keyList.add(KeyVoltage);
        keyList.add(KeyCurrent);
        keyList.add(KeyBatteryTemperature);
        keyList.add(KeyNumberOfDischarges);
        keyList.add(KeyNumberOfCells);
        keyList.add(KeyLifetimeRemainingInPercent);
        keyList.add(KeyIsAnyBatteryDisconnected);
        keyList.add(KeyBatteryTemperatureException);
        keyList.add(KeyIsVoltageDifferenceDetected);
        keyList.add(KeyIsLowCellVoltageDetected);
        keyList.add(KeyIsCellDamaged);
        keyList.add(KeyIsFirmwareDifferenceDetected);
        keyList.add(KeyNumberOfConnectedBatteries);
        keyList.add(KeyBatteryOverviews);
        keyList.add(KeyBatteryCommunicationStatus);
        keyList.add(KeyHeatingState);
        keyList.add(KeyBatteryManufacturedDate);
        keyList.add(KeyCellVoltages);
        keyList.add(KeyBatteryIsBeingCharged);
        keyList.add(KeyBatteryLife);
        keyList.add(KeyAccessoryIsBeingCharged);
        keyList.add(KeyAccessoryChargeRemainingInPercent);
        keyList.add(KeySerialNumber);
        keyList.add(KeyFirmwareVersion);
        keyList.add(KeyBatteryMCUFirmwareVersion);
        keyList.add(KeyBatteryAFEFirmwareVersion);
        keyList.add(KeyBatteryException);
        keyList.add(KeyIsCommunicationException);
        keyList.add(KeyIsBatterySOHStateSupport);
        keyList.add(KeyQueryBatteryCollectData);
        keyList.add(KeyBatterySelfDischargeInfo);
        keyList.add(KeyBatteryBreakCellIndex);
        keyList.add(KeyBatteryLifeData);
        keyList.add(KeyBatteryVersion2LifeData);
        keyList.add(KeySmartBatterySocWarning);
        keyList.add(KeyMGSOPPower);
        keyList.add(KeyBatteryIsOutOfDate);
        keyList.add(KeyBatterySelfDischargeInDays);
        keyList.add(KeyBatteryLEDsEnabled);
        keyList.add(KeyIsInLoaderState);
        keyList.add(KeyBatteryHwType);
        keyList.add(KeySOPTemperatureLevel);
        keyList.add(KeyIsSelfDischarge);
        keyList.add(KeyMGBatteryParamsManager);
        keyList.add(KeyBatteryHighVoltageStorageTime);
        keyList.add(KeyIndustryBatteryType);
        keyList.add(KeyMooringLineLength);
        keyList.add(KeyDeviceID);
        keyList.add(KeyConnection);
        keyList.add(KeyForceUpdateCacheValue);
        keyList.add(KeyCalibrationFileStatus);
        keyList.add(KeyCalibrationFileUpdatingInfo);
        keyList.add(KeyUpdateCalibrationFile);
        keyList.add(KeyUpgradeNotifyInfo);
        keyList.add(KeyEnforceUpgradeEnable);
        keyList.add(KeyIsInEnforceUpgradeStatus);
        keyList.add(KeyIsDirectDevice);
        keyList.add(KeyCommonFileUpdatingInfo);
        keyList.add(KeyStartCommonFileUpdate);
        keyList.add(KeyStopCommonFileUpdate);
        keyList.add(KeySelfDiagnosticMode);
        keyList.add(KeySelfDiagnosticRequest);
        keyList.add(KeySelfDiagnosticCancel);
        keyList.add(KeySelfDiagnosticStatus);
        keyList.add(KeySelfDiagnosticParts);
    }
}

