/*
 * Decompiled with CFR 0.152.
 */
package dji.sdk.keyvalue.key;

import dji.sdk.keyvalue.converter.BufferConverter;
import dji.sdk.keyvalue.converter.DJIValueConverter;
import dji.sdk.keyvalue.converter.EmptyValueConverter;
import dji.sdk.keyvalue.converter.SingleValueConverter;
import dji.sdk.keyvalue.key.ComponentType;
import dji.sdk.keyvalue.key.DJIActionKeyInfo;
import dji.sdk.keyvalue.key.DJIKeyInfo;
import dji.sdk.keyvalue.key.SubComponentType;
import dji.sdk.keyvalue.value.common.Attitude;
import dji.sdk.keyvalue.value.common.CalibrationFileStatus;
import dji.sdk.keyvalue.value.common.CalibrationFileStatusMsg;
import dji.sdk.keyvalue.value.common.CalibrationFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.CommonFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.EmptyMsg;
import dji.sdk.keyvalue.value.common.IntMinMax;
import dji.sdk.keyvalue.value.common.IntPoint2D;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapability;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapabilityMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCode;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCodeMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticPartsInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticProgress;
import dji.sdk.keyvalue.value.common.SelfDiagnosticRequestInfo;
import dji.sdk.keyvalue.value.common.StringListMsg;
import dji.sdk.keyvalue.value.common.UpgradeNotifyInfo;
import dji.sdk.keyvalue.value.gimbal.CalibrationDataExistInfoMsg;
import dji.sdk.keyvalue.value.gimbal.CameraPortraitStateMsg;
import dji.sdk.keyvalue.value.gimbal.FineTunePostureMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalActionButtonExecutionMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalActionButtonExecutionType;
import dji.sdk.keyvalue.value.gimbal.GimbalAngleRotation;
import dji.sdk.keyvalue.value.gimbal.GimbalAttitudeQuaternionInfo;
import dji.sdk.keyvalue.value.gimbal.GimbalAttitudeRange;
import dji.sdk.keyvalue.value.gimbal.GimbalBalanceDetectionState;
import dji.sdk.keyvalue.value.gimbal.GimbalButtonExecutionMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalButtonExecutionType;
import dji.sdk.keyvalue.value.gimbal.GimbalCalibrationStatusInfo;
import dji.sdk.keyvalue.value.gimbal.GimbalCmdIdsMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalCoaxialityDetectionState;
import dji.sdk.keyvalue.value.gimbal.GimbalComponentType;
import dji.sdk.keyvalue.value.gimbal.GimbalComponentTypeMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalControlParametersAutoTuningState;
import dji.sdk.keyvalue.value.gimbal.GimbalCurrentAttitudeMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalCustomPathSettings;
import dji.sdk.keyvalue.value.gimbal.GimbalExceptionFlags;
import dji.sdk.keyvalue.value.gimbal.GimbalFeatureStateInfo;
import dji.sdk.keyvalue.value.gimbal.GimbalFollowSettings;
import dji.sdk.keyvalue.value.gimbal.GimbalFollowingSpeed;
import dji.sdk.keyvalue.value.gimbal.GimbalFollowingSpeedMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalHandHeldDirectionMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalHandHeldDirectionType;
import dji.sdk.keyvalue.value.gimbal.GimbalInstallDirection;
import dji.sdk.keyvalue.value.gimbal.GimbalInstallDirectionMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalJoystickControlSpeedMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalJoystickSettings;
import dji.sdk.keyvalue.value.gimbal.GimbalLimitationState;
import dji.sdk.keyvalue.value.gimbal.GimbalMode;
import dji.sdk.keyvalue.value.gimbal.GimbalModeMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalMotionControlReq;
import dji.sdk.keyvalue.value.gimbal.GimbalMotionSettingMode;
import dji.sdk.keyvalue.value.gimbal.GimbalMotionSettingModeMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalPanoSettings;
import dji.sdk.keyvalue.value.gimbal.GimbalPathMissionExecutionSettings;
import dji.sdk.keyvalue.value.gimbal.GimbalPathMissionProgress;
import dji.sdk.keyvalue.value.gimbal.GimbalPathMissionStateSubscribeMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalPathMissionType;
import dji.sdk.keyvalue.value.gimbal.GimbalPathMissionTypeMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalPinInfo;
import dji.sdk.keyvalue.value.gimbal.GimbalRecenterProgress;
import dji.sdk.keyvalue.value.gimbal.GimbalRecenterProgressMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalResetCommandMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalResetType;
import dji.sdk.keyvalue.value.gimbal.GimbalRollMode;
import dji.sdk.keyvalue.value.gimbal.GimbalRollModeMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalSceneMode;
import dji.sdk.keyvalue.value.gimbal.GimbalSceneModeMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalSelfCheckFlags;
import dji.sdk.keyvalue.value.gimbal.GimbalSpeedRotation;
import dji.sdk.keyvalue.value.gimbal.GimbalTLVsMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalTimeLapseProgressMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalTimeLapseSettings;
import dji.sdk.keyvalue.value.gimbal.GimbalTrimValueMsg;
import dji.sdk.keyvalue.value.gimbal.GimbalZoomActionState;
import dji.sdk.keyvalue.value.gimbal.GimbalZoomActionStateMsg;
import dji.sdk.keyvalue.value.gimbal.HandheldStickHorizontalDirection;
import dji.sdk.keyvalue.value.gimbal.HandheldStickHorizontalDirectionMsg;
import dji.sdk.keyvalue.value.gimbal.HandheldStickVerticalDirection;
import dji.sdk.keyvalue.value.gimbal.HandheldStickVerticalDirectionMsg;
import dji.sdk.keyvalue.value.gimbal.JoystickControlMode;
import dji.sdk.keyvalue.value.gimbal.JoystickControlModeMsg;
import dji.sdk.keyvalue.value.gimbal.ManualCalibrateGimbalParam;
import dji.sdk.keyvalue.value.gimbal.PostureFineTuneResult;
import dji.sdk.keyvalue.value.gimbal.PostureFineTuneResultMsg;
import dji.sdk.keyvalue.value.gimbal.QuaternionMeasInfo;
import dji.sdk.keyvalue.value.gimbal.SmartTrackingSpeed;
import dji.sdk.keyvalue.value.gimbal.SmartTrackingSpeedMsg;
import dji.sdk.keyvalue.value.gimbal.TypeLengthValue;
import dji.sdk.keyvalue.value.gimbal.WheelControlInfo;
import java.util.ArrayList;
import java.util.List;

public class DJIGimbalKey {
    protected static final List<DJIKeyInfo<?>> keyList = new ArrayList();
    private static final ComponentType componentType = ComponentType.GIMBAL;
    private static final SubComponentType subComponentType = SubComponentType.IGNORE;
    public static final DJIKeyInfo<GimbalLimitationState> KeyLimitationState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LimitationState", new DJIValueConverter<GimbalLimitationState>(GimbalLimitationState.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<GimbalResetType, EmptyMsg> KeyGimbalReset = new DJIActionKeyInfo<GimbalResetType, EmptyMsg>(componentType.value(), subComponentType.value(), "GimbalReset", new SingleValueConverter<GimbalResetType, GimbalResetCommandMsg>(GimbalResetType.class, GimbalResetCommandMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false).setInnerIdentifier("ResetGimbal");
    public static final DJIKeyInfo<GimbalMode> KeyGimbalCMode = new DJIKeyInfo<GimbalMode>(componentType.value(), subComponentType.value(), "GimbalCMode", new SingleValueConverter<GimbalMode, GimbalModeMsg>(GimbalMode.class, GimbalModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("GimbalMode");
    public static final DJIKeyInfo<Attitude> KeyGimbalAttitude = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GimbalAttitude", new DJIValueConverter<Attitude>(Attitude.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyYawRelativeToAircraftHeading = new DJIKeyInfo(componentType.value(), subComponentType.value(), "YawRelativeToAircraftHeading", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("YawRelativeToBodyHeading");
    public static final DJIKeyInfo<Attitude> KeyGimbalJointAttitude = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GimbalJointAttitude", new DJIValueConverter<Attitude>(Attitude.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<GimbalAngleRotation, EmptyMsg> KeyRotateByAngle = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RotateByAngle", new DJIValueConverter<GimbalAngleRotation>(GimbalAngleRotation.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<GimbalSpeedRotation, EmptyMsg> KeyRotateBySpeed = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RotateBySpeed", new DJIValueConverter<GimbalSpeedRotation>(GimbalSpeedRotation.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<ManualCalibrateGimbalParam, EmptyMsg> KeyManualCalibrateGimbal = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ManualCalibrateGimbal", new DJIValueConverter<ManualCalibrateGimbalParam>(ManualCalibrateGimbalParam.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyGimbalCalibrate = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "GimbalCalibrate", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false).setInnerIdentifier("CalibrateGimbal");
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyRestoreFactorySettings = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "RestoreFactorySettings", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<List<Integer>, List<TypeLengthValue>> KeyReadParams = new DJIActionKeyInfo<List, List>(componentType.value(), subComponentType.value(), "ReadParams", new SingleValueConverter<List, GimbalCmdIdsMsg>(List.class, GimbalCmdIdsMsg.class), new SingleValueConverter<List, GimbalTLVsMsg>(List.class, GimbalTLVsMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<GimbalMotionControlReq, GimbalCurrentAttitudeMsg> KeyMotionControl = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "MotionControl", new DJIValueConverter<GimbalMotionControlReq>(GimbalMotionControlReq.class), new DJIValueConverter<GimbalCurrentAttitudeMsg>(GimbalCurrentAttitudeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<GimbalCurrentAttitudeMsg> KeyGimbalCurrentAttitude = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GimbalCurrentAttitude", new DJIValueConverter<GimbalCurrentAttitudeMsg>(GimbalCurrentAttitudeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalTrimValueMsg> KeyGimbalTrimValue = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GimbalTrimValue", new DJIValueConverter<GimbalTrimValueMsg>(GimbalTrimValueMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalSceneMode> KeyGimbalSceneMode = new DJIKeyInfo<GimbalSceneMode>(componentType.value(), subComponentType.value(), "GimbalSceneMode", new SingleValueConverter<GimbalSceneMode, GimbalSceneModeMsg>(GimbalSceneMode.class, GimbalSceneModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<FineTunePostureMsg, PostureFineTuneResult> KeyFineTunePosture = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "FineTunePosture", new DJIValueConverter<FineTunePostureMsg>(FineTunePostureMsg.class), new SingleValueConverter<PostureFineTuneResult, PostureFineTuneResultMsg>(PostureFineTuneResult.class, PostureFineTuneResultMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<Double, EmptyMsg> KeyFineTuneFPVRollInDegrees = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "FineTuneFPVRollInDegrees", SingleValueConverter.DoubleConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<Double, EmptyMsg> KeyFineTunePitchInDegrees = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "FineTunePitchInDegrees", SingleValueConverter.DoubleConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<Double, EmptyMsg> KeyFineTuneYawInDegrees = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "FineTuneYawInDegrees", SingleValueConverter.DoubleConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<GimbalMotionSettingMode> KeyMotionSettingMode = new DJIKeyInfo<GimbalMotionSettingMode>(componentType.value(), subComponentType.value(), "MotionSettingMode", new SingleValueConverter<GimbalMotionSettingMode, GimbalMotionSettingModeMsg>(GimbalMotionSettingMode.class, GimbalMotionSettingModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyGimbalSettingProfileIndex = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GimbalSettingProfileIndex", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalAttitudeRange> KeyGimbalAttitudeRange = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GimbalAttitudeRange", new DJIValueConverter<GimbalAttitudeRange>(GimbalAttitudeRange.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalCalibrationStatusInfo> KeyGimbalCalibrationStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GimbalCalibrationStatus", new DJIValueConverter<GimbalCalibrationStatusInfo>(GimbalCalibrationStatusInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("GimbalCalibrationState");
    public static final DJIKeyInfo<GimbalHandHeldDirectionType> KeyGimbalHandHeldDirection = new DJIKeyInfo<GimbalHandHeldDirectionType>(componentType.value(), subComponentType.value(), "GimbalHandHeldDirection", new SingleValueConverter<GimbalHandHeldDirectionType, GimbalHandHeldDirectionMsg>(GimbalHandHeldDirectionType.class, GimbalHandHeldDirectionMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsInFlashlightMode = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsInFlashlightMode", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyTurnOnGimbal = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "TurnOnGimbal", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyTurnOffGimbal = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "TurnOffGimbal", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyDormantGimbal = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "DormantGimbal", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsInSelfieMode = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsInSelfieMode", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CameraPortraitStateMsg> KeyCameraPortraitState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CameraPortraitState", new DJIValueConverter<CameraPortraitStateMsg>(CameraPortraitStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalRecenterProgress> KeyRecenterProgress = new DJIKeyInfo<GimbalRecenterProgress>(componentType.value(), subComponentType.value(), "RecenterProgress", new SingleValueConverter<GimbalRecenterProgress, GimbalRecenterProgressMsg>(GimbalRecenterProgress.class, GimbalRecenterProgressMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationDataExistInfoMsg> KeyDebugOnlyCalibrationDataExistInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DebugOnlyCalibrationDataExistInfo", new DJIValueConverter<CalibrationDataExistInfoMsg>(CalibrationDataExistInfoMsg.class)).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalInstallDirection> KeyGimbalInstallDirection = new DJIKeyInfo<GimbalInstallDirection>(componentType.value(), subComponentType.value(), "GimbalInstallDirection", new SingleValueConverter<GimbalInstallDirection, GimbalInstallDirectionMsg>(GimbalInstallDirection.class, GimbalInstallDirectionMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalJoystickControlSpeedMsg> KeyJoystickControlSpeed = new DJIKeyInfo(componentType.value(), subComponentType.value(), "JoystickControlSpeed", new DJIValueConverter<GimbalJoystickControlSpeedMsg>(GimbalJoystickControlSpeedMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalTimeLapseProgressMsg> KeyGimbalTimeLapseProgress = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GimbalTimeLapseProgress", new DJIValueConverter<GimbalTimeLapseProgressMsg>(GimbalTimeLapseProgressMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<GimbalTimeLapseSettings, EmptyMsg> KeyStartGimbalTimeLapse = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StartGimbalTimeLapse", new DJIValueConverter<GimbalTimeLapseSettings>(GimbalTimeLapseSettings.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopGimbalTimeLapse = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopGimbalTimeLapse", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<GimbalZoomActionState> KeyGimbalZoomActionState = new DJIKeyInfo<GimbalZoomActionState>(componentType.value(), subComponentType.value(), "GimbalZoomActionState", new SingleValueConverter<GimbalZoomActionState, GimbalZoomActionStateMsg>(GimbalZoomActionState.class, GimbalZoomActionStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalActionButtonExecutionType> KeyGimbalActionButtonExecution = new DJIKeyInfo<GimbalActionButtonExecutionType>(componentType.value(), subComponentType.value(), "GimbalActionButtonExecution", new SingleValueConverter<GimbalActionButtonExecutionType, GimbalActionButtonExecutionMsg>(GimbalActionButtonExecutionType.class, GimbalActionButtonExecutionMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<String> KeySerialNumber = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SerialNumber", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyFirmwareVersion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FirmwareVersion", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyAxisLockSwitch = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AxisLockSwitch", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyGimbalVerticalShotEnabled = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GimbalVerticalShotEnabled", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsHorizontalVerticalShotSwitching = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsHorizontalVerticalShotSwitching", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalPathMissionProgress> KeyGimbalPathMissionProgress = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GimbalPathMissionProgress", new DJIValueConverter<GimbalPathMissionProgress>(GimbalPathMissionProgress.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<GimbalPathMissionStateSubscribeMsg, EmptyMsg> KeySubscribeGimbalPathMissionState = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SubscribeGimbalPathMissionState", new DJIValueConverter<GimbalPathMissionStateSubscribeMsg>(GimbalPathMissionStateSubscribeMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<JoystickControlMode> KeyJoystickControlMode = new DJIKeyInfo<JoystickControlMode>(componentType.value(), subComponentType.value(), "JoystickControlMode", new SingleValueConverter<JoystickControlMode, JoystickControlModeMsg>(JoystickControlMode.class, JoystickControlModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyUnsubscribeGimbalPathMissionState = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "UnsubscribeGimbalPathMissionState", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<GimbalCustomPathSettings, EmptyMsg> KeyStartGimbalCustomPathMission = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StartGimbalCustomPathMission", new DJIValueConverter<GimbalCustomPathSettings>(GimbalCustomPathSettings.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<GimbalFollowingSpeed> KeyGimbalFollowSpeed = new DJIKeyInfo<GimbalFollowingSpeed>(componentType.value(), subComponentType.value(), "GimbalFollowSpeed", new SingleValueConverter<GimbalFollowingSpeed, GimbalFollowingSpeedMsg>(GimbalFollowingSpeed.class, GimbalFollowingSpeedMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyJoystickYawInverted = new DJIKeyInfo(componentType.value(), subComponentType.value(), "JoystickYawInverted", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<GimbalPathMissionType, EmptyMsg> KeyStopGimbalPathMission = new DJIActionKeyInfo<GimbalPathMissionType, EmptyMsg>(componentType.value(), subComponentType.value(), "StopGimbalPathMission", new SingleValueConverter<GimbalPathMissionType, GimbalPathMissionTypeMsg>(GimbalPathMissionType.class, GimbalPathMissionTypeMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyJoystickPitchInverted = new DJIKeyInfo(componentType.value(), subComponentType.value(), "JoystickPitchInverted", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<GimbalPathMissionExecutionSettings, EmptyMsg> KeyContinueGimbalPathMission = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ContinueGimbalPathMission", new DJIValueConverter<GimbalPathMissionExecutionSettings>(GimbalPathMissionExecutionSettings.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsPitchLocked = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsPitchLocked", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<GimbalPanoSettings, EmptyMsg> KeyStartGimbalPanoMission = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StartGimbalPanoMission", new DJIValueConverter<GimbalPanoSettings>(GimbalPanoSettings.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyWaterProofModeEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WaterProofModeEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyFineTuneRollTotalDegree = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FineTuneRollTotalDegree", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RollAdjustDegree");
    public static final DJIKeyInfo<GimbalExceptionFlags> KeyGimbalException = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GimbalException", new DJIValueConverter<GimbalExceptionFlags>(GimbalExceptionFlags.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalSelfCheckFlags> KeyGimbalSelfCheckInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GimbalSelfCheckInfo", new DJIValueConverter<GimbalSelfCheckFlags>(GimbalSelfCheckFlags.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalFollowSettings> KeyGimbalFollowSettings = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GimbalFollowSettings", new DJIValueConverter<GimbalFollowSettings>(GimbalFollowSettings.class)).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalJoystickSettings> KeyGimbalJoystickSettings = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GimbalJoystickSettings", new DJIValueConverter<GimbalJoystickSettings>(GimbalJoystickSettings.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalRollMode> KeyGimbalRollMode = new DJIKeyInfo<GimbalRollMode>(componentType.value(), subComponentType.value(), "GimbalRollMode", new SingleValueConverter<GimbalRollMode, GimbalRollModeMsg>(GimbalRollMode.class, GimbalRollModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<HandheldStickVerticalDirection> KeyHandheldStickVerticalDirection = new DJIKeyInfo<HandheldStickVerticalDirection>(componentType.value(), subComponentType.value(), "HandheldStickVerticalDirection", new SingleValueConverter<HandheldStickVerticalDirection, HandheldStickVerticalDirectionMsg>(HandheldStickVerticalDirection.class, HandheldStickVerticalDirectionMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<HandheldStickHorizontalDirection> KeyHandheldStickHorizontalDirection = new DJIKeyInfo<HandheldStickHorizontalDirection>(componentType.value(), subComponentType.value(), "HandheldStickHorizontalDirection", new SingleValueConverter<HandheldStickHorizontalDirection, HandheldStickHorizontalDirectionMsg>(HandheldStickHorizontalDirection.class, HandheldStickHorizontalDirectionMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyHasAugmentedLens = new DJIKeyInfo(componentType.value(), subComponentType.value(), "HasAugmentedLens", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyFineTunePitchTotalDegree = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FineTunePitchTotalDegree", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("PitchAdjustDegree");
    public static final DJIKeyInfo<Double> KeyFineTuneYawTotalDegree = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FineTuneYawTotalDegree", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("YawAdjustDegree");
    public static final DJIKeyInfo<IntPoint2D> KeyHandheldStickPosition = new DJIKeyInfo(componentType.value(), subComponentType.value(), "HandheldStickPosition", new DJIValueConverter<IntPoint2D>(IntPoint2D.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<Integer, EmptyMsg> KeyRollCoordinateSystemRotate = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RollCoordinateSystemRotate", SingleValueConverter.IntegerConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<GimbalFeatureStateInfo, EmptyMsg> KeyAcquireGimbalFeatureControl = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "AcquireGimbalFeatureControl", new DJIValueConverter<GimbalFeatureStateInfo>(GimbalFeatureStateInfo.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyReleaseGimbalFeatureControl = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "ReleaseGimbalFeatureControl", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyOM3GimbalSpecialMode = new DJIKeyInfo(componentType.value(), subComponentType.value(), "OM3GimbalSpecialMode", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyDemoFunctionSwitch = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DemoFunctionSwitch", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<Double, EmptyMsg> KeyFineTuneRollInDegrees = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "FineTuneRollInDegrees", SingleValueConverter.DoubleConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyPitchRangeExtensionEnabled = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PitchRangeExtensionEnabled", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyYawSmoothingFactor = new DJIKeyInfo(componentType.value(), subComponentType.value(), "YawSmoothingFactor", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalAttitudeQuaternionInfo> KeyGimbalAttitudeQuaternion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GimbalAttitudeQuaternion", new DJIValueConverter<GimbalAttitudeQuaternionInfo>(GimbalAttitudeQuaternionInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyPitchSmoothingFactor = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PitchSmoothingFactor", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyCheckPhoneOffset = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CheckPhoneOffset", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<IntMinMax> KeyPitchSmoothingFactorRange = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PitchSmoothingFactorRange", new DJIValueConverter<IntMinMax>(IntMinMax.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<IntMinMax> KeyYawSmoothingFactorRange = new DJIKeyInfo(componentType.value(), subComponentType.value(), "YawSmoothingFactorRange", new DJIValueConverter<IntMinMax>(IntMinMax.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<IntMinMax> KeyPitchMaxSpeedRange = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PitchMaxSpeedRange", new DJIValueConverter<IntMinMax>(IntMinMax.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyPitchMaxSpeed = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PitchMaxSpeed", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyPitchSmoothingFactorOnTripodState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PitchSmoothingFactorOnTripodState", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<IntMinMax> KeyPitchSmoothingFactorOnTripodStateRange = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PitchSmoothingFactorOnTripodStateRange", new DJIValueConverter<IntMinMax>(IntMinMax.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyPitchSmoothingFactorOnSportState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PitchSmoothingFactorOnSportState", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<IntMinMax> KeyPitchSmoothingFactorOnSportStateRange = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PitchSmoothingFactorOnSportStateRange", new DJIValueConverter<IntMinMax>(IntMinMax.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyYawControlMaxSpeed = new DJIKeyInfo(componentType.value(), subComponentType.value(), "YawControlMaxSpeed", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("YawControllerMaxSpeed");
    public static final DJIKeyInfo<Integer> KeyPitchControlMaxSpeed = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PitchControlMaxSpeed", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("PitchControllerMaxSpeed");
    public static final DJIKeyInfo<Integer> KeyPitchMaxSpeedOnTripodState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PitchMaxSpeedOnTripodState", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<IntMinMax> KeyPitchMaxSpeedOnTripodStateRange = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PitchMaxSpeedOnTripodStateRange", new DJIValueConverter<IntMinMax>(IntMinMax.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyPitchMaxSpeedOnSportState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PitchMaxSpeedOnSportState", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<IntMinMax> KeyPitchMaxSpeedOnSportStateRange = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PitchMaxSpeedOnSportStateRange", new DJIValueConverter<IntMinMax>(IntMinMax.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyRollControllerMaxSpeed = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RollControllerMaxSpeed", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyRollSmoothingFactor = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RollSmoothingFactor", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<EmptyMsg> KeyResetGimbalEvent = new DJIKeyInfo<EmptyMsg>(componentType.value(), subComponentType.value(), "ResetGimbalEvent", EmptyValueConverter.converter).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<Boolean> KeyYawAdjustSupported = new DJIKeyInfo(componentType.value(), subComponentType.value(), "YawAdjustSupported", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyYawEulerDeviation = new DJIKeyInfo(componentType.value(), subComponentType.value(), "YawEulerDeviation", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyLimitationEnabled = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LimitationEnabled", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalButtonExecutionType> KeyGimbalTriggerButtonExecutionEvent = new DJIKeyInfo<GimbalButtonExecutionType>(componentType.value(), subComponentType.value(), "GimbalTriggerButtonExecutionEvent", new SingleValueConverter<GimbalButtonExecutionType, GimbalButtonExecutionMsg>(GimbalButtonExecutionType.class, GimbalButtonExecutionMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalButtonExecutionType> KeyGimbalFunctionButtonExecutionEvent = new DJIKeyInfo<GimbalButtonExecutionType>(componentType.value(), subComponentType.value(), "GimbalFunctionButtonExecutionEvent", new SingleValueConverter<GimbalButtonExecutionType, GimbalButtonExecutionMsg>(GimbalButtonExecutionType.class, GimbalButtonExecutionMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalButtonExecutionType> KeyGimbalZoomTelephotoButtonExecutionEvent = new DJIKeyInfo<GimbalButtonExecutionType>(componentType.value(), subComponentType.value(), "GimbalZoomTelephotoButtonExecutionEvent", new SingleValueConverter<GimbalButtonExecutionType, GimbalButtonExecutionMsg>(GimbalButtonExecutionType.class, GimbalButtonExecutionMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalButtonExecutionType> KeyGimbalZoomWideButtonExecutionEvent = new DJIKeyInfo<GimbalButtonExecutionType>(componentType.value(), subComponentType.value(), "GimbalZoomWideButtonExecutionEvent", new SingleValueConverter<GimbalButtonExecutionType, GimbalButtonExecutionMsg>(GimbalButtonExecutionType.class, GimbalButtonExecutionMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyStickGimbalControlEnabled = new DJIKeyInfo(componentType.value(), subComponentType.value(), "StickGimbalControlEnabled", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalButtonExecutionType> KeyGimbalSideButtonExecutionEvent = new DJIKeyInfo<GimbalButtonExecutionType>(componentType.value(), subComponentType.value(), "GimbalSideButtonExecutionEvent", new SingleValueConverter<GimbalButtonExecutionType, GimbalButtonExecutionMsg>(GimbalButtonExecutionType.class, GimbalButtonExecutionMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<byte[], EmptyMsg> KeyRotateByMLVotInfo = new DJIActionKeyInfo<byte[], EmptyMsg>(componentType.value(), subComponentType.value(), "RotateByMLVotInfo", BufferConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyStepFrequency = new DJIKeyInfo(componentType.value(), subComponentType.value(), "StepFrequency", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyTiltAngle = new DJIKeyInfo(componentType.value(), subComponentType.value(), "TiltAngle", SingleValueConverter.DoubleConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<SmartTrackingSpeed> KeySmartTrackingSpeed = new DJIKeyInfo<SmartTrackingSpeed>(componentType.value(), subComponentType.value(), "SmartTrackingSpeed", new SingleValueConverter<SmartTrackingSpeed, SmartTrackingSpeedMsg>(SmartTrackingSpeed.class, SmartTrackingSpeedMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyYawMotorControlStiffness = new DJIKeyInfo(componentType.value(), subComponentType.value(), "YawMotorControlStiffness", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyPitchMotorControlStiffness = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PitchMotorControlStiffness", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyRollMotorControlStiffness = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RollMotorControlStiffness", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyResetControlParameters = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "ResetControlParameters", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStartControlParametersAutoTuning = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StartControlParametersAutoTuning", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopControlParametersAutoTuning = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopControlParametersAutoTuning", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<GimbalControlParametersAutoTuningState> KeyStiffnessSelfTuningResult = new DJIKeyInfo(componentType.value(), subComponentType.value(), "StiffnessSelfTuningResult", new DJIValueConverter<GimbalControlParametersAutoTuningState>(GimbalControlParametersAutoTuningState.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStartBalanceDetection = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StartBalanceDetection", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopBalanceDetection = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopBalanceDetection", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<GimbalBalanceDetectionState> KeyBalanceCheckResult = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BalanceCheckResult", new DJIValueConverter<GimbalBalanceDetectionState>(GimbalBalanceDetectionState.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStartConcentricityDetection = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StartConcentricityDetection", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopConcentricityDetection = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopConcentricityDetection", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<GimbalCoaxialityDetectionState> KeyConcentricityCheckResult = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ConcentricityCheckResult", new DJIValueConverter<GimbalCoaxialityDetectionState>(GimbalCoaxialityDetectionState.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<Double>> KeyQuaternionMeas = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "QuaternionMeas", new SingleValueConverter<List, QuaternionMeasInfo>(List.class, QuaternionMeasInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalComponentType> KeyGimbalComponentType = new DJIKeyInfo<GimbalComponentType>(componentType.value(), subComponentType.value(), "GimbalComponentType", new SingleValueConverter<GimbalComponentType, GimbalComponentTypeMsg>(GimbalComponentType.class, GimbalComponentTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<WheelControlInfo> KeyWheelControlEvent = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WheelControlEvent", new DJIValueConverter<WheelControlInfo>(WheelControlInfo.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsTripodModeOn = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsTripodModeOn", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalButtonExecutionType> KeyGimbalWheelButtonExecutionEvent = new DJIKeyInfo<GimbalButtonExecutionType>(componentType.value(), subComponentType.value(), "GimbalWheelButtonExecutionEvent", new SingleValueConverter<GimbalButtonExecutionType, GimbalButtonExecutionMsg>(GimbalButtonExecutionType.class, GimbalButtonExecutionMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyMachineLearningRollControlEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MachineLearningRollControlEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<List<String>, EmptyMsg> KeyResetParameters = new DJIActionKeyInfo<List, EmptyMsg>(componentType.value(), subComponentType.value(), "ResetParameters", new SingleValueConverter<List, StringListMsg>(List.class, StringListMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsInFFGMode = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsInFFGMode", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<GimbalPinInfo> KeyGimbalPinInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GimbalPinInfo", new DJIValueConverter<GimbalPinInfo>(GimbalPinInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyDeviceID = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DeviceID", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyConnection = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Connection", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyForceUpdateCacheValue = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ForceUpdateCacheValue", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileStatus> KeyCalibrationFileStatus = new DJIKeyInfo<CalibrationFileStatus>(componentType.value(), subComponentType.value(), "CalibrationFileStatus", new SingleValueConverter<CalibrationFileStatus, CalibrationFileStatusMsg>(CalibrationFileStatus.class, CalibrationFileStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileUpdatingInfo> KeyCalibrationFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CalibrationFileUpdatingInfo", new DJIValueConverter<CalibrationFileUpdatingInfo>(CalibrationFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyUpdateCalibrationFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "UpdateCalibrationFile", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<UpgradeNotifyInfo> KeyUpgradeNotifyInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UpgradeNotifyInfo", new DJIValueConverter<UpgradeNotifyInfo>(UpgradeNotifyInfo.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyEnforceUpgradeEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "EnforceUpgradeEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsInEnforceUpgradeStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsInEnforceUpgradeStatus", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsDirectDevice = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsDirectDevice", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CommonFileUpdatingInfo> KeyCommonFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CommonFileUpdatingInfo", new DJIValueConverter<CommonFileUpdatingInfo>(CommonFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyStartCommonFileUpdate = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StartCommonFileUpdate", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopCommonFileUpdate = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopCommonFileUpdate", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticMode = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticMode", new DJIValueConverter<SelfDiagnosticInfo>(SelfDiagnosticInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticRequestInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticRequest = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticRequest", new DJIValueConverter<SelfDiagnosticRequestInfo>(SelfDiagnosticRequestInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode> KeySelfDiagnosticCancel = new DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode>(componentType.value(), subComponentType.value(), "SelfDiagnosticCancel", EmptyValueConverter.converter, new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<SelfDiagnosticProgress> KeySelfDiagnosticStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticStatus", new DJIValueConverter<SelfDiagnosticProgress>(SelfDiagnosticProgress.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticCapability, SelfDiagnosticPartsInfo> KeySelfDiagnosticParts = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticParts", new SingleValueConverter<SelfDiagnosticCapability, SelfDiagnosticCapabilityMsg>(SelfDiagnosticCapability.class, SelfDiagnosticCapabilityMsg.class), new DJIValueConverter<SelfDiagnosticPartsInfo>(SelfDiagnosticPartsInfo.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);

    static {
        keyList.add(KeyLimitationState);
        keyList.add(KeyGimbalReset);
        keyList.add(KeyGimbalCMode);
        keyList.add(KeyGimbalAttitude);
        keyList.add(KeyYawRelativeToAircraftHeading);
        keyList.add(KeyGimbalJointAttitude);
        keyList.add(KeyRotateByAngle);
        keyList.add(KeyRotateBySpeed);
        keyList.add(KeyManualCalibrateGimbal);
        keyList.add(KeyGimbalCalibrate);
        keyList.add(KeyRestoreFactorySettings);
        keyList.add(KeyReadParams);
        keyList.add(KeyMotionControl);
        keyList.add(KeyGimbalCurrentAttitude);
        keyList.add(KeyGimbalTrimValue);
        keyList.add(KeyGimbalSceneMode);
        keyList.add(KeyFineTunePosture);
        keyList.add(KeyFineTuneFPVRollInDegrees);
        keyList.add(KeyFineTunePitchInDegrees);
        keyList.add(KeyFineTuneYawInDegrees);
        keyList.add(KeyMotionSettingMode);
        keyList.add(KeyGimbalSettingProfileIndex);
        keyList.add(KeyGimbalAttitudeRange);
        keyList.add(KeyGimbalCalibrationStatus);
        keyList.add(KeyGimbalHandHeldDirection);
        keyList.add(KeyIsInFlashlightMode);
        keyList.add(KeyTurnOnGimbal);
        keyList.add(KeyTurnOffGimbal);
        keyList.add(KeyDormantGimbal);
        keyList.add(KeyIsInSelfieMode);
        keyList.add(KeyCameraPortraitState);
        keyList.add(KeyRecenterProgress);
        keyList.add(KeyDebugOnlyCalibrationDataExistInfo);
        keyList.add(KeyGimbalInstallDirection);
        keyList.add(KeyJoystickControlSpeed);
        keyList.add(KeyGimbalTimeLapseProgress);
        keyList.add(KeyStartGimbalTimeLapse);
        keyList.add(KeyStopGimbalTimeLapse);
        keyList.add(KeyGimbalZoomActionState);
        keyList.add(KeyGimbalActionButtonExecution);
        keyList.add(KeySerialNumber);
        keyList.add(KeyFirmwareVersion);
        keyList.add(KeyAxisLockSwitch);
        keyList.add(KeyGimbalVerticalShotEnabled);
        keyList.add(KeyIsHorizontalVerticalShotSwitching);
        keyList.add(KeyGimbalPathMissionProgress);
        keyList.add(KeySubscribeGimbalPathMissionState);
        keyList.add(KeyJoystickControlMode);
        keyList.add(KeyUnsubscribeGimbalPathMissionState);
        keyList.add(KeyStartGimbalCustomPathMission);
        keyList.add(KeyGimbalFollowSpeed);
        keyList.add(KeyJoystickYawInverted);
        keyList.add(KeyStopGimbalPathMission);
        keyList.add(KeyJoystickPitchInverted);
        keyList.add(KeyContinueGimbalPathMission);
        keyList.add(KeyIsPitchLocked);
        keyList.add(KeyStartGimbalPanoMission);
        keyList.add(KeyWaterProofModeEnable);
        keyList.add(KeyFineTuneRollTotalDegree);
        keyList.add(KeyGimbalException);
        keyList.add(KeyGimbalSelfCheckInfo);
        keyList.add(KeyGimbalFollowSettings);
        keyList.add(KeyGimbalJoystickSettings);
        keyList.add(KeyGimbalRollMode);
        keyList.add(KeyHandheldStickVerticalDirection);
        keyList.add(KeyHandheldStickHorizontalDirection);
        keyList.add(KeyHasAugmentedLens);
        keyList.add(KeyFineTunePitchTotalDegree);
        keyList.add(KeyFineTuneYawTotalDegree);
        keyList.add(KeyHandheldStickPosition);
        keyList.add(KeyRollCoordinateSystemRotate);
        keyList.add(KeyAcquireGimbalFeatureControl);
        keyList.add(KeyReleaseGimbalFeatureControl);
        keyList.add(KeyOM3GimbalSpecialMode);
        keyList.add(KeyDemoFunctionSwitch);
        keyList.add(KeyFineTuneRollInDegrees);
        keyList.add(KeyPitchRangeExtensionEnabled);
        keyList.add(KeyYawSmoothingFactor);
        keyList.add(KeyGimbalAttitudeQuaternion);
        keyList.add(KeyPitchSmoothingFactor);
        keyList.add(KeyCheckPhoneOffset);
        keyList.add(KeyPitchSmoothingFactorRange);
        keyList.add(KeyYawSmoothingFactorRange);
        keyList.add(KeyPitchMaxSpeedRange);
        keyList.add(KeyPitchMaxSpeed);
        keyList.add(KeyPitchSmoothingFactorOnTripodState);
        keyList.add(KeyPitchSmoothingFactorOnTripodStateRange);
        keyList.add(KeyPitchSmoothingFactorOnSportState);
        keyList.add(KeyPitchSmoothingFactorOnSportStateRange);
        keyList.add(KeyYawControlMaxSpeed);
        keyList.add(KeyPitchControlMaxSpeed);
        keyList.add(KeyPitchMaxSpeedOnTripodState);
        keyList.add(KeyPitchMaxSpeedOnTripodStateRange);
        keyList.add(KeyPitchMaxSpeedOnSportState);
        keyList.add(KeyPitchMaxSpeedOnSportStateRange);
        keyList.add(KeyRollControllerMaxSpeed);
        keyList.add(KeyRollSmoothingFactor);
        keyList.add(KeyResetGimbalEvent);
        keyList.add(KeyYawAdjustSupported);
        keyList.add(KeyYawEulerDeviation);
        keyList.add(KeyLimitationEnabled);
        keyList.add(KeyGimbalTriggerButtonExecutionEvent);
        keyList.add(KeyGimbalFunctionButtonExecutionEvent);
        keyList.add(KeyGimbalZoomTelephotoButtonExecutionEvent);
        keyList.add(KeyGimbalZoomWideButtonExecutionEvent);
        keyList.add(KeyStickGimbalControlEnabled);
        keyList.add(KeyGimbalSideButtonExecutionEvent);
        keyList.add(KeyRotateByMLVotInfo);
        keyList.add(KeyStepFrequency);
        keyList.add(KeyTiltAngle);
        keyList.add(KeySmartTrackingSpeed);
        keyList.add(KeyYawMotorControlStiffness);
        keyList.add(KeyPitchMotorControlStiffness);
        keyList.add(KeyRollMotorControlStiffness);
        keyList.add(KeyResetControlParameters);
        keyList.add(KeyStartControlParametersAutoTuning);
        keyList.add(KeyStopControlParametersAutoTuning);
        keyList.add(KeyStiffnessSelfTuningResult);
        keyList.add(KeyStartBalanceDetection);
        keyList.add(KeyStopBalanceDetection);
        keyList.add(KeyBalanceCheckResult);
        keyList.add(KeyStartConcentricityDetection);
        keyList.add(KeyStopConcentricityDetection);
        keyList.add(KeyConcentricityCheckResult);
        keyList.add(KeyQuaternionMeas);
        keyList.add(KeyGimbalComponentType);
        keyList.add(KeyWheelControlEvent);
        keyList.add(KeyIsTripodModeOn);
        keyList.add(KeyGimbalWheelButtonExecutionEvent);
        keyList.add(KeyMachineLearningRollControlEnable);
        keyList.add(KeyResetParameters);
        keyList.add(KeyIsInFFGMode);
        keyList.add(KeyGimbalPinInfo);
        keyList.add(KeyDeviceID);
        keyList.add(KeyConnection);
        keyList.add(KeyForceUpdateCacheValue);
        keyList.add(KeyCalibrationFileStatus);
        keyList.add(KeyCalibrationFileUpdatingInfo);
        keyList.add(KeyUpdateCalibrationFile);
        keyList.add(KeyUpgradeNotifyInfo);
        keyList.add(KeyEnforceUpgradeEnable);
        keyList.add(KeyIsInEnforceUpgradeStatus);
        keyList.add(KeyIsDirectDevice);
        keyList.add(KeyCommonFileUpdatingInfo);
        keyList.add(KeyStartCommonFileUpdate);
        keyList.add(KeyStopCommonFileUpdate);
        keyList.add(KeySelfDiagnosticMode);
        keyList.add(KeySelfDiagnosticRequest);
        keyList.add(KeySelfDiagnosticCancel);
        keyList.add(KeySelfDiagnosticStatus);
        keyList.add(KeySelfDiagnosticParts);
    }
}

