/*
 * Decompiled with CFR 0.152.
 */
package dji.sdk.keyvalue.key;

import dji.sdk.keyvalue.converter.BufferConverter;
import dji.sdk.keyvalue.converter.DJIValueConverter;
import dji.sdk.keyvalue.converter.EmptyValueConverter;
import dji.sdk.keyvalue.converter.SingleValueConverter;
import dji.sdk.keyvalue.key.ComponentType;
import dji.sdk.keyvalue.key.DJIActionKeyInfo;
import dji.sdk.keyvalue.key.DJIKeyInfo;
import dji.sdk.keyvalue.key.SubComponentType;
import dji.sdk.keyvalue.value.common.CalibrationFileStatus;
import dji.sdk.keyvalue.value.common.CalibrationFileStatusMsg;
import dji.sdk.keyvalue.value.common.CalibrationFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.CommonFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.EmptyMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapability;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapabilityMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCode;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCodeMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticPartsInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticProgress;
import dji.sdk.keyvalue.value.common.SelfDiagnosticRequestInfo;
import dji.sdk.keyvalue.value.common.UpgradeNotifyInfo;
import dji.sdk.keyvalue.value.file.CommonFile;
import dji.sdk.keyvalue.value.onboard.ArrestFlightErrorDescMsg;
import dji.sdk.keyvalue.value.payload.AppSystemInfo;
import dji.sdk.keyvalue.value.payload.FetchPayloadConfigFile;
import dji.sdk.keyvalue.value.payload.FetchePayloadConfigResult;
import dji.sdk.keyvalue.value.payload.FetchePayloadConfigResultMsg;
import dji.sdk.keyvalue.value.payload.FloatingWindowWidget;
import dji.sdk.keyvalue.value.payload.IconFileRsp;
import dji.sdk.keyvalue.value.payload.MegaphonePlayMode;
import dji.sdk.keyvalue.value.payload.MegaphonePlayModeMsg;
import dji.sdk.keyvalue.value.payload.MegaphonePlayStateMsg;
import dji.sdk.keyvalue.value.payload.MegaphoneWorkMode;
import dji.sdk.keyvalue.value.payload.MegaphoneWorkModeMsg;
import dji.sdk.keyvalue.value.payload.PayloadProductPhaseMsg;
import dji.sdk.keyvalue.value.payload.PayloadProductPhaseType;
import dji.sdk.keyvalue.value.payload.PayloadType;
import dji.sdk.keyvalue.value.payload.PayloadTypeMsg;
import dji.sdk.keyvalue.value.payload.SpeakerWidget;
import dji.sdk.keyvalue.value.payload.TextInputParam;
import dji.sdk.keyvalue.value.payload.WidgetInfoSet;
import dji.sdk.keyvalue.value.payload.WidgetJsonFileVersion;
import dji.sdk.keyvalue.value.payload.WidgetSet;
import dji.sdk.keyvalue.value.payload.WidgetValue;
import java.util.ArrayList;
import java.util.List;

public class DJIOnboardKey {
    protected static final List<DJIKeyInfo<?>> keyList = new ArrayList();
    private static final ComponentType componentType = ComponentType.ONBOARD;
    private static final SubComponentType subComponentType = SubComponentType.IGNORE;
    public static final DJIKeyInfo<String> KeySerialNumber = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SerialNumber", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyFirmwareVersion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FirmwareVersion", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyPayloadSerialNumber = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PayloadSerialNumber", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyPayloadFirmwareVersion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PayloadFirmwareVersion", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<byte[], EmptyMsg> KeySendDataToOnBoardSDKDevice = new DJIActionKeyInfo<byte[], EmptyMsg>(componentType.value(), subComponentType.value(), "SendDataToOnBoardSDKDevice", BufferConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<byte[]> KeyOnBoardSDKDeviceReceivedData = new DJIKeyInfo<byte[]>(componentType.value(), subComponentType.value(), "OnBoardSDKDeviceReceivedData", BufferConverter.converter).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIActionKeyInfo<byte[], EmptyMsg> KeyNewSendDataToOnBoardSDKDevice = new DJIActionKeyInfo<byte[], EmptyMsg>(componentType.value(), subComponentType.value(), "NewSendDataToOnBoardSDKDevice", BufferConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<byte[]> KeyNewOnBoardSDKDeviceReceivedData = new DJIKeyInfo<byte[]>(componentType.value(), subComponentType.value(), "NewOnBoardSDKDeviceReceivedData", BufferConverter.converter).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<Boolean> KeyPowerSupplyPortEnabled = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PowerSupplyPortEnabled", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyEnableOnboardSDK = new DJIKeyInfo(componentType.value(), subComponentType.value(), "EnableOnboardSDK", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyEnableVision = new DJIKeyInfo(componentType.value(), subComponentType.value(), "EnableVision", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyFetchWidgetFile = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "FetchWidgetFile", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<CommonFile, IconFileRsp> KeyFetchIconFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "FetchIconFile", new DJIValueConverter<CommonFile>(CommonFile.class), new DJIValueConverter<IconFileRsp>(IconFileRsp.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyFetchWidgetFileProgress = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FetchWidgetFileProgress", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<WidgetInfoSet> KeyWidgetInfoSet = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WidgetInfoSet", new DJIValueConverter<WidgetInfoSet>(WidgetInfoSet.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<WidgetJsonFileVersion> KeyWidgetJsonFileVersion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WidgetJsonFileVersion", new DJIValueConverter<WidgetJsonFileVersion>(WidgetJsonFileVersion.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<FloatingWindowWidget> KeyFloatingWindowWidget = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FloatingWindowWidget", new DJIValueConverter<FloatingWindowWidget>(FloatingWindowWidget.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<SpeakerWidget> KeySpeakerWidget = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SpeakerWidget", new DJIValueConverter<SpeakerWidget>(SpeakerWidget.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<WidgetSet> KeyMainInterfaceWidget = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MainInterfaceWidget", new DJIValueConverter<WidgetSet>(WidgetSet.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<WidgetSet> KeyConfigInterfaceWidget = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ConfigInterfaceWidget", new DJIValueConverter<WidgetSet>(WidgetSet.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<PayloadProductPhaseType> KeyOnboardProductPhase = new DJIKeyInfo<PayloadProductPhaseType>(componentType.value(), subComponentType.value(), "OnboardProductPhase", new SingleValueConverter<PayloadProductPhaseType, PayloadProductPhaseMsg>(PayloadProductPhaseType.class, PayloadProductPhaseMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<ArrestFlightErrorDescMsg> KeyArrestFlightErrorDescToApp = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ArrestFlightErrorDescToApp", new DJIValueConverter<ArrestFlightErrorDescMsg>(ArrestFlightErrorDescMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyOnboardProductName = new DJIKeyInfo(componentType.value(), subComponentType.value(), "OnboardProductName", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<PayloadType> KeyOnboardProductType = new DJIKeyInfo<PayloadType>(componentType.value(), subComponentType.value(), "OnboardProductType", new SingleValueConverter<PayloadType, PayloadTypeMsg>(PayloadType.class, PayloadTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsOnboardProductReady = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsOnboardProductReady", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<AppSystemInfo> KeyAppSystemInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AppSystemInfo", new DJIValueConverter<AppSystemInfo>(AppSystemInfo.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<WidgetValue> KeySetWidgetValue = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SetWidgetValue", new DJIValueConverter<WidgetValue>(WidgetValue.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<TextInputParam> KeyTextInputParam = new DJIKeyInfo(componentType.value(), subComponentType.value(), "TextInputParam", new DJIValueConverter<TextInputParam>(TextInputParam.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyDataFloatHintMsgFromPayload = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DataFloatHintMsgFromPayload", SingleValueConverter.StringConverter).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<MegaphoneWorkMode> KeyMegaphoneWorkMode = new DJIKeyInfo<MegaphoneWorkMode>(componentType.value(), subComponentType.value(), "MegaphoneWorkMode", new SingleValueConverter<MegaphoneWorkMode, MegaphoneWorkModeMsg>(MegaphoneWorkMode.class, MegaphoneWorkModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<MegaphonePlayMode> KeyMegaphonePlayMode = new DJIKeyInfo<MegaphonePlayMode>(componentType.value(), subComponentType.value(), "MegaphonePlayMode", new SingleValueConverter<MegaphonePlayMode, MegaphonePlayModeMsg>(MegaphonePlayMode.class, MegaphonePlayModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyMegaphoneVolume = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MegaphoneVolume", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyMegaphoneFileName = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MegaphoneFileName", SingleValueConverter.StringConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<MegaphonePlayStateMsg> KeyMegaphonePlayState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MegaphonePlayState", new DJIValueConverter<MegaphonePlayStateMsg>(MegaphonePlayStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyMegaphoneStartPlay = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "MegaphoneStartPlay", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyMegaphoneStopPlay = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "MegaphoneStopPlay", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyMegaphonePausePlay = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "MegaphonePausePlay", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<FetchPayloadConfigFile, FetchePayloadConfigResult> KeyFetchPayloadConfigFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "FetchPayloadConfigFile", new DJIValueConverter<FetchPayloadConfigFile>(FetchPayloadConfigFile.class), new SingleValueConverter<FetchePayloadConfigResult, FetchePayloadConfigResultMsg>(FetchePayloadConfigResult.class, FetchePayloadConfigResultMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsHmsSupport = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsHmsSupport", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyDeviceID = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DeviceID", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyConnection = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Connection", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyForceUpdateCacheValue = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ForceUpdateCacheValue", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileStatus> KeyCalibrationFileStatus = new DJIKeyInfo<CalibrationFileStatus>(componentType.value(), subComponentType.value(), "CalibrationFileStatus", new SingleValueConverter<CalibrationFileStatus, CalibrationFileStatusMsg>(CalibrationFileStatus.class, CalibrationFileStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileUpdatingInfo> KeyCalibrationFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CalibrationFileUpdatingInfo", new DJIValueConverter<CalibrationFileUpdatingInfo>(CalibrationFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyUpdateCalibrationFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "UpdateCalibrationFile", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<UpgradeNotifyInfo> KeyUpgradeNotifyInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UpgradeNotifyInfo", new DJIValueConverter<UpgradeNotifyInfo>(UpgradeNotifyInfo.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyEnforceUpgradeEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "EnforceUpgradeEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsInEnforceUpgradeStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsInEnforceUpgradeStatus", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsDirectDevice = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsDirectDevice", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CommonFileUpdatingInfo> KeyCommonFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CommonFileUpdatingInfo", new DJIValueConverter<CommonFileUpdatingInfo>(CommonFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyStartCommonFileUpdate = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StartCommonFileUpdate", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopCommonFileUpdate = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopCommonFileUpdate", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticMode = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticMode", new DJIValueConverter<SelfDiagnosticInfo>(SelfDiagnosticInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticRequestInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticRequest = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticRequest", new DJIValueConverter<SelfDiagnosticRequestInfo>(SelfDiagnosticRequestInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode> KeySelfDiagnosticCancel = new DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode>(componentType.value(), subComponentType.value(), "SelfDiagnosticCancel", EmptyValueConverter.converter, new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<SelfDiagnosticProgress> KeySelfDiagnosticStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticStatus", new DJIValueConverter<SelfDiagnosticProgress>(SelfDiagnosticProgress.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticCapability, SelfDiagnosticPartsInfo> KeySelfDiagnosticParts = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticParts", new SingleValueConverter<SelfDiagnosticCapability, SelfDiagnosticCapabilityMsg>(SelfDiagnosticCapability.class, SelfDiagnosticCapabilityMsg.class), new DJIValueConverter<SelfDiagnosticPartsInfo>(SelfDiagnosticPartsInfo.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);

    static {
        keyList.add(KeySerialNumber);
        keyList.add(KeyFirmwareVersion);
        keyList.add(KeyPayloadSerialNumber);
        keyList.add(KeyPayloadFirmwareVersion);
        keyList.add(KeySendDataToOnBoardSDKDevice);
        keyList.add(KeyOnBoardSDKDeviceReceivedData);
        keyList.add(KeyNewSendDataToOnBoardSDKDevice);
        keyList.add(KeyNewOnBoardSDKDeviceReceivedData);
        keyList.add(KeyPowerSupplyPortEnabled);
        keyList.add(KeyEnableOnboardSDK);
        keyList.add(KeyEnableVision);
        keyList.add(KeyFetchWidgetFile);
        keyList.add(KeyFetchIconFile);
        keyList.add(KeyFetchWidgetFileProgress);
        keyList.add(KeyWidgetInfoSet);
        keyList.add(KeyWidgetJsonFileVersion);
        keyList.add(KeyFloatingWindowWidget);
        keyList.add(KeySpeakerWidget);
        keyList.add(KeyMainInterfaceWidget);
        keyList.add(KeyConfigInterfaceWidget);
        keyList.add(KeyOnboardProductPhase);
        keyList.add(KeyArrestFlightErrorDescToApp);
        keyList.add(KeyOnboardProductName);
        keyList.add(KeyOnboardProductType);
        keyList.add(KeyIsOnboardProductReady);
        keyList.add(KeyAppSystemInfo);
        keyList.add(KeySetWidgetValue);
        keyList.add(KeyTextInputParam);
        keyList.add(KeyDataFloatHintMsgFromPayload);
        keyList.add(KeyMegaphoneWorkMode);
        keyList.add(KeyMegaphonePlayMode);
        keyList.add(KeyMegaphoneVolume);
        keyList.add(KeyMegaphoneFileName);
        keyList.add(KeyMegaphonePlayState);
        keyList.add(KeyMegaphoneStartPlay);
        keyList.add(KeyMegaphoneStopPlay);
        keyList.add(KeyMegaphonePausePlay);
        keyList.add(KeyFetchPayloadConfigFile);
        keyList.add(KeyIsHmsSupport);
        keyList.add(KeyDeviceID);
        keyList.add(KeyConnection);
        keyList.add(KeyForceUpdateCacheValue);
        keyList.add(KeyCalibrationFileStatus);
        keyList.add(KeyCalibrationFileUpdatingInfo);
        keyList.add(KeyUpdateCalibrationFile);
        keyList.add(KeyUpgradeNotifyInfo);
        keyList.add(KeyEnforceUpgradeEnable);
        keyList.add(KeyIsInEnforceUpgradeStatus);
        keyList.add(KeyIsDirectDevice);
        keyList.add(KeyCommonFileUpdatingInfo);
        keyList.add(KeyStartCommonFileUpdate);
        keyList.add(KeyStopCommonFileUpdate);
        keyList.add(KeySelfDiagnosticMode);
        keyList.add(KeySelfDiagnosticRequest);
        keyList.add(KeySelfDiagnosticCancel);
        keyList.add(KeySelfDiagnosticStatus);
        keyList.add(KeySelfDiagnosticParts);
    }
}

