/*
 * Decompiled with CFR 0.152.
 */
package dji.sdk.keyvalue.key;

import dji.sdk.keyvalue.converter.BufferConverter;
import dji.sdk.keyvalue.converter.DJIValueConverter;
import dji.sdk.keyvalue.converter.EmptyValueConverter;
import dji.sdk.keyvalue.converter.SingleValueConverter;
import dji.sdk.keyvalue.key.ComponentType;
import dji.sdk.keyvalue.key.DJIActionKeyInfo;
import dji.sdk.keyvalue.key.DJIKeyInfo;
import dji.sdk.keyvalue.key.SubComponentType;
import dji.sdk.keyvalue.value.activate.ActivateStateMsg;
import dji.sdk.keyvalue.value.common.CalibrationFileStatus;
import dji.sdk.keyvalue.value.common.CalibrationFileStatusMsg;
import dji.sdk.keyvalue.value.common.CalibrationFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.CommonFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.EmptyMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapability;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapabilityMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCode;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCodeMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticPartsInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticProgress;
import dji.sdk.keyvalue.value.common.SelfDiagnosticRequestInfo;
import dji.sdk.keyvalue.value.common.UpgradeNotifyInfo;
import dji.sdk.keyvalue.value.file.CommonFile;
import dji.sdk.keyvalue.value.flightassistant.AIModelInfoMsg;
import dji.sdk.keyvalue.value.flightassistant.AIModelOverview;
import dji.sdk.keyvalue.value.flightassistant.AIModelOverviewMsg;
import dji.sdk.keyvalue.value.payload.AlarmEnhancePromptMsg;
import dji.sdk.keyvalue.value.payload.AppSystemInfo;
import dji.sdk.keyvalue.value.payload.ArCirclesMsg;
import dji.sdk.keyvalue.value.payload.ArDeleteCircleMsg;
import dji.sdk.keyvalue.value.payload.ArDeleteLineMsg;
import dji.sdk.keyvalue.value.payload.ArDeletePivotAxisMsg;
import dji.sdk.keyvalue.value.payload.ArDeletePointMsg;
import dji.sdk.keyvalue.value.payload.ArDeletePolygonMsg;
import dji.sdk.keyvalue.value.payload.ArLinesMsg;
import dji.sdk.keyvalue.value.payload.ArPivotAxesMsg;
import dji.sdk.keyvalue.value.payload.ArPointsMsg;
import dji.sdk.keyvalue.value.payload.ArPolygonsMsg;
import dji.sdk.keyvalue.value.payload.FetchPayloadConfigFile;
import dji.sdk.keyvalue.value.payload.FetchePayloadConfigResult;
import dji.sdk.keyvalue.value.payload.FetchePayloadConfigResultMsg;
import dji.sdk.keyvalue.value.payload.FloatingWindowWidget;
import dji.sdk.keyvalue.value.payload.IconFileRsp;
import dji.sdk.keyvalue.value.payload.LightCtrlMsg;
import dji.sdk.keyvalue.value.payload.LightGimbalAdjustMsg;
import dji.sdk.keyvalue.value.payload.LightGimbalAdjustResult;
import dji.sdk.keyvalue.value.payload.LightGimbalAdjustResultMsg;
import dji.sdk.keyvalue.value.payload.LightGimbalAdjustStateMsg;
import dji.sdk.keyvalue.value.payload.LightGimbalAutoAdjustMsg;
import dji.sdk.keyvalue.value.payload.LightGimbalAutoAdjustResult;
import dji.sdk.keyvalue.value.payload.LightGimbalAutoAdjustResultMsg;
import dji.sdk.keyvalue.value.payload.LightStateMsg;
import dji.sdk.keyvalue.value.payload.MegaphonePlayMode;
import dji.sdk.keyvalue.value.payload.MegaphonePlayModeMsg;
import dji.sdk.keyvalue.value.payload.MegaphonePlayStateMsg;
import dji.sdk.keyvalue.value.payload.MegaphoneWorkMode;
import dji.sdk.keyvalue.value.payload.MegaphoneWorkModeMsg;
import dji.sdk.keyvalue.value.payload.PayloadCameraType;
import dji.sdk.keyvalue.value.payload.PayloadCameraTypeMsg;
import dji.sdk.keyvalue.value.payload.PayloadProductInfo;
import dji.sdk.keyvalue.value.payload.PayloadProductPhaseMsg;
import dji.sdk.keyvalue.value.payload.PayloadProductPhaseType;
import dji.sdk.keyvalue.value.payload.PayloadType;
import dji.sdk.keyvalue.value.payload.PayloadTypeMsg;
import dji.sdk.keyvalue.value.payload.PsdkBindStateMsg;
import dji.sdk.keyvalue.value.payload.SpeakerWidget;
import dji.sdk.keyvalue.value.payload.TextInputParam;
import dji.sdk.keyvalue.value.payload.WidgetInfoSet;
import dji.sdk.keyvalue.value.payload.WidgetJsonFileVersion;
import dji.sdk.keyvalue.value.payload.WidgetSet;
import dji.sdk.keyvalue.value.payload.WidgetValue;
import java.util.ArrayList;
import java.util.List;

public class DJIPayloadKey {
    protected static final List<DJIKeyInfo<?>> keyList = new ArrayList();
    private static final ComponentType componentType = ComponentType.PAYLOAD;
    private static final SubComponentType subComponentType = SubComponentType.IGNORE;
    public static final DJIKeyInfo<String> KeySerialNumber = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SerialNumber", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyFirmwareVersion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FirmwareVersion", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyPayloadSerialNumber = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PayloadSerialNumber", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyPayloadFirmwareVersion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PayloadFirmwareVersion", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<PayloadType> KeyPayloadType = new DJIKeyInfo<PayloadType>(componentType.value(), subComponentType.value(), "PayloadType", new SingleValueConverter<PayloadType, PayloadTypeMsg>(PayloadType.class, PayloadTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<WidgetSet> KeyConfigInterfaceWidget = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ConfigInterfaceWidget", new DJIValueConverter<WidgetSet>(WidgetSet.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyWidgetConfigJson = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WidgetConfigJson", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<WidgetValue> KeySetWidgetValue = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SetWidgetValue", new DJIValueConverter<WidgetValue>(WidgetValue.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<WidgetValue, WidgetValue> KeyGetWidgetValue = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "GetWidgetValue", new DJIValueConverter<WidgetValue>(WidgetValue.class), new DJIValueConverter<WidgetValue>(WidgetValue.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyPayloadProductName = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PayloadProductName", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsAccessoryConnected = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsAccessoryConnected", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsPayloadProductReady = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsPayloadProductReady", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyIsFeatureOpen = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsFeatureOpen", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<PayloadProductPhaseType> KeyPayloadProductPhase = new DJIKeyInfo<PayloadProductPhaseType>(componentType.value(), subComponentType.value(), "PayloadProductPhase", new SingleValueConverter<PayloadProductPhaseType, PayloadProductPhaseMsg>(PayloadProductPhaseType.class, PayloadProductPhaseMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyDataFloatHintMsgFromPayload = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DataFloatHintMsgFromPayload", SingleValueConverter.StringConverter).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<byte[]> KeyDataFromPayload = new DJIKeyInfo<byte[]>(componentType.value(), subComponentType.value(), "DataFromPayload", BufferConverter.converter).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<byte[], EmptyMsg> KeySendDataToPayload = new DJIActionKeyInfo<byte[], EmptyMsg>(componentType.value(), subComponentType.value(), "SendDataToPayload", BufferConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyUploadBandwidthLimit = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UploadBandwidthLimit", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<TextInputParam> KeyTextInputParam = new DJIKeyInfo(componentType.value(), subComponentType.value(), "TextInputParam", new DJIValueConverter<TextInputParam>(TextInputParam.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyFetchWidgetFile = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "FetchWidgetFile", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<CommonFile, IconFileRsp> KeyFetchIconFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "FetchIconFile", new DJIValueConverter<CommonFile>(CommonFile.class), new DJIValueConverter<IconFileRsp>(IconFileRsp.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<WidgetInfoSet> KeyWidgetInfoSet = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WidgetInfoSet", new DJIValueConverter<WidgetInfoSet>(WidgetInfoSet.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyFetchWidgetFileProgress = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FetchWidgetFileProgress", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<WidgetJsonFileVersion> KeyWidgetJsonFileVersion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WidgetJsonFileVersion", new DJIValueConverter<WidgetJsonFileVersion>(WidgetJsonFileVersion.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<FloatingWindowWidget> KeyFloatingWindowWidget = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FloatingWindowWidget", new DJIValueConverter<FloatingWindowWidget>(FloatingWindowWidget.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<SpeakerWidget> KeySpeakerWidget = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SpeakerWidget", new DJIValueConverter<SpeakerWidget>(SpeakerWidget.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<WidgetSet> KeyMainInterfaceWidget = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MainInterfaceWidget", new DJIValueConverter<WidgetSet>(WidgetSet.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<ActivateStateMsg> KeyActivateStateInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ActivateStateInfo", new DJIValueConverter<ActivateStateMsg>(ActivateStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<PsdkBindStateMsg> KeyBindState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BindState", new DJIValueConverter<PsdkBindStateMsg>(PsdkBindStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<AppSystemInfo> KeyAppSystemInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AppSystemInfo", new DJIValueConverter<AppSystemInfo>(AppSystemInfo.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsMaVideoChannelSupport = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsMaVideoChannelSupport", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<PayloadCameraType> KeyPayloadCameraType = new DJIKeyInfo<PayloadCameraType>(componentType.value(), subComponentType.value(), "PayloadCameraType", new SingleValueConverter<PayloadCameraType, PayloadCameraTypeMsg>(PayloadCameraType.class, PayloadCameraTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyPayloadLibVersion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PayloadLibVersion", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<MegaphoneWorkMode> KeyMegaphoneWorkMode = new DJIKeyInfo<MegaphoneWorkMode>(componentType.value(), subComponentType.value(), "MegaphoneWorkMode", new SingleValueConverter<MegaphoneWorkMode, MegaphoneWorkModeMsg>(MegaphoneWorkMode.class, MegaphoneWorkModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<MegaphonePlayMode> KeyMegaphonePlayMode = new DJIKeyInfo<MegaphonePlayMode>(componentType.value(), subComponentType.value(), "MegaphonePlayMode", new SingleValueConverter<MegaphonePlayMode, MegaphonePlayModeMsg>(MegaphonePlayMode.class, MegaphonePlayModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyMegaphoneVolume = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MegaphoneVolume", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyMegaphoneRealVolume = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MegaphoneRealVolume", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyMegaphonePlayQuality = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MegaphonePlayQuality", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyMegaphoneLimitVolumeOnTheGround = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MegaphoneLimitVolumeOnTheGround", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyMegaphoneFileName = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MegaphoneFileName", SingleValueConverter.StringConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<MegaphonePlayStateMsg> KeyMegaphonePlayState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MegaphonePlayState", new DJIValueConverter<MegaphonePlayStateMsg>(MegaphonePlayStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyMegaphoneStartPlay = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "MegaphoneStartPlay", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyMegaphoneStopPlay = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "MegaphoneStopPlay", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyMegaphonePausePlay = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "MegaphonePausePlay", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<FetchPayloadConfigFile, FetchePayloadConfigResult> KeyFetchPayloadConfigFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "FetchPayloadConfigFile", new DJIValueConverter<FetchPayloadConfigFile>(FetchPayloadConfigFile.class), new SingleValueConverter<FetchePayloadConfigResult, FetchePayloadConfigResultMsg>(FetchePayloadConfigResult.class, FetchePayloadConfigResultMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsHmsSupport = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsHmsSupport", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<PayloadProductInfo> KeyPayloadProductInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PayloadProductInfo", new DJIValueConverter<PayloadProductInfo>(PayloadProductInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<LightCtrlMsg> KeyLightCtrl = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LightCtrl", new DJIValueConverter<LightCtrlMsg>(LightCtrlMsg.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyWideFieldModeEnabled = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WideFieldModeEnabled", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyLightGimbalControlEnabled = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LightGimbalControlEnabled", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<LightStateMsg> KeyLightState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LightState", new DJIValueConverter<LightStateMsg>(LightStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<LightGimbalAdjustMsg, LightGimbalAdjustResult> KeyLightGimbalAdjust = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "LightGimbalAdjust", new DJIValueConverter<LightGimbalAdjustMsg>(LightGimbalAdjustMsg.class), new SingleValueConverter<LightGimbalAdjustResult, LightGimbalAdjustResultMsg>(LightGimbalAdjustResult.class, LightGimbalAdjustResultMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<LightGimbalAdjustStateMsg> KeyLightGimbalAdjustState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LightGimbalAdjustState", new DJIValueConverter<LightGimbalAdjustStateMsg>(LightGimbalAdjustStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, LightGimbalAutoAdjustResult> KeyLightGimbalAutoAdjust = new DJIActionKeyInfo<EmptyMsg, LightGimbalAutoAdjustResult>(componentType.value(), subComponentType.value(), "LightGimbalAutoAdjust", EmptyValueConverter.converter, new SingleValueConverter<LightGimbalAutoAdjustResult, LightGimbalAutoAdjustResultMsg>(LightGimbalAutoAdjustResult.class, LightGimbalAutoAdjustResultMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<AlarmEnhancePromptMsg> KeyAlarmEnhancePrompt = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AlarmEnhancePrompt", new DJIValueConverter<AlarmEnhancePromptMsg>(AlarmEnhancePromptMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<LightGimbalAutoAdjustMsg> KeyLightGimbalAutoAdjustState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LightGimbalAutoAdjustState", new DJIValueConverter<LightGimbalAutoAdjustMsg>(LightGimbalAutoAdjustMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<AIModelOverview>> KeyAIModelList = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "AIModelList", new SingleValueConverter<List, AIModelOverviewMsg>(List.class, AIModelOverviewMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<Integer, AIModelInfoMsg> KeyAIModelInfo = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "AIModelInfo", SingleValueConverter.IntegerConverter, new DJIValueConverter<AIModelInfoMsg>(AIModelInfoMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyAiRegAiLabelInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "AiRegAiLabelInfo", SingleValueConverter.BooleanConverter).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<ArPointsMsg> KeyArSetPoints = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ArSetPoints", new DJIValueConverter<ArPointsMsg>(ArPointsMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<ArPointsMsg> KeyArUpdatePoints = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ArUpdatePoints", new DJIValueConverter<ArPointsMsg>(ArPointsMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<ArDeletePointMsg> KeyArDeletePoint = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ArDeletePoint", new DJIValueConverter<ArDeletePointMsg>(ArDeletePointMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<ArLinesMsg> KeyArSetLines = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ArSetLines", new DJIValueConverter<ArLinesMsg>(ArLinesMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<ArLinesMsg> KeyArUpdateLines = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ArUpdateLines", new DJIValueConverter<ArLinesMsg>(ArLinesMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<ArDeleteLineMsg> KeyArDeleteLine = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ArDeleteLine", new DJIValueConverter<ArDeleteLineMsg>(ArDeleteLineMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<ArCirclesMsg> KeyArSetCircles = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ArSetCircles", new DJIValueConverter<ArCirclesMsg>(ArCirclesMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<ArCirclesMsg> KeyArUpdateCircles = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ArUpdateCircles", new DJIValueConverter<ArCirclesMsg>(ArCirclesMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<ArDeleteCircleMsg> KeyArDeleteCircle = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ArDeleteCircle", new DJIValueConverter<ArDeleteCircleMsg>(ArDeleteCircleMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<ArPolygonsMsg> KeyArSetPolygons = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ArSetPolygons", new DJIValueConverter<ArPolygonsMsg>(ArPolygonsMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<ArPolygonsMsg> KeyArUpdatePolygons = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ArUpdatePolygons", new DJIValueConverter<ArPolygonsMsg>(ArPolygonsMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<ArDeletePolygonMsg> KeyArDeletePolygon = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ArDeletePolygon", new DJIValueConverter<ArDeletePolygonMsg>(ArDeletePolygonMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<ArPivotAxesMsg> KeyArSetPivotAxes = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ArSetPivotAxes", new DJIValueConverter<ArPivotAxesMsg>(ArPivotAxesMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<ArPivotAxesMsg> KeyArUpdatePivotAxes = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ArUpdatePivotAxes", new DJIValueConverter<ArPivotAxesMsg>(ArPivotAxesMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<ArDeletePivotAxisMsg> KeyArDeletePivotAxis = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ArDeletePivotAxis", new DJIValueConverter<ArDeletePivotAxisMsg>(ArDeletePivotAxisMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyArNotifyReady = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "ArNotifyReady", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyDeviceID = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DeviceID", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyConnection = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Connection", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyForceUpdateCacheValue = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ForceUpdateCacheValue", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileStatus> KeyCalibrationFileStatus = new DJIKeyInfo<CalibrationFileStatus>(componentType.value(), subComponentType.value(), "CalibrationFileStatus", new SingleValueConverter<CalibrationFileStatus, CalibrationFileStatusMsg>(CalibrationFileStatus.class, CalibrationFileStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileUpdatingInfo> KeyCalibrationFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CalibrationFileUpdatingInfo", new DJIValueConverter<CalibrationFileUpdatingInfo>(CalibrationFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyUpdateCalibrationFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "UpdateCalibrationFile", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<UpgradeNotifyInfo> KeyUpgradeNotifyInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UpgradeNotifyInfo", new DJIValueConverter<UpgradeNotifyInfo>(UpgradeNotifyInfo.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyEnforceUpgradeEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "EnforceUpgradeEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsInEnforceUpgradeStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsInEnforceUpgradeStatus", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsDirectDevice = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsDirectDevice", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CommonFileUpdatingInfo> KeyCommonFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CommonFileUpdatingInfo", new DJIValueConverter<CommonFileUpdatingInfo>(CommonFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyStartCommonFileUpdate = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StartCommonFileUpdate", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopCommonFileUpdate = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopCommonFileUpdate", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticMode = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticMode", new DJIValueConverter<SelfDiagnosticInfo>(SelfDiagnosticInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticRequestInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticRequest = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticRequest", new DJIValueConverter<SelfDiagnosticRequestInfo>(SelfDiagnosticRequestInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode> KeySelfDiagnosticCancel = new DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode>(componentType.value(), subComponentType.value(), "SelfDiagnosticCancel", EmptyValueConverter.converter, new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<SelfDiagnosticProgress> KeySelfDiagnosticStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticStatus", new DJIValueConverter<SelfDiagnosticProgress>(SelfDiagnosticProgress.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticCapability, SelfDiagnosticPartsInfo> KeySelfDiagnosticParts = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticParts", new SingleValueConverter<SelfDiagnosticCapability, SelfDiagnosticCapabilityMsg>(SelfDiagnosticCapability.class, SelfDiagnosticCapabilityMsg.class), new DJIValueConverter<SelfDiagnosticPartsInfo>(SelfDiagnosticPartsInfo.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);

    static {
        keyList.add(KeySerialNumber);
        keyList.add(KeyFirmwareVersion);
        keyList.add(KeyPayloadSerialNumber);
        keyList.add(KeyPayloadFirmwareVersion);
        keyList.add(KeyPayloadType);
        keyList.add(KeyConfigInterfaceWidget);
        keyList.add(KeyWidgetConfigJson);
        keyList.add(KeySetWidgetValue);
        keyList.add(KeyGetWidgetValue);
        keyList.add(KeyPayloadProductName);
        keyList.add(KeyIsAccessoryConnected);
        keyList.add(KeyIsPayloadProductReady);
        keyList.add(KeyIsFeatureOpen);
        keyList.add(KeyPayloadProductPhase);
        keyList.add(KeyDataFloatHintMsgFromPayload);
        keyList.add(KeyDataFromPayload);
        keyList.add(KeySendDataToPayload);
        keyList.add(KeyUploadBandwidthLimit);
        keyList.add(KeyTextInputParam);
        keyList.add(KeyFetchWidgetFile);
        keyList.add(KeyFetchIconFile);
        keyList.add(KeyWidgetInfoSet);
        keyList.add(KeyFetchWidgetFileProgress);
        keyList.add(KeyWidgetJsonFileVersion);
        keyList.add(KeyFloatingWindowWidget);
        keyList.add(KeySpeakerWidget);
        keyList.add(KeyMainInterfaceWidget);
        keyList.add(KeyActivateStateInfo);
        keyList.add(KeyBindState);
        keyList.add(KeyAppSystemInfo);
        keyList.add(KeyIsMaVideoChannelSupport);
        keyList.add(KeyPayloadCameraType);
        keyList.add(KeyPayloadLibVersion);
        keyList.add(KeyMegaphoneWorkMode);
        keyList.add(KeyMegaphonePlayMode);
        keyList.add(KeyMegaphoneVolume);
        keyList.add(KeyMegaphoneRealVolume);
        keyList.add(KeyMegaphonePlayQuality);
        keyList.add(KeyMegaphoneLimitVolumeOnTheGround);
        keyList.add(KeyMegaphoneFileName);
        keyList.add(KeyMegaphonePlayState);
        keyList.add(KeyMegaphoneStartPlay);
        keyList.add(KeyMegaphoneStopPlay);
        keyList.add(KeyMegaphonePausePlay);
        keyList.add(KeyFetchPayloadConfigFile);
        keyList.add(KeyIsHmsSupport);
        keyList.add(KeyPayloadProductInfo);
        keyList.add(KeyLightCtrl);
        keyList.add(KeyWideFieldModeEnabled);
        keyList.add(KeyLightGimbalControlEnabled);
        keyList.add(KeyLightState);
        keyList.add(KeyLightGimbalAdjust);
        keyList.add(KeyLightGimbalAdjustState);
        keyList.add(KeyLightGimbalAutoAdjust);
        keyList.add(KeyAlarmEnhancePrompt);
        keyList.add(KeyLightGimbalAutoAdjustState);
        keyList.add(KeyAIModelList);
        keyList.add(KeyAIModelInfo);
        keyList.add(KeyAiRegAiLabelInfo);
        keyList.add(KeyArSetPoints);
        keyList.add(KeyArUpdatePoints);
        keyList.add(KeyArDeletePoint);
        keyList.add(KeyArSetLines);
        keyList.add(KeyArUpdateLines);
        keyList.add(KeyArDeleteLine);
        keyList.add(KeyArSetCircles);
        keyList.add(KeyArUpdateCircles);
        keyList.add(KeyArDeleteCircle);
        keyList.add(KeyArSetPolygons);
        keyList.add(KeyArUpdatePolygons);
        keyList.add(KeyArDeletePolygon);
        keyList.add(KeyArSetPivotAxes);
        keyList.add(KeyArUpdatePivotAxes);
        keyList.add(KeyArDeletePivotAxis);
        keyList.add(KeyArNotifyReady);
        keyList.add(KeyDeviceID);
        keyList.add(KeyConnection);
        keyList.add(KeyForceUpdateCacheValue);
        keyList.add(KeyCalibrationFileStatus);
        keyList.add(KeyCalibrationFileUpdatingInfo);
        keyList.add(KeyUpdateCalibrationFile);
        keyList.add(KeyUpgradeNotifyInfo);
        keyList.add(KeyEnforceUpgradeEnable);
        keyList.add(KeyIsInEnforceUpgradeStatus);
        keyList.add(KeyIsDirectDevice);
        keyList.add(KeyCommonFileUpdatingInfo);
        keyList.add(KeyStartCommonFileUpdate);
        keyList.add(KeyStopCommonFileUpdate);
        keyList.add(KeySelfDiagnosticMode);
        keyList.add(KeySelfDiagnosticRequest);
        keyList.add(KeySelfDiagnosticCancel);
        keyList.add(KeySelfDiagnosticStatus);
        keyList.add(KeySelfDiagnosticParts);
    }
}

