/*
 * Decompiled with CFR 0.152.
 */
package dji.sdk.keyvalue.key;

import dji.sdk.keyvalue.converter.DJIValueConverter;
import dji.sdk.keyvalue.converter.EmptyValueConverter;
import dji.sdk.keyvalue.converter.SingleValueConverter;
import dji.sdk.keyvalue.key.ComponentType;
import dji.sdk.keyvalue.key.DJIActionKeyInfo;
import dji.sdk.keyvalue.key.DJIKeyInfo;
import dji.sdk.keyvalue.key.SubComponentType;
import dji.sdk.keyvalue.value.common.CalibrationFileStatus;
import dji.sdk.keyvalue.value.common.CalibrationFileStatusMsg;
import dji.sdk.keyvalue.value.common.CalibrationFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.CareBindInfo;
import dji.sdk.keyvalue.value.common.CommonFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.DataLinkType;
import dji.sdk.keyvalue.value.common.DataLinkTypeMsg;
import dji.sdk.keyvalue.value.common.DatalinkMonitorRegistResult;
import dji.sdk.keyvalue.value.common.DatalinkMonitorRegistResults;
import dji.sdk.keyvalue.value.common.EmptyMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapability;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapabilityMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCode;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCodeMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticPartsInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticProgress;
import dji.sdk.keyvalue.value.common.SelfDiagnosticRequestInfo;
import dji.sdk.keyvalue.value.common.TLVData;
import dji.sdk.keyvalue.value.common.UpgradeNotifyInfo;
import dji.sdk.keyvalue.value.payload.PayloadSet;
import dji.sdk.keyvalue.value.product.AIBoxInfo;
import dji.sdk.keyvalue.value.product.AIBoxInfoListMsg;
import dji.sdk.keyvalue.value.product.CameraComponentInfo;
import dji.sdk.keyvalue.value.product.CameraComponentInfoMsg;
import dji.sdk.keyvalue.value.product.CareStatusMsg;
import dji.sdk.keyvalue.value.product.CareSupportedInfoMsg;
import dji.sdk.keyvalue.value.product.DJIComponentParam;
import dji.sdk.keyvalue.value.product.DatalinkFullIDListMsg;
import dji.sdk.keyvalue.value.product.DatalinkFullIDMsg;
import dji.sdk.keyvalue.value.product.DeviceRebootTimeInfo;
import dji.sdk.keyvalue.value.product.EagleTestParam;
import dji.sdk.keyvalue.value.product.EportPayloadInfo;
import dji.sdk.keyvalue.value.product.EportPayloadInfoMsg;
import dji.sdk.keyvalue.value.product.GimbalComponentInfo;
import dji.sdk.keyvalue.value.product.GimbalComponentInfoMsg;
import dji.sdk.keyvalue.value.product.LiveState;
import dji.sdk.keyvalue.value.product.MRTCLiveStatusEvent;
import dji.sdk.keyvalue.value.product.MRTCLiveStatusEventMsg;
import dji.sdk.keyvalue.value.product.MRTCOptionSetVideoAttributeMsg;
import dji.sdk.keyvalue.value.product.MRTCPlayEvent;
import dji.sdk.keyvalue.value.product.MRTCPlayEventMsg;
import dji.sdk.keyvalue.value.product.MRTCRegisterEvent;
import dji.sdk.keyvalue.value.product.MRTCVideoParamEvent;
import dji.sdk.keyvalue.value.product.MRTCVideoParamEventMsg;
import dji.sdk.keyvalue.value.product.NPIBuriedDataMsg;
import dji.sdk.keyvalue.value.product.NPIBuriedDataProviderRange;
import dji.sdk.keyvalue.value.product.NPIBuriedDataProviderType;
import dji.sdk.keyvalue.value.product.NPIBuriedDataProviderTypeMsg;
import dji.sdk.keyvalue.value.product.NotSupportAppInfoMsg;
import dji.sdk.keyvalue.value.product.PSDKComponentInfo;
import dji.sdk.keyvalue.value.product.PSDKComponentInfoMsg;
import dji.sdk.keyvalue.value.product.PowerControlAction;
import dji.sdk.keyvalue.value.product.PowerControlParam;
import dji.sdk.keyvalue.value.product.ProductEdition;
import dji.sdk.keyvalue.value.product.ProductEditionMsg;
import dji.sdk.keyvalue.value.product.ProductFirmwareSupportInfo;
import dji.sdk.keyvalue.value.product.ProductType;
import dji.sdk.keyvalue.value.product.ProductTypeMsg;
import dji.sdk.keyvalue.value.product.RadarComponentInfo;
import dji.sdk.keyvalue.value.product.RadarComponentInfoMsg;
import dji.sdk.keyvalue.value.product.RelayComponentInfo;
import dji.sdk.keyvalue.value.product.RelayComponentInfoMsg;
import dji.sdk.keyvalue.value.product.StreamHubLiveChannelInformation;
import dji.sdk.keyvalue.value.product.StreamHubLiveChannelInformationMsg;
import dji.sdk.keyvalue.value.product.StreamHubLiveOptionGetRemainingMsg;
import dji.sdk.keyvalue.value.product.StreamHubLiveOptionSetRemainingMsg;
import dji.sdk.keyvalue.value.product.TemperatureTestInfo;
import dji.sdk.keyvalue.value.product.UnmatchedBindInfo;
import java.util.ArrayList;
import java.util.List;

public class DJIProductKey {
    protected static final List<DJIKeyInfo<?>> keyList = new ArrayList();
    private static final ComponentType componentType = ComponentType.PRODUCT;
    private static final SubComponentType subComponentType = SubComponentType.IGNORE;
    public static final DJIKeyInfo<String> KeyDatalinkID = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DatalinkID", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<DatalinkFullIDMsg> KeyDatalinkFullID = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DatalinkFullID", new DJIValueConverter<DatalinkFullIDMsg>(DatalinkFullIDMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<String>> KeyDatalinkFullIDList = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "DatalinkFullIDList", new SingleValueConverter<List, DatalinkFullIDListMsg>(List.class, DatalinkFullIDListMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyFirmwareBuriedPointData = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FirmwareBuriedPointData", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStartFirmwareBuriedDataTransfer = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StartFirmwareBuriedDataTransfer", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, Boolean> KeyPingDJIComponent = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "PingDJIComponent", EmptyValueConverter.converter, SingleValueConverter.BooleanConverter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<DJIComponentParam, EmptyMsg> KeyPingCertainDJIComponent = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "PingCertainDJIComponent", new DJIValueConverter<DJIComponentParam>(DJIComponentParam.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EagleTestParam, EmptyMsg> KeyEagleTestCmd = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "EagleTestCmd", new DJIValueConverter<EagleTestParam>(EagleTestParam.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<String> KeySerialNumber = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SerialNumber", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyFirmwareVersion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FirmwareVersion", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsMassProduct = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsMassProduct", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<ProductType> KeyProductType = new DJIKeyInfo<ProductType>(componentType.value(), subComponentType.value(), "ProductType", new SingleValueConverter<ProductType, ProductTypeMsg>(ProductType.class, ProductTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<ProductType> KeyInternalProductType = new DJIKeyInfo<ProductType>(componentType.value(), subComponentType.value(), "InternalProductType", new SingleValueConverter<ProductType, ProductTypeMsg>(ProductType.class, ProductTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<ProductEdition> KeyProductEdition = new DJIKeyInfo<ProductEdition>(componentType.value(), subComponentType.value(), "ProductEdition", new SingleValueConverter<ProductEdition, ProductEditionMsg>(ProductEdition.class, ProductEditionMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<NotSupportAppInfoMsg> KeyNotSupportAppInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "NotSupportAppInfo", new DJIValueConverter<NotSupportAppInfoMsg>(NotSupportAppInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyCECertificationInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CECertificationInfo", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<NPIBuriedDataProviderType, List<TLVData>> KeyRequireNPIBuriedData = new DJIActionKeyInfo<NPIBuriedDataProviderType, List>(componentType.value(), subComponentType.value(), "RequireNPIBuriedData", new SingleValueConverter<NPIBuriedDataProviderType, NPIBuriedDataProviderTypeMsg>(NPIBuriedDataProviderType.class, NPIBuriedDataProviderTypeMsg.class), new SingleValueConverter<List, NPIBuriedDataMsg>(List.class, NPIBuriedDataMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<List<NPIBuriedDataProviderTypeMsg>> KeyNPIBuriedDataProviderRange = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "NPIBuriedDataProviderRange", new SingleValueConverter<List, NPIBuriedDataProviderRange>(List.class, NPIBuriedDataProviderRange.class)).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<PowerControlAction, EmptyMsg> KeyPowerControl = new DJIActionKeyInfo<PowerControlAction, EmptyMsg>(componentType.value(), subComponentType.value(), "PowerControl", new SingleValueConverter<PowerControlAction, PowerControlParam>(PowerControlAction.class, PowerControlParam.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<DataLinkType> KeyDataLinkType = new DJIKeyInfo<DataLinkType>(componentType.value(), subComponentType.value(), "DataLinkType", new SingleValueConverter<DataLinkType, DataLinkTypeMsg>(DataLinkType.class, DataLinkTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyUnsupportedProductConnected = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UnsupportedProductConnected", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<CameraComponentInfo>> KeyProductCameraCOverview = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "ProductCameraCOverview", new SingleValueConverter<List, CameraComponentInfoMsg>(List.class, CameraComponentInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("ProductCameraOverview");
    public static final DJIKeyInfo<List<GimbalComponentInfo>> KeyProductGimbalCOverview = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "ProductGimbalCOverview", new SingleValueConverter<List, GimbalComponentInfoMsg>(List.class, GimbalComponentInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("ProductGimbalOverview");
    public static final DJIKeyInfo<List<EportPayloadInfo>> KeyMultiPayloadOverview = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "MultiPayloadOverview", new SingleValueConverter<List, EportPayloadInfoMsg>(List.class, EportPayloadInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<RadarComponentInfo>> KeyProductRadarOverview = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "ProductRadarOverview", new SingleValueConverter<List, RadarComponentInfoMsg>(List.class, RadarComponentInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<RelayComponentInfo>> KeyProductRelayOverview = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "ProductRelayOverview", new SingleValueConverter<List, RelayComponentInfoMsg>(List.class, RelayComponentInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CareStatusMsg> KeyCareStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CareStatus", new DJIValueConverter<CareStatusMsg>(CareStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<UnmatchedBindInfo> KeyCareUnmatchedBindInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CareUnmatchedBindInfo", new DJIValueConverter<UnmatchedBindInfo>(UnmatchedBindInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<CareBindInfo, EmptyMsg> KeyVerifyLost = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "VerifyLost", new DJIValueConverter<CareBindInfo>(CareBindInfo.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<CareBindInfo> KeyNeedChangeBind = new DJIKeyInfo(componentType.value(), subComponentType.value(), "NeedChangeBind", new DJIValueConverter<CareBindInfo>(CareBindInfo.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CareSupportedInfoMsg> KeyCareSupportedInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CareSupportedInfo", new DJIValueConverter<CareSupportedInfoMsg>(CareSupportedInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyProductUUID = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ProductUUID", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<StreamHubLiveChannelInformation>> KeyStreamHubLiveChannelInformation = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "StreamHubLiveChannelInformation", new SingleValueConverter<List, StreamHubLiveChannelInformationMsg>(List.class, StreamHubLiveChannelInformationMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<MRTCRegisterEvent> KeyMRTCRegisterEvent = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MRTCRegisterEvent", new DJIValueConverter<MRTCRegisterEvent>(MRTCRegisterEvent.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<MRTCPlayEvent>> KeyMRTCPlayEvent = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "MRTCPlayEvent", new SingleValueConverter<List, MRTCPlayEventMsg>(List.class, MRTCPlayEventMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<MRTCVideoParamEvent>> KeyMRTCVideoParamEvent = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "MRTCVideoParamEvent", new SingleValueConverter<List, MRTCVideoParamEventMsg>(List.class, MRTCVideoParamEventMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<MRTCLiveStatusEvent>> KeyMRTCLiveStatusEvent = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "MRTCLiveStatusEvent", new SingleValueConverter<List, MRTCLiveStatusEventMsg>(List.class, MRTCLiveStatusEventMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<StreamHubLiveOptionGetRemainingMsg, MRTCOptionSetVideoAttributeMsg> KeyGetStreamHubLiveOption = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "GetStreamHubLiveOption", new DJIValueConverter<StreamHubLiveOptionGetRemainingMsg>(StreamHubLiveOptionGetRemainingMsg.class), new DJIValueConverter<MRTCOptionSetVideoAttributeMsg>(MRTCOptionSetVideoAttributeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<StreamHubLiveOptionSetRemainingMsg> KeySetStreamHubLiveOption = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SetStreamHubLiveOption", new DJIValueConverter<StreamHubLiveOptionSetRemainingMsg>(StreamHubLiveOptionSetRemainingMsg.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyWiFiStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "WiFiStatus", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<LiveState> KeyStreamHubLiveStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "StreamHubLiveStatus", new DJIValueConverter<LiveState>(LiveState.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, List<DatalinkMonitorRegistResult>> KeyDatalinkMonitorRegistByJsonFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "DatalinkMonitorRegistByJsonFile", SingleValueConverter.StringConverter, new SingleValueConverter<List, DatalinkMonitorRegistResults>(List.class, DatalinkMonitorRegistResults.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, String> KeyForceGetSerialNumber = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ForceGetSerialNumber", EmptyValueConverter.converter, SingleValueConverter.StringConverter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<DeviceRebootTimeInfo> KeyDeviceRebootTime = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DeviceRebootTime", new DJIValueConverter<DeviceRebootTimeInfo>(DeviceRebootTimeInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyTemperatureTestEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "TemperatureTestEnable", SingleValueConverter.BooleanConverter).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyUpdateDroneBlacklist = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "UpdateDroneBlacklist", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<TemperatureTestInfo> KeyTemperatureTestInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "TemperatureTestInfo", new DJIValueConverter<TemperatureTestInfo>(TemperatureTestInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyFlightNumWithoutInternet = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FlightNumWithoutInternet", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyLogDescription = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LogDescription", SingleValueConverter.StringConverter).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<ProductFirmwareSupportInfo> KeyProductFirmwareSupportInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ProductFirmwareSupportInfo", new DJIValueConverter<ProductFirmwareSupportInfo>(ProductFirmwareSupportInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<PSDKComponentInfo>> KeyProductPSDKOverview = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "ProductPSDKOverview", new SingleValueConverter<List, PSDKComponentInfoMsg>(List.class, PSDKComponentInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<AIBoxInfo>> KeyProductAIBoxOverview = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "ProductAIBoxOverview", new SingleValueConverter<List, AIBoxInfoListMsg>(List.class, AIBoxInfoListMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyOidUploadEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "OidUploadEnable", SingleValueConverter.BooleanConverter).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyOidUploadSimulatorEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "OidUploadSimulatorEnable", SingleValueConverter.BooleanConverter).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<PayloadSet> KeyCurrentPayloadSet = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CurrentPayloadSet", new DJIValueConverter<PayloadSet>(PayloadSet.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyDeviceID = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DeviceID", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyConnection = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Connection", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyForceUpdateCacheValue = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ForceUpdateCacheValue", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileStatus> KeyCalibrationFileStatus = new DJIKeyInfo<CalibrationFileStatus>(componentType.value(), subComponentType.value(), "CalibrationFileStatus", new SingleValueConverter<CalibrationFileStatus, CalibrationFileStatusMsg>(CalibrationFileStatus.class, CalibrationFileStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileUpdatingInfo> KeyCalibrationFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CalibrationFileUpdatingInfo", new DJIValueConverter<CalibrationFileUpdatingInfo>(CalibrationFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyUpdateCalibrationFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "UpdateCalibrationFile", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<UpgradeNotifyInfo> KeyUpgradeNotifyInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UpgradeNotifyInfo", new DJIValueConverter<UpgradeNotifyInfo>(UpgradeNotifyInfo.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyEnforceUpgradeEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "EnforceUpgradeEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsInEnforceUpgradeStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsInEnforceUpgradeStatus", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsDirectDevice = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsDirectDevice", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CommonFileUpdatingInfo> KeyCommonFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CommonFileUpdatingInfo", new DJIValueConverter<CommonFileUpdatingInfo>(CommonFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyStartCommonFileUpdate = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StartCommonFileUpdate", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopCommonFileUpdate = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopCommonFileUpdate", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticMode = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticMode", new DJIValueConverter<SelfDiagnosticInfo>(SelfDiagnosticInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticRequestInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticRequest = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticRequest", new DJIValueConverter<SelfDiagnosticRequestInfo>(SelfDiagnosticRequestInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode> KeySelfDiagnosticCancel = new DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode>(componentType.value(), subComponentType.value(), "SelfDiagnosticCancel", EmptyValueConverter.converter, new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<SelfDiagnosticProgress> KeySelfDiagnosticStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticStatus", new DJIValueConverter<SelfDiagnosticProgress>(SelfDiagnosticProgress.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticCapability, SelfDiagnosticPartsInfo> KeySelfDiagnosticParts = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticParts", new SingleValueConverter<SelfDiagnosticCapability, SelfDiagnosticCapabilityMsg>(SelfDiagnosticCapability.class, SelfDiagnosticCapabilityMsg.class), new DJIValueConverter<SelfDiagnosticPartsInfo>(SelfDiagnosticPartsInfo.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);

    static {
        keyList.add(KeyDatalinkID);
        keyList.add(KeyDatalinkFullID);
        keyList.add(KeyDatalinkFullIDList);
        keyList.add(KeyFirmwareBuriedPointData);
        keyList.add(KeyStartFirmwareBuriedDataTransfer);
        keyList.add(KeyPingDJIComponent);
        keyList.add(KeyPingCertainDJIComponent);
        keyList.add(KeyEagleTestCmd);
        keyList.add(KeySerialNumber);
        keyList.add(KeyFirmwareVersion);
        keyList.add(KeyIsMassProduct);
        keyList.add(KeyProductType);
        keyList.add(KeyInternalProductType);
        keyList.add(KeyProductEdition);
        keyList.add(KeyNotSupportAppInfo);
        keyList.add(KeyCECertificationInfo);
        keyList.add(KeyRequireNPIBuriedData);
        keyList.add(KeyNPIBuriedDataProviderRange);
        keyList.add(KeyPowerControl);
        keyList.add(KeyDataLinkType);
        keyList.add(KeyUnsupportedProductConnected);
        keyList.add(KeyProductCameraCOverview);
        keyList.add(KeyProductGimbalCOverview);
        keyList.add(KeyMultiPayloadOverview);
        keyList.add(KeyProductRadarOverview);
        keyList.add(KeyProductRelayOverview);
        keyList.add(KeyCareStatus);
        keyList.add(KeyCareUnmatchedBindInfo);
        keyList.add(KeyVerifyLost);
        keyList.add(KeyNeedChangeBind);
        keyList.add(KeyCareSupportedInfo);
        keyList.add(KeyProductUUID);
        keyList.add(KeyStreamHubLiveChannelInformation);
        keyList.add(KeyMRTCRegisterEvent);
        keyList.add(KeyMRTCPlayEvent);
        keyList.add(KeyMRTCVideoParamEvent);
        keyList.add(KeyMRTCLiveStatusEvent);
        keyList.add(KeyGetStreamHubLiveOption);
        keyList.add(KeySetStreamHubLiveOption);
        keyList.add(KeyWiFiStatus);
        keyList.add(KeyStreamHubLiveStatus);
        keyList.add(KeyDatalinkMonitorRegistByJsonFile);
        keyList.add(KeyForceGetSerialNumber);
        keyList.add(KeyDeviceRebootTime);
        keyList.add(KeyTemperatureTestEnable);
        keyList.add(KeyUpdateDroneBlacklist);
        keyList.add(KeyTemperatureTestInfo);
        keyList.add(KeyFlightNumWithoutInternet);
        keyList.add(KeyLogDescription);
        keyList.add(KeyProductFirmwareSupportInfo);
        keyList.add(KeyProductPSDKOverview);
        keyList.add(KeyProductAIBoxOverview);
        keyList.add(KeyOidUploadEnable);
        keyList.add(KeyOidUploadSimulatorEnable);
        keyList.add(KeyCurrentPayloadSet);
        keyList.add(KeyDeviceID);
        keyList.add(KeyConnection);
        keyList.add(KeyForceUpdateCacheValue);
        keyList.add(KeyCalibrationFileStatus);
        keyList.add(KeyCalibrationFileUpdatingInfo);
        keyList.add(KeyUpdateCalibrationFile);
        keyList.add(KeyUpgradeNotifyInfo);
        keyList.add(KeyEnforceUpgradeEnable);
        keyList.add(KeyIsInEnforceUpgradeStatus);
        keyList.add(KeyIsDirectDevice);
        keyList.add(KeyCommonFileUpdatingInfo);
        keyList.add(KeyStartCommonFileUpdate);
        keyList.add(KeyStopCommonFileUpdate);
        keyList.add(KeySelfDiagnosticMode);
        keyList.add(KeySelfDiagnosticRequest);
        keyList.add(KeySelfDiagnosticCancel);
        keyList.add(KeySelfDiagnosticStatus);
        keyList.add(KeySelfDiagnosticParts);
    }
}

