/*
 * Decompiled with CFR 0.152.
 */
package dji.sdk.keyvalue.key;

import dji.sdk.keyvalue.converter.BufferConverter;
import dji.sdk.keyvalue.converter.DJIValueConverter;
import dji.sdk.keyvalue.converter.EmptyValueConverter;
import dji.sdk.keyvalue.converter.SingleValueConverter;
import dji.sdk.keyvalue.key.ComponentType;
import dji.sdk.keyvalue.key.DJIActionKeyInfo;
import dji.sdk.keyvalue.key.DJIKeyInfo;
import dji.sdk.keyvalue.key.SubComponentType;
import dji.sdk.keyvalue.value.airlink.AirlinkBandwidthRangeMsg;
import dji.sdk.keyvalue.value.airlink.Bandwidth;
import dji.sdk.keyvalue.value.common.CalibrationFileStatus;
import dji.sdk.keyvalue.value.common.CalibrationFileStatusMsg;
import dji.sdk.keyvalue.value.common.CalibrationFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.CareBindInfo;
import dji.sdk.keyvalue.value.common.CommonFileUpdatingInfo;
import dji.sdk.keyvalue.value.common.DeviceSecretResult;
import dji.sdk.keyvalue.value.common.EmptyMsg;
import dji.sdk.keyvalue.value.common.FileDownloadInfoMsg;
import dji.sdk.keyvalue.value.common.FileDownloadInputMsg;
import dji.sdk.keyvalue.value.common.LocationCoordinate2D;
import dji.sdk.keyvalue.value.common.LocationCoordinate3D;
import dji.sdk.keyvalue.value.common.MultiControlAuthorityType;
import dji.sdk.keyvalue.value.common.MultiControlChannel;
import dji.sdk.keyvalue.value.common.MultiControlLockAuthorityInfo;
import dji.sdk.keyvalue.value.common.RCAuthorityModes;
import dji.sdk.keyvalue.value.common.RelayProductTypeListMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapability;
import dji.sdk.keyvalue.value.common.SelfDiagnosticCapabilityMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCode;
import dji.sdk.keyvalue.value.common.SelfDiagnosticErrorCodeMsg;
import dji.sdk.keyvalue.value.common.SelfDiagnosticInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticPartsInfo;
import dji.sdk.keyvalue.value.common.SelfDiagnosticProgress;
import dji.sdk.keyvalue.value.common.SelfDiagnosticRequestInfo;
import dji.sdk.keyvalue.value.common.UpgradeNotifyInfo;
import dji.sdk.keyvalue.value.common.XYZ;
import dji.sdk.keyvalue.value.lidar.LidarPointCloudPredictionInputMsg;
import dji.sdk.keyvalue.value.lidar.LidarPointCloudPredictionOutputMsg;
import dji.sdk.keyvalue.value.product.DatalinkFullIDListMsg;
import dji.sdk.keyvalue.value.remotecontroller.AMTTestMsg;
import dji.sdk.keyvalue.value.remotecontroller.AlternateLandingPoint;
import dji.sdk.keyvalue.value.remotecontroller.BatteryInfo;
import dji.sdk.keyvalue.value.remotecontroller.CommonNetworkPrivateKeyCheckMsg;
import dji.sdk.keyvalue.value.remotecontroller.CommonNetworkSignMsg;
import dji.sdk.keyvalue.value.remotecontroller.CommonNetworkSignRsp;
import dji.sdk.keyvalue.value.remotecontroller.ConnectRelayMsg;
import dji.sdk.keyvalue.value.remotecontroller.ConnectedDeviceInfo;
import dji.sdk.keyvalue.value.remotecontroller.ConnectedDeviceInfos;
import dji.sdk.keyvalue.value.remotecontroller.ConnectedExternalDevice;
import dji.sdk.keyvalue.value.remotecontroller.CurrentRelayInfoMsg;
import dji.sdk.keyvalue.value.remotecontroller.CustomBtnFunctionInfo;
import dji.sdk.keyvalue.value.remotecontroller.DeviceConfigActionReqMsg;
import dji.sdk.keyvalue.value.remotecontroller.DeviceConfigActionRspMsg;
import dji.sdk.keyvalue.value.remotecontroller.DroneNestDeploymentEvaluation;
import dji.sdk.keyvalue.value.remotecontroller.DroneNestDeploymentEvaluationMsg;
import dji.sdk.keyvalue.value.remotecontroller.DroneNestDeploymentMode;
import dji.sdk.keyvalue.value.remotecontroller.DroneNestDeploymentModeMsg;
import dji.sdk.keyvalue.value.remotecontroller.DroneNestMaintainInfo;
import dji.sdk.keyvalue.value.remotecontroller.DroneNestMoveMsg;
import dji.sdk.keyvalue.value.remotecontroller.DroneNestStatusMsg;
import dji.sdk.keyvalue.value.remotecontroller.ExternalDeviceType;
import dji.sdk.keyvalue.value.remotecontroller.FileUpdatingInfoMsg;
import dji.sdk.keyvalue.value.remotecontroller.FirmwareMatchType;
import dji.sdk.keyvalue.value.remotecontroller.FirmwareMatchTypeMsg;
import dji.sdk.keyvalue.value.remotecontroller.FirmwareSupportInfo;
import dji.sdk.keyvalue.value.remotecontroller.FiveDimensionPressedStatus;
import dji.sdk.keyvalue.value.remotecontroller.FpvAuthStatus;
import dji.sdk.keyvalue.value.remotecontroller.HDVTSDRMode;
import dji.sdk.keyvalue.value.remotecontroller.HDVTSDRModeMsg;
import dji.sdk.keyvalue.value.remotecontroller.LockShutterAndRecordButtonParam;
import dji.sdk.keyvalue.value.remotecontroller.MGMultiDevicesConnectStatusMsg;
import dji.sdk.keyvalue.value.remotecontroller.MGMultiDevicesFpvSwitchMsg;
import dji.sdk.keyvalue.value.remotecontroller.MGMultiDevicesWorkModeMsg;
import dji.sdk.keyvalue.value.remotecontroller.MGMultiDevicesWorkStatusMsg;
import dji.sdk.keyvalue.value.remotecontroller.MaintainInfo;
import dji.sdk.keyvalue.value.remotecontroller.MaintainInfoType;
import dji.sdk.keyvalue.value.remotecontroller.MaintainInfoTypeMsg;
import dji.sdk.keyvalue.value.remotecontroller.MissionCenterDeployErrorCode;
import dji.sdk.keyvalue.value.remotecontroller.MissionCenterDeployErrorCodeMsg;
import dji.sdk.keyvalue.value.remotecontroller.MultiControlChannelInfo;
import dji.sdk.keyvalue.value.remotecontroller.MultiControlFlightControlAuthorityOwnerInfo;
import dji.sdk.keyvalue.value.remotecontroller.MultiControlLostControlInfo;
import dji.sdk.keyvalue.value.remotecontroller.MultiControlStatusInfo;
import dji.sdk.keyvalue.value.remotecontroller.MultiRCAuthOwnerMsg;
import dji.sdk.keyvalue.value.remotecontroller.MultiRCExclusiveTaskAuthOwnerMsg;
import dji.sdk.keyvalue.value.remotecontroller.MultiRcGimbalsControlAuthOwnerMsg;
import dji.sdk.keyvalue.value.remotecontroller.MultiRcSyncDataMsg;
import dji.sdk.keyvalue.value.remotecontroller.PairingState;
import dji.sdk.keyvalue.value.remotecontroller.RCFlightModeSwitch;
import dji.sdk.keyvalue.value.remotecontroller.RCFlightModeSwitchMsg;
import dji.sdk.keyvalue.value.remotecontroller.RCMachineModeMsg;
import dji.sdk.keyvalue.value.remotecontroller.RCMode;
import dji.sdk.keyvalue.value.remotecontroller.RCStickChannelModeInfo;
import dji.sdk.keyvalue.value.remotecontroller.RCStickMode;
import dji.sdk.keyvalue.value.remotecontroller.RCStickModeMsg;
import dji.sdk.keyvalue.value.remotecontroller.RCTransformationSwitchState;
import dji.sdk.keyvalue.value.remotecontroller.RCTransformationSwitchStateMsg;
import dji.sdk.keyvalue.value.remotecontroller.RCUSBMode;
import dji.sdk.keyvalue.value.remotecontroller.RCUSBModeMsg;
import dji.sdk.keyvalue.value.remotecontroller.RCWheellModeInfo;
import dji.sdk.keyvalue.value.remotecontroller.RcAppWorkStageMsg;
import dji.sdk.keyvalue.value.remotecontroller.RcButtonActionMsg;
import dji.sdk.keyvalue.value.remotecontroller.RcCalibrateState;
import dji.sdk.keyvalue.value.remotecontroller.RcCalibrateStateValue;
import dji.sdk.keyvalue.value.remotecontroller.RcChargeMobileMode;
import dji.sdk.keyvalue.value.remotecontroller.RcChargeMobileModeMsg;
import dji.sdk.keyvalue.value.remotecontroller.RcCheckStatusMsg;
import dji.sdk.keyvalue.value.remotecontroller.RcControllerModeMsg;
import dji.sdk.keyvalue.value.remotecontroller.RcCurrentPairState;
import dji.sdk.keyvalue.value.remotecontroller.RcCustomButtonEvent;
import dji.sdk.keyvalue.value.remotecontroller.RcCustomButtonHardwareStatus;
import dji.sdk.keyvalue.value.remotecontroller.RcCustomizableButton;
import dji.sdk.keyvalue.value.remotecontroller.RcCustomizableButtonMsg;
import dji.sdk.keyvalue.value.remotecontroller.RcFirmwareInfo;
import dji.sdk.keyvalue.value.remotecontroller.RcFirmwareMsg;
import dji.sdk.keyvalue.value.remotecontroller.RcFirmwareType;
import dji.sdk.keyvalue.value.remotecontroller.RcGPSInfo;
import dji.sdk.keyvalue.value.remotecontroller.RcMultiButtonActionConfigMsg;
import dji.sdk.keyvalue.value.remotecontroller.RcMultiDeviceAircraftState;
import dji.sdk.keyvalue.value.remotecontroller.RcMultiDeviceBsAircraftState;
import dji.sdk.keyvalue.value.remotecontroller.RcMultiDeviceBsStates;
import dji.sdk.keyvalue.value.remotecontroller.RcMultiDeviceMakePairRsp;
import dji.sdk.keyvalue.value.remotecontroller.RcMultiDeviceMakePairValue;
import dji.sdk.keyvalue.value.remotecontroller.RcMultiDeviceSelectTargetRsp;
import dji.sdk.keyvalue.value.remotecontroller.RcMultiDeviceSelectTargetValue;
import dji.sdk.keyvalue.value.remotecontroller.RcMultiDevices50xMakePairValue;
import dji.sdk.keyvalue.value.remotecontroller.RcPairingStateMsg;
import dji.sdk.keyvalue.value.remotecontroller.RcRole;
import dji.sdk.keyvalue.value.remotecontroller.RcRoleListInfo;
import dji.sdk.keyvalue.value.remotecontroller.RcRoleMsg;
import dji.sdk.keyvalue.value.remotecontroller.RcSoftSwitchMode;
import dji.sdk.keyvalue.value.remotecontroller.RcSoftSwitchModeMsg;
import dji.sdk.keyvalue.value.remotecontroller.RcStickCalibrationStatusMsg;
import dji.sdk.keyvalue.value.remotecontroller.RcUnitAndLanguageMsg;
import dji.sdk.keyvalue.value.remotecontroller.RelayBinSwitchStatusMsg;
import dji.sdk.keyvalue.value.remotecontroller.RelayBroadcastPeriodMsg;
import dji.sdk.keyvalue.value.remotecontroller.RelayConnectionResultMsg;
import dji.sdk.keyvalue.value.remotecontroller.RelaySSIDMsg;
import dji.sdk.keyvalue.value.remotecontroller.RelaySearchCtrlMsg;
import dji.sdk.keyvalue.value.remotecontroller.RemoteControllerType;
import dji.sdk.keyvalue.value.remotecontroller.RemoteControllerTypeMsg;
import dji.sdk.keyvalue.value.remotecontroller.RequestGimbalControlRightMsg;
import dji.sdk.keyvalue.value.remotecontroller.RequireIFrameMsg;
import dji.sdk.keyvalue.value.remotecontroller.ResponseGimbalControlMsg;
import dji.sdk.keyvalue.value.remotecontroller.ScannedRelaysMsg;
import dji.sdk.keyvalue.value.remotecontroller.SdrParameterMsg;
import dji.sdk.keyvalue.value.remotecontroller.ShardFileUploadInfo;
import dji.sdk.keyvalue.value.remotecontroller.UavLockFailReason;
import dji.sdk.keyvalue.value.remotecontroller.UavLockFailReasonMsg;
import dji.sdk.keyvalue.value.remotecontroller.UsbDeviceAttachedInfo;
import dji.sdk.keyvalue.value.remotecontroller.UserImprovementPlanMode;
import dji.sdk.keyvalue.value.remotecontroller.UserImprovementPlanMsg;
import dji.sdk.keyvalue.value.remotecontroller.V1PushCMDSets;
import java.util.ArrayList;
import java.util.List;

public class DJIRemoteControllerKey {
    protected static final List<DJIKeyInfo<?>> keyList = new ArrayList();
    private static final ComponentType componentType = ComponentType.REMOTECONTROLLER;
    private static final SubComponentType subComponentType = SubComponentType.IGNORE;
    public static final DJIKeyInfo<String> KeySerialNumber = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SerialNumber", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyFirmwareVersion = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FirmwareVersion", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<ConnectedDeviceInfo>> KeyConnectionDeviceInfo = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "ConnectionDeviceInfo", new SingleValueConverter<List, ConnectedDeviceInfos>(List.class, ConnectedDeviceInfos.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RemoteControllerType> KeyRemoteControllerType = new DJIKeyInfo<RemoteControllerType>(componentType.value(), subComponentType.value(), "RemoteControllerType", new SingleValueConverter<RemoteControllerType, RemoteControllerTypeMsg>(RemoteControllerType.class, RemoteControllerTypeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RCUSBMode> KeyRCUSBMode = new DJIKeyInfo<RCUSBMode>(componentType.value(), subComponentType.value(), "RCUSBMode", new SingleValueConverter<RCUSBMode, RCUSBModeMsg>(RCUSBMode.class, RCUSBModeMsg.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<RcMultiDeviceMakePairValue, RcCurrentPairState> KeyRcMultiDeviceMakePair = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RcMultiDeviceMakePair", new DJIValueConverter<RcMultiDeviceMakePairValue>(RcMultiDeviceMakePairValue.class), new SingleValueConverter<RcCurrentPairState, RcMultiDeviceMakePairRsp>(RcCurrentPairState.class, RcMultiDeviceMakePairRsp.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<RcMultiDevices50xMakePairValue, RcCurrentPairState> KeyRcMultiDevices50xMakePair = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RcMultiDevices50xMakePair", new DJIValueConverter<RcMultiDevices50xMakePairValue>(RcMultiDevices50xMakePairValue.class), new SingleValueConverter<RcCurrentPairState, RcMultiDeviceMakePairRsp>(RcCurrentPairState.class, RcMultiDeviceMakePairRsp.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<RcMultiDeviceSelectTargetValue, RcMultiDeviceSelectTargetRsp> KeyRcMultiDeviceSelectTarget = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RcMultiDeviceSelectTarget", new DJIValueConverter<RcMultiDeviceSelectTargetValue>(RcMultiDeviceSelectTargetValue.class), new DJIValueConverter<RcMultiDeviceSelectTargetRsp>(RcMultiDeviceSelectTargetRsp.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<FirmwareMatchType> KeyFirmwareMatchType = new DJIKeyInfo<FirmwareMatchType>(componentType.value(), subComponentType.value(), "FirmwareMatchType", new SingleValueConverter<FirmwareMatchType, FirmwareMatchTypeMsg>(FirmwareMatchType.class, FirmwareMatchTypeMsg.class)).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyRequestPairUpgradePairing = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "RequestPairUpgradePairing", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyRequestPairing = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "RequestPairing", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false).setInnerIdentifier("RcRequestPairing");
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopPairing = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopPairing", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false).setInnerIdentifier("RcStopPairing");
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStartRelayPairing = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StartRelayPairing", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopRelayPairing = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopRelayPairing", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyRcPassword = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcPassword", SingleValueConverter.IntegerConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyReleaseGimbalControlRight = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "ReleaseGimbalControlRight", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyRequestLegacyGimbalControlRight = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "RequestLegacyGimbalControlRight", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<ResponseGimbalControlMsg, EmptyMsg> KeyResponseToRequestForGimbalControl = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ResponseToRequestForGimbalControl", new DJIValueConverter<ResponseGimbalControlMsg>(ResponseGimbalControlMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<RequestGimbalControlRightMsg> KeyGimbalControlRightRequest = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GimbalControlRightRequest", new DJIValueConverter<RequestGimbalControlRightMsg>(RequestGimbalControlRightMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyRcShakeMotor = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "RcShakeMotor", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<Boolean, EmptyMsg> KeyRcEnableRtk = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RcEnableRtk", SingleValueConverter.BooleanConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<Boolean, EmptyMsg> KeyRcEnable4G = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RcEnable4G", SingleValueConverter.BooleanConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<RcCalibrateState, RcCalibrateState> KeyRcCalibrateChannels = new DJIActionKeyInfo<RcCalibrateState, RcCalibrateState>(componentType.value(), subComponentType.value(), "RcCalibrateChannels", new SingleValueConverter<RcCalibrateState, RcCalibrateStateValue>(RcCalibrateState.class, RcCalibrateStateValue.class), new SingleValueConverter<RcCalibrateState, RcCalibrateStateValue>(RcCalibrateState.class, RcCalibrateStateValue.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<RcMultiDeviceAircraftState> KeyRcMultiDeviceAircraftState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcMultiDeviceAircraftState", new DJIValueConverter<RcMultiDeviceAircraftState>(RcMultiDeviceAircraftState.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<RcMultiDeviceBsAircraftState>> KeyRcMultiDeviceBsStates = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "RcMultiDeviceBsStates", new SingleValueConverter<List, RcMultiDeviceBsStates>(List.class, RcMultiDeviceBsStates.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyStickLeftHorizontal = new DJIKeyInfo(componentType.value(), subComponentType.value(), "StickLeftHorizontal", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RCStickLeftHorizontal");
    public static final DJIKeyInfo<Integer> KeyStickLeftVertical = new DJIKeyInfo(componentType.value(), subComponentType.value(), "StickLeftVertical", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RCStickLeftVertical");
    public static final DJIKeyInfo<Integer> KeyStickRightHorizontal = new DJIKeyInfo(componentType.value(), subComponentType.value(), "StickRightHorizontal", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RCStickRightHorizontal");
    public static final DJIKeyInfo<Integer> KeyStickRightVertical = new DJIKeyInfo(componentType.value(), subComponentType.value(), "StickRightVertical", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RCStickRightVertical");
    public static final DJIKeyInfo<Integer> KeyLeftDial = new DJIKeyInfo(componentType.value(), subComponentType.value(), "LeftDial", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RCLeftWheel");
    public static final DJIKeyInfo<Integer> KeyRightDial = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RightDial", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RCRightWheel");
    public static final DJIKeyInfo<Integer> KeyScrollWheel = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ScrollWheel", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RCRightNewWheel");
    public static final DJIKeyInfo<Boolean> KeyRCRightWheelButtonDown = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RCRightWheelButtonDown", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RCTransformationSwitchState> KeyRCTransformationSwitchState = new DJIKeyInfo<RCTransformationSwitchState>(componentType.value(), subComponentType.value(), "RCTransformationSwitchState", new SingleValueConverter<RCTransformationSwitchState, RCTransformationSwitchStateMsg>(RCTransformationSwitchState.class, RCTransformationSwitchStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RCFlightModeSwitch> KeyFlightModeSwitchState = new DJIKeyInfo<RCFlightModeSwitch>(componentType.value(), subComponentType.value(), "FlightModeSwitchState", new SingleValueConverter<RCFlightModeSwitch, RCFlightModeSwitchMsg>(RCFlightModeSwitch.class, RCFlightModeSwitchMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RCFlightModeSwitchState");
    public static final DJIKeyInfo<Boolean> KeyGoHomeButtonDown = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GoHomeButtonDown", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RCGohomeButtonDown");
    public static final DJIKeyInfo<Boolean> KeyRecordButtonDown = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RecordButtonDown", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RCRecordButtonDown");
    public static final DJIKeyInfo<Boolean> KeyShutterButtonDown = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ShutterButtonDown", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RCShutterButtonDown");
    public static final DJIKeyInfo<Boolean> KeyRCAuthLedButtonDown = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RCAuthLedButtonDown", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyRCShutterButtonLongPress = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RCShutterButtonLongPress", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyCustomButton1Down = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CustomButton1Down", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RCCustomButton1Down");
    public static final DJIKeyInfo<Boolean> KeyCustomButton2Down = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CustomButton2Down", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RCCustomButton2Down");
    public static final DJIKeyInfo<Boolean> KeyCustomButton3Down = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CustomButton3Down", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RCCustomButton3Down");
    public static final DJIKeyInfo<Boolean> KeyRCSwitchButtonDown = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RCSwitchButtonDown", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyRCCustomButton4Down = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RCCustomButton4Down", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyRCPlaybackButtonDown = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RCPlaybackButtonDown", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyPauseButtonDown = new DJIKeyInfo(componentType.value(), subComponentType.value(), "PauseButtonDown", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RCPauseButtonDown");
    public static final DJIKeyInfo<BatteryInfo> KeyBatteryInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryInfo", new DJIValueConverter<BatteryInfo>(BatteryInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RcParamChargeRemaining");
    public static final DJIKeyInfo<BatteryInfo> KeySecondBatteryInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SecondBatteryInfo", new DJIValueConverter<BatteryInfo>(BatteryInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("SecondRcParamChargeRemaining");
    public static final DJIKeyInfo<PairingState> KeyPairingStatus = new DJIKeyInfo<PairingState>(componentType.value(), subComponentType.value(), "PairingStatus", new SingleValueConverter<PairingState, RcPairingStateMsg>(PairingState.class, RcPairingStateMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RcPairingState");
    public static final DJIKeyInfo<RcControllerModeMsg> KeyRcControllerMode = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcControllerMode", new DJIValueConverter<RcControllerModeMsg>(RcControllerModeMsg.class)).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RcAppWorkStageMsg> KeyRcAppWorkStage = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcAppWorkStage", new DJIValueConverter<RcAppWorkStageMsg>(RcAppWorkStageMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RcCheckStatusMsg> KeyRcCheckStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcCheckStatus", new DJIValueConverter<RcCheckStatusMsg>(RcCheckStatusMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RcGPSInfo> KeyRcGPSInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcGPSInfo", new DJIValueConverter<RcGPSInfo>(RcGPSInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RcChargeMobileMode> KeyChargeMobileMode = new DJIKeyInfo<RcChargeMobileMode>(componentType.value(), subComponentType.value(), "ChargeMobileMode", new SingleValueConverter<RcChargeMobileMode, RcChargeMobileModeMsg>(RcChargeMobileMode.class, RcChargeMobileModeMsg.class)).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RcSoftSwitchMode> KeySoftSwitchMode = new DJIKeyInfo<RcSoftSwitchMode>(componentType.value(), subComponentType.value(), "SoftSwitchMode", new SingleValueConverter<RcSoftSwitchMode, RcSoftSwitchModeMsg>(RcSoftSwitchMode.class, RcSoftSwitchModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RcStickCalibrationStatusMsg> KeyRcLeftStickCalibrationStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcLeftStickCalibrationStatus", new DJIValueConverter<RcStickCalibrationStatusMsg>(RcStickCalibrationStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RcStickCalibrationStatusMsg> KeyRcRightStickCalibrationStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcRightStickCalibrationStatus", new DJIValueConverter<RcStickCalibrationStatusMsg>(RcStickCalibrationStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<RequireIFrameMsg, EmptyMsg> KeyRequireIFrame = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RequireIFrame", new DJIValueConverter<RequireIFrameMsg>(RequireIFrameMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<FiveDimensionPressedStatus> KeyFiveDimensionPressedStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FiveDimensionPressedStatus", new DJIValueConverter<FiveDimensionPressedStatus>(FiveDimensionPressedStatus.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RcFiveDimensionPressedStatus");
    public static final DJIKeyInfo<RcCustomButtonHardwareStatus> KeyRcHardwareState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcHardwareState", new DJIValueConverter<RcCustomButtonHardwareStatus>(RcCustomButtonHardwareStatus.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RcCustomButtonHardwareStatus> KeyMockRcHardwareState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MockRcHardwareState", new DJIValueConverter<RcCustomButtonHardwareStatus>(RcCustomButtonHardwareStatus.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RcUnitAndLanguageMsg> KeyRcUnitAndLanguage = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcUnitAndLanguage", new DJIValueConverter<RcUnitAndLanguageMsg>(RcUnitAndLanguageMsg.class)).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyRcCalibrateNumberOfSegment = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcCalibrateNumberOfSegment", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyRcCalibrateAAxisStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcCalibrateAAxisStatus", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyRcCalibrateBAxisStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcCalibrateBAxisStatus", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyRcCalibrateCAxisStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcCalibrateCAxisStatus", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyRcCalibrateDAxisStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcCalibrateDAxisStatus", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyRcCalibrateEAxisStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcCalibrateEAxisStatus", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyRcCalibrateFAxisStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcCalibrateFAxisStatus", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyRcCalibrateGAxisStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcCalibrateGAxisStatus", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyRcCalibrateHAxisStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcCalibrateHAxisStatus", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RcCustomButtonEvent> KeyRcButtonEventPro = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcButtonEventPro", new DJIValueConverter<RcCustomButtonEvent>(RcCustomButtonEvent.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<RcMultiButtonActionConfigMsg> KeyRcButtonConfig = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcButtonConfig", new DJIValueConverter<RcMultiButtonActionConfigMsg>(RcMultiButtonActionConfigMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<String>> KeyRcButtonProfileGroups = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "RcButtonProfileGroups", new SingleValueConverter<List, DatalinkFullIDListMsg>(List.class, DatalinkFullIDListMsg.class)).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyRcSelectButtonProfileGroup = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcSelectButtonProfileGroup", SingleValueConverter.StringConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<RcButtonActionMsg, EmptyMsg> KeyRcCustomButtonConfig = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RcCustomButtonConfig", new DJIValueConverter<RcButtonActionMsg>(RcButtonActionMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<RcCustomizableButton, RcButtonActionMsg> KeyRcFetchCustomButtonConfig = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RcFetchCustomButtonConfig", new SingleValueConverter<RcCustomizableButton, RcCustomizableButtonMsg>(RcCustomizableButton.class, RcCustomizableButtonMsg.class), new DJIValueConverter<RcButtonActionMsg>(RcButtonActionMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsStillLinked = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsStillLinked", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyRcResetButtonConfig = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "RcResetButtonConfig", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<MultiControlStatusInfo> KeyMultiControlStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MultiControlStatus", new DJIValueConverter<MultiControlStatusInfo>(MultiControlStatusInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("RcMultiStatus");
    public static final DJIKeyInfo<String> KeyRcRK3399SirialNumber = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcRK3399SirialNumber", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyBatteryBoxSerialNumber = new DJIKeyInfo(componentType.value(), subComponentType.value(), "BatteryBoxSerialNumber", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RCMode> KeyRcMachineMode = new DJIKeyInfo<RCMode>(componentType.value(), subComponentType.value(), "RcMachineMode", new SingleValueConverter<RCMode, RCMachineModeMsg>(RCMode.class, RCMachineModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<MultiControlChannelInfo>> KeyMultiControlGimbalAuthorityOwner = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "MultiControlGimbalAuthorityOwner", new SingleValueConverter<List, MultiRcGimbalsControlAuthOwnerMsg>(List.class, MultiRcGimbalsControlAuthOwnerMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("MultiRcGimbalsControlAuthOwner");
    public static final DJIActionKeyInfo<MultiControlChannel, EmptyMsg> KeyMultiControlRequestPairing = new DJIActionKeyInfo<MultiControlChannel, EmptyMsg>(componentType.value(), subComponentType.value(), "MultiControlRequestPairing", new SingleValueConverter<MultiControlChannel, MultiControlChannelInfo>(MultiControlChannel.class, MultiControlChannelInfo.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false).setInnerIdentifier("StartModePairing");
    public static final DJIKeyInfo<FpvAuthStatus> KeyFpvAuthStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FpvAuthStatus", new DJIValueConverter<FpvAuthStatus>(FpvAuthStatus.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyUavLockStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UavLockStatus", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<UavLockFailReason> KeyUavLockFailReason = new DJIKeyInfo<UavLockFailReason>(componentType.value(), subComponentType.value(), "UavLockFailReason", new SingleValueConverter<UavLockFailReason, UavLockFailReasonMsg>(UavLockFailReason.class, UavLockFailReasonMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<Integer> KeyMultiControlOnlineRcCount = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MultiControlOnlineRcCount", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("MultiRcOnlineRCCount");
    public static final DJIKeyInfo<Integer> KeyMultiControlOnlineAppCount = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MultiControlOnlineAppCount", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("MultiRcOnlineAPPCount");
    public static final DJIKeyInfo<Boolean> KeyRcMasterSlaveOpen = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcMasterSlaveOpen", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyMultiControlIsSupported = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MultiControlIsSupported", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("IsMasterSlaveModeV4Supported");
    public static final DJIKeyInfo<RCStickMode> KeySlaveRCStickMode = new DJIKeyInfo<RCStickMode>(componentType.value(), subComponentType.value(), "SlaveRCStickMode", new SingleValueConverter<RCStickMode, RCStickModeMsg>(RCStickMode.class, RCStickModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RCStickChannelModeInfo> KeySlaveRCStickChannelMode = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SlaveRCStickChannelMode", new DJIValueConverter<RCStickChannelModeInfo>(RCStickChannelModeInfo.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RCWheellModeInfo> KeySlaveRCSWheelMode = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SlaveRCSWheelMode", new DJIValueConverter<RCWheellModeInfo>(RCWheellModeInfo.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<List<MultiControlAuthorityType>, EmptyMsg> KeyMultiControlAuthorityObtain = new DJIActionKeyInfo<List, EmptyMsg>(componentType.value(), subComponentType.value(), "MultiControlAuthorityObtain", new SingleValueConverter<List, RCAuthorityModes>(List.class, RCAuthorityModes.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false).setInnerIdentifier("MultiRcControlAuthoritySurpass");
    public static final DJIActionKeyInfo<MultiControlLockAuthorityInfo, EmptyMsg> KeyMultiControlLockAuthority = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "MultiControlLockAuthority", new DJIValueConverter<MultiControlLockAuthorityInfo>(MultiControlLockAuthorityInfo.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false).setInnerIdentifier("MultiRcControlLockRight");
    public static final DJIKeyInfo<MultiRcSyncDataMsg> KeyMultiRcSyncData = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MultiRcSyncData", new DJIValueConverter<MultiRcSyncDataMsg>(MultiRcSyncDataMsg.class)).canGet(false).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<MultiControlFlightControlAuthorityOwnerInfo> KeyMultiControlFlightControlAuthorityOwner = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MultiControlFlightControlAuthorityOwner", new DJIValueConverter<MultiControlFlightControlAuthorityOwnerInfo>(MultiControlFlightControlAuthorityOwnerInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("MultiRCFlightControlAuthOwner");
    public static final DJIKeyInfo<Boolean> KeyMultiControlFlightControlAuthorityLockStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MultiControlFlightControlAuthorityLockStatus", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false).setInnerIdentifier("MultiRCFlightControlAuthLockState");
    public static final DJIKeyInfo<MultiControlLostControlInfo> KeyMultiControlLostControlNotice = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MultiControlLostControlNotice", new DJIValueConverter<MultiControlLostControlInfo>(MultiControlLostControlInfo.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true).setInnerIdentifier("MultiRcLostNotice");
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyMultiControlExecuteFailSafeActionWhenLostControl = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "MultiControlExecuteFailSafeActionWhenLostControl", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false).setInnerIdentifier("MultiRcExecuteAircraftLostLogic");
    public static final DJIKeyInfo<MultiRCAuthOwnerMsg> KeyMultiRCBackgroundDownloadAuthOwner = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MultiRCBackgroundDownloadAuthOwner", new DJIValueConverter<MultiRCAuthOwnerMsg>(MultiRCAuthOwnerMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<MultiRCExclusiveTaskAuthOwnerMsg> KeyMultiRCExclusiveTaskAuthOwner = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MultiRCExclusiveTaskAuthOwner", new DJIValueConverter<MultiRCExclusiveTaskAuthOwnerMsg>(MultiRCExclusiveTaskAuthOwnerMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<MultiRCAuthOwnerMsg, Boolean> KeySetBackgroundDownloadAuthOwner = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SetBackgroundDownloadAuthOwner", new DJIValueConverter<MultiRCAuthOwnerMsg>(MultiRCAuthOwnerMsg.class), SingleValueConverter.BooleanConverter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<MultiRCExclusiveTaskAuthOwnerMsg, Boolean> KeySetExclusiveTaskAuthOwner = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SetExclusiveTaskAuthOwner", new DJIValueConverter<MultiRCExclusiveTaskAuthOwnerMsg>(MultiRCExclusiveTaskAuthOwnerMsg.class), SingleValueConverter.BooleanConverter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<CustomBtnFunctionInfo> KeyCustomBtnFunction = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CustomBtnFunction", new DJIValueConverter<CustomBtnFunctionInfo>(CustomBtnFunctionInfo.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<FileDownloadInfoMsg> KeyFileDownloadInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FileDownloadInfo", new DJIValueConverter<FileDownloadInfoMsg>(FileDownloadInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<FileDownloadInputMsg, EmptyMsg> KeyDownloadFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "DownloadFile", new DJIValueConverter<FileDownloadInputMsg>(FileDownloadInputMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<FileUpdatingInfoMsg> KeyFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FileUpdatingInfo", new DJIValueConverter<FileUpdatingInfoMsg>(FileUpdatingInfoMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyUpdateFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "UpdateFile", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<DeviceConfigActionReqMsg, DeviceConfigActionRspMsg> KeyDeviceConfigAction = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "DeviceConfigAction", new DJIValueConverter<DeviceConfigActionReqMsg>(DeviceConfigActionReqMsg.class), new DJIValueConverter<DeviceConfigActionRspMsg>(DeviceConfigActionRspMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<LockShutterAndRecordButtonParam, EmptyMsg> KeyLockShutterAndRecordButton = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "LockShutterAndRecordButton", new DJIValueConverter<LockShutterAndRecordButtonParam>(LockShutterAndRecordButtonParam.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyRebootDevice = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "RebootDevice", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyProductSerialNumber = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ProductSerialNumber", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyRcUpgradeVoiceEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcUpgradeVoiceEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<CommonNetworkSignMsg, CommonNetworkSignRsp> KeyCommonNetworkSign = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "CommonNetworkSign", new DJIValueConverter<CommonNetworkSignMsg>(CommonNetworkSignMsg.class), new DJIValueConverter<CommonNetworkSignRsp>(CommonNetworkSignRsp.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<CommonNetworkPrivateKeyCheckMsg, Boolean> KeyCommonNetworkPrivateKeyCheck = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "CommonNetworkPrivateKeyCheck", new DJIValueConverter<CommonNetworkPrivateKeyCheckMsg>(CommonNetworkPrivateKeyCheckMsg.class), SingleValueConverter.BooleanConverter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyResetFactorySettings = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "ResetFactorySettings", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<AlternateLandingPoint> KeySetAlternateLandingPoint = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SetAlternateLandingPoint", new DJIValueConverter<AlternateLandingPoint>(AlternateLandingPoint.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<DroneNestStatusMsg> KeyDroneNestStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DroneNestStatus", new DJIValueConverter<DroneNestStatusMsg>(DroneNestStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<LocationCoordinate3D> KeyDroneNestPosition = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DroneNestPosition", new DJIValueConverter<LocationCoordinate3D>(LocationCoordinate3D.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<LocationCoordinate3D> KeyDroneNestAlternateLandingPointConfig = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DroneNestAlternateLandingPointConfig", new DJIValueConverter<LocationCoordinate3D>(LocationCoordinate3D.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<LocationCoordinate2D> KeyDroneNestHomeLocation = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DroneNestHomeLocation", new DJIValueConverter<LocationCoordinate2D>(LocationCoordinate2D.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<LocationCoordinate2D> KeyDroneNestAlternateLandingLocation = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DroneNestAlternateLandingLocation", new DJIValueConverter<LocationCoordinate2D>(LocationCoordinate2D.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Double> KeyDroneNestAlternateLandingGoHomeHeight = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DroneNestAlternateLandingGoHomeHeight", SingleValueConverter.DoubleConverter).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Long> KeySSSFN = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SSSFN", SingleValueConverter.LongConverter).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<Boolean, EmptyMsg> KeyRcSwitchPcMode = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RcSwitchPcMode", SingleValueConverter.BooleanConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<AMTTestMsg, EmptyMsg> KeyStartAMTTest = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StartAMTTest", new DJIValueConverter<AMTTestMsg>(AMTTestMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<String> KeyModule3399Version = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Module3399Version", SingleValueConverter.StringConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<RcFirmwareType, EmptyMsg> KeySwitchRcFirmware = new DJIActionKeyInfo<RcFirmwareType, EmptyMsg>(componentType.value(), subComponentType.value(), "SwitchRcFirmware", new SingleValueConverter<RcFirmwareType, RcFirmwareMsg>(RcFirmwareType.class, RcFirmwareMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<RcFirmwareInfo> KeyRcFirmwareInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RcFirmwareInfo", new DJIValueConverter<RcFirmwareInfo>(RcFirmwareInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<RcRole> KeyRcFirmwareRole = new DJIKeyInfo<RcRole>(componentType.value(), subComponentType.value(), "RcFirmwareRole", new SingleValueConverter<RcRole, RcRoleMsg>(RcRole.class, RcRoleMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<List<RcRoleMsg>> KeyRcFirmwareRoleList = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "RcFirmwareRoleList", new SingleValueConverter<List, RcRoleListInfo>(List.class, RcRoleListInfo.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<SdrParameterMsg> KeySdrParameter = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SdrParameter", new DJIValueConverter<SdrParameterMsg>(SdrParameterMsg.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<DeviceSecretResult> KeyDeviceSecret = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DeviceSecret", new DJIValueConverter<DeviceSecretResult>(DeviceSecretResult.class)).canGet(true).canSet(false).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<FirmwareSupportInfo> KeyFirmwareSupportInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "FirmwareSupportInfo", new DJIValueConverter<FirmwareSupportInfo>(FirmwareSupportInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<UsbDeviceAttachedInfo> KeyUsbDeviceAttached = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UsbDeviceAttached", new DJIValueConverter<UsbDeviceAttachedInfo>(UsbDeviceAttachedInfo.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, ExternalDeviceType> KeyCheckExternalDeviceConnected = new DJIActionKeyInfo<EmptyMsg, ExternalDeviceType>(componentType.value(), subComponentType.value(), "CheckExternalDeviceConnected", EmptyValueConverter.converter, new SingleValueConverter<ExternalDeviceType, ConnectedExternalDevice>(ExternalDeviceType.class, ConnectedExternalDevice.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyRecordShutterButtonEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RecordShutterButtonEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsLeftHorizontalStickNormal = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsLeftHorizontalStickNormal", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsLeftVerticalStickNormal = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsLeftVerticalStickNormal", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsRightHorizontalStickNormal = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsRightHorizontalStickNormal", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsRightVerticalStickNormal = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsRightVerticalStickNormal", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyTakePhotoButtonWhiteList = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "TakePhotoButtonWhiteList", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyAPPSilentlyUpgrade = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "APPSilentlyUpgrade", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<V1PushCMDSets> KeyV1CmdSetPushEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "V1CmdSetPushEnable", new DJIValueConverter<V1PushCMDSets>(V1PushCMDSets.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyGroundDeviceIdentity = new DJIKeyInfo(componentType.value(), subComponentType.value(), "GroundDeviceIdentity", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyUAVDeviceIdentity = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UAVDeviceIdentity", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<HDVTSDRMode> KeyHDVTSDRModeConfig = new DJIKeyInfo<HDVTSDRMode>(componentType.value(), subComponentType.value(), "HDVTSDRModeConfig", new SingleValueConverter<HDVTSDRMode, HDVTSDRModeMsg>(HDVTSDRMode.class, HDVTSDRModeMsg.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<CareBindInfo, EmptyMsg> KeyCameraVerifyLost = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "CameraVerifyLost", new DJIValueConverter<CareBindInfo>(CareBindInfo.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<List<Bandwidth>> KeyRCSupportedAirlinkBandwidthRange = new DJIKeyInfo<List>(componentType.value(), subComponentType.value(), "RCSupportedAirlinkBandwidthRange", new SingleValueConverter<List, AirlinkBandwidthRangeMsg>(List.class, AirlinkBandwidthRangeMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsSupportDualChannelAssistantLive = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsSupportDualChannelAssistantLive", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsMultiControllerSingleLiveView = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsMultiControllerSingleLiveView", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<RelaySSIDMsg, EmptyMsg> KeyUpdateRelaySSID = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "UpdateRelaySSID", new DJIValueConverter<RelaySSIDMsg>(RelaySSIDMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<byte[], Boolean> KeyUpdateRelayPasswd = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "UpdateRelayPasswd", BufferConverter.converter, SingleValueConverter.BooleanConverter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<RelayBroadcastPeriodMsg, EmptyMsg> KeyUpdateRelayBroadcastPeriod = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "UpdateRelayBroadcastPeriod", new DJIValueConverter<RelayBroadcastPeriodMsg>(RelayBroadcastPeriodMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<Boolean, EmptyMsg> KeyUpdateRelayHideBroadcast = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "UpdateRelayHideBroadcast", SingleValueConverter.BooleanConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<Boolean, EmptyMsg> KeyUpdateRelayEnableBroadcast = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "UpdateRelayEnableBroadcast", SingleValueConverter.BooleanConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, CurrentRelayInfoMsg> KeyObtainRelayInfo = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ObtainRelayInfo", EmptyValueConverter.converter, new DJIValueConverter<CurrentRelayInfoMsg>(CurrentRelayInfoMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<Boolean, EmptyMsg> KeyRelayScanEnable = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RelayScanEnable", SingleValueConverter.BooleanConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<ScannedRelaysMsg> KeyScannedRelays = new DJIKeyInfo(componentType.value(), subComponentType.value(), "ScannedRelays", new DJIValueConverter<ScannedRelaysMsg>(ScannedRelaysMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<ConnectRelayMsg, EmptyMsg> KeyConnectRelay = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ConnectRelay", new DJIValueConverter<ConnectRelayMsg>(ConnectRelayMsg.class), EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<RelayConnectionResultMsg> KeyRelayConnectionResult = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelayConnectionResult", new DJIValueConverter<RelayConnectionResultMsg>(RelayConnectionResultMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<RelayBinSwitchStatusMsg> KeyRelayBinSwitchStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelayBinSwitchStatus", new DJIValueConverter<RelayBinSwitchStatusMsg>(RelayBinSwitchStatusMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(true);
    public static final DJIKeyInfo<RelaySearchCtrlMsg> KeyRelaySearchCtrl = new DJIKeyInfo(componentType.value(), subComponentType.value(), "RelaySearchCtrl", new DJIValueConverter<RelaySearchCtrlMsg>(RelaySearchCtrlMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, byte[]> KeyRelayPasswdHash = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "RelayPasswdHash", SingleValueConverter.StringConverter, BufferConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyClearRelayPairInfo = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "ClearRelayPairInfo", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, RelayProductTypeListMsg> KeySupportRelayedByProductTypeRange = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SupportRelayedByProductTypeRange", EmptyValueConverter.converter, new DJIValueConverter<RelayProductTypeListMsg>(RelayProductTypeListMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<LidarPointCloudPredictionInputMsg, LidarPointCloudPredictionOutputMsg> KeyLidarPointCloudPrediction = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "LidarPointCloudPrediction", new DJIValueConverter<LidarPointCloudPredictionInputMsg>(LidarPointCloudPredictionInputMsg.class), new DJIValueConverter<LidarPointCloudPredictionOutputMsg>(LidarPointCloudPredictionOutputMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<MGMultiDevicesWorkModeMsg> KeyMGMultiDevicesWorkMode = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MGMultiDevicesWorkMode", new DJIValueConverter<MGMultiDevicesWorkModeMsg>(MGMultiDevicesWorkModeMsg.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<MGMultiDevicesFpvSwitchMsg> KeyMGMultiDevicesFpvSwitch = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MGMultiDevicesFpvSwitch", new DJIValueConverter<MGMultiDevicesFpvSwitchMsg>(MGMultiDevicesFpvSwitchMsg.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<MGMultiDevicesConnectStatusMsg> KeyMGMultiDevicesConnectStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MGMultiDevicesConnectStatus", new DJIValueConverter<MGMultiDevicesConnectStatusMsg>(MGMultiDevicesConnectStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<MGMultiDevicesWorkStatusMsg> KeyMGMultiDevicesWorkStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "MGMultiDevicesWorkStatus", new DJIValueConverter<MGMultiDevicesWorkStatusMsg>(MGMultiDevicesWorkStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<Boolean, EmptyMsg> KeyNotifyDroneTaskState = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "NotifyDroneTaskState", SingleValueConverter.BooleanConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<MaintainInfoType, MaintainInfo> KeyMaintainInfo = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "MaintainInfo", new SingleValueConverter<MaintainInfoType, MaintainInfoTypeMsg>(MaintainInfoType.class, MaintainInfoTypeMsg.class), new DJIValueConverter<MaintainInfo>(MaintainInfo.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<DroneNestMaintainInfo> KeyDroneNestSetMaintainData = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DroneNestSetMaintainData", new DJIValueConverter<DroneNestMaintainInfo>(DroneNestMaintainInfo.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<UserImprovementPlanMode> KeyDroneNestUserImprovementPlan = new DJIKeyInfo<UserImprovementPlanMode>(componentType.value(), subComponentType.value(), "DroneNestUserImprovementPlan", new SingleValueConverter<UserImprovementPlanMode, UserImprovementPlanMsg>(UserImprovementPlanMode.class, UserImprovementPlanMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<DroneNestDeploymentMode> KeyDroneNestDeploymentMode = new DJIKeyInfo<DroneNestDeploymentMode>(componentType.value(), subComponentType.value(), "DroneNestDeploymentMode", new SingleValueConverter<DroneNestDeploymentMode, DroneNestDeploymentModeMsg>(DroneNestDeploymentMode.class, DroneNestDeploymentModeMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<LocationCoordinate2D> KeyDroneNestSetRelativeAlternateLandingPoint = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DroneNestSetRelativeAlternateLandingPoint", new DJIValueConverter<LocationCoordinate2D>(LocationCoordinate2D.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<LocationCoordinate2D> KeyDroneNestGetRelativeAlternateLandingPoint = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DroneNestGetRelativeAlternateLandingPoint", new DJIValueConverter<LocationCoordinate2D>(LocationCoordinate2D.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<DroneNestMoveMsg> KeyDroneNestMoveState = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DroneNestMoveState", new DJIValueConverter<DroneNestMoveMsg>(DroneNestMoveMsg.class)).canGet(false).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<XYZ> KeyDroneNestDeparturePointOffset = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DroneNestDeparturePointOffset", new DJIValueConverter<XYZ>(XYZ.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<DroneNestDeploymentEvaluation> KeyDroneNestDeploymentEvaluation = new DJIKeyInfo<DroneNestDeploymentEvaluation>(componentType.value(), subComponentType.value(), "DroneNestDeploymentEvaluation", new SingleValueConverter<DroneNestDeploymentEvaluation, DroneNestDeploymentEvaluationMsg>(DroneNestDeploymentEvaluation.class, DroneNestDeploymentEvaluationMsg.class)).canGet(true).canSet(true).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<ShardFileUploadInfo, MissionCenterDeployErrorCode> KeyMissionCenterShardFileUpload = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "MissionCenterShardFileUpload", new DJIValueConverter<ShardFileUploadInfo>(ShardFileUploadInfo.class), new SingleValueConverter<MissionCenterDeployErrorCode, MissionCenterDeployErrorCodeMsg>(MissionCenterDeployErrorCode.class, MissionCenterDeployErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<String, MissionCenterDeployErrorCode> KeyMissionCenterShardFileDelete = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "MissionCenterShardFileDelete", SingleValueConverter.StringConverter, new SingleValueConverter<MissionCenterDeployErrorCode, MissionCenterDeployErrorCodeMsg>(MissionCenterDeployErrorCode.class, MissionCenterDeployErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<Integer> KeyDeviceID = new DJIKeyInfo(componentType.value(), subComponentType.value(), "DeviceID", SingleValueConverter.IntegerConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyConnection = new DJIKeyInfo(componentType.value(), subComponentType.value(), "Connection", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyForceUpdateCacheValue = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "ForceUpdateCacheValue", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileStatus> KeyCalibrationFileStatus = new DJIKeyInfo<CalibrationFileStatus>(componentType.value(), subComponentType.value(), "CalibrationFileStatus", new SingleValueConverter<CalibrationFileStatus, CalibrationFileStatusMsg>(CalibrationFileStatus.class, CalibrationFileStatusMsg.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CalibrationFileUpdatingInfo> KeyCalibrationFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CalibrationFileUpdatingInfo", new DJIValueConverter<CalibrationFileUpdatingInfo>(CalibrationFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyUpdateCalibrationFile = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "UpdateCalibrationFile", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<UpgradeNotifyInfo> KeyUpgradeNotifyInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "UpgradeNotifyInfo", new DJIValueConverter<UpgradeNotifyInfo>(UpgradeNotifyInfo.class)).canGet(false).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyEnforceUpgradeEnable = new DJIKeyInfo(componentType.value(), subComponentType.value(), "EnforceUpgradeEnable", SingleValueConverter.BooleanConverter).canGet(true).canSet(true).canListen(false).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsInEnforceUpgradeStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsInEnforceUpgradeStatus", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<Boolean> KeyIsDirectDevice = new DJIKeyInfo(componentType.value(), subComponentType.value(), "IsDirectDevice", SingleValueConverter.BooleanConverter).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIKeyInfo<CommonFileUpdatingInfo> KeyCommonFileUpdatingInfo = new DJIKeyInfo(componentType.value(), subComponentType.value(), "CommonFileUpdatingInfo", new DJIValueConverter<CommonFileUpdatingInfo>(CommonFileUpdatingInfo.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<String, EmptyMsg> KeyStartCommonFileUpdate = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "StartCommonFileUpdate", SingleValueConverter.StringConverter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, EmptyMsg> KeyStopCommonFileUpdate = new DJIActionKeyInfo<EmptyMsg, EmptyMsg>(componentType.value(), subComponentType.value(), "StopCommonFileUpdate", EmptyValueConverter.converter, EmptyValueConverter.converter).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticMode = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticMode", new DJIValueConverter<SelfDiagnosticInfo>(SelfDiagnosticInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticRequestInfo, SelfDiagnosticErrorCode> KeySelfDiagnosticRequest = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticRequest", new DJIValueConverter<SelfDiagnosticRequestInfo>(SelfDiagnosticRequestInfo.class), new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode> KeySelfDiagnosticCancel = new DJIActionKeyInfo<EmptyMsg, SelfDiagnosticErrorCode>(componentType.value(), subComponentType.value(), "SelfDiagnosticCancel", EmptyValueConverter.converter, new SingleValueConverter<SelfDiagnosticErrorCode, SelfDiagnosticErrorCodeMsg>(SelfDiagnosticErrorCode.class, SelfDiagnosticErrorCodeMsg.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);
    public static final DJIKeyInfo<SelfDiagnosticProgress> KeySelfDiagnosticStatus = new DJIKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticStatus", new DJIValueConverter<SelfDiagnosticProgress>(SelfDiagnosticProgress.class)).canGet(true).canSet(false).canListen(true).canPerformAction(false).setIsEvent(false);
    public static final DJIActionKeyInfo<SelfDiagnosticCapability, SelfDiagnosticPartsInfo> KeySelfDiagnosticParts = new DJIActionKeyInfo(componentType.value(), subComponentType.value(), "SelfDiagnosticParts", new SingleValueConverter<SelfDiagnosticCapability, SelfDiagnosticCapabilityMsg>(SelfDiagnosticCapability.class, SelfDiagnosticCapabilityMsg.class), new DJIValueConverter<SelfDiagnosticPartsInfo>(SelfDiagnosticPartsInfo.class)).canGet(false).canSet(false).canListen(false).canPerformAction(true).setIsEvent(false);

    static {
        keyList.add(KeySerialNumber);
        keyList.add(KeyFirmwareVersion);
        keyList.add(KeyConnectionDeviceInfo);
        keyList.add(KeyRemoteControllerType);
        keyList.add(KeyRCUSBMode);
        keyList.add(KeyRcMultiDeviceMakePair);
        keyList.add(KeyRcMultiDevices50xMakePair);
        keyList.add(KeyRcMultiDeviceSelectTarget);
        keyList.add(KeyFirmwareMatchType);
        keyList.add(KeyRequestPairUpgradePairing);
        keyList.add(KeyRequestPairing);
        keyList.add(KeyStopPairing);
        keyList.add(KeyStartRelayPairing);
        keyList.add(KeyStopRelayPairing);
        keyList.add(KeyRcPassword);
        keyList.add(KeyReleaseGimbalControlRight);
        keyList.add(KeyRequestLegacyGimbalControlRight);
        keyList.add(KeyResponseToRequestForGimbalControl);
        keyList.add(KeyGimbalControlRightRequest);
        keyList.add(KeyRcShakeMotor);
        keyList.add(KeyRcEnableRtk);
        keyList.add(KeyRcEnable4G);
        keyList.add(KeyRcCalibrateChannels);
        keyList.add(KeyRcMultiDeviceAircraftState);
        keyList.add(KeyRcMultiDeviceBsStates);
        keyList.add(KeyStickLeftHorizontal);
        keyList.add(KeyStickLeftVertical);
        keyList.add(KeyStickRightHorizontal);
        keyList.add(KeyStickRightVertical);
        keyList.add(KeyLeftDial);
        keyList.add(KeyRightDial);
        keyList.add(KeyScrollWheel);
        keyList.add(KeyRCRightWheelButtonDown);
        keyList.add(KeyRCTransformationSwitchState);
        keyList.add(KeyFlightModeSwitchState);
        keyList.add(KeyGoHomeButtonDown);
        keyList.add(KeyRecordButtonDown);
        keyList.add(KeyShutterButtonDown);
        keyList.add(KeyRCAuthLedButtonDown);
        keyList.add(KeyRCShutterButtonLongPress);
        keyList.add(KeyCustomButton1Down);
        keyList.add(KeyCustomButton2Down);
        keyList.add(KeyCustomButton3Down);
        keyList.add(KeyRCSwitchButtonDown);
        keyList.add(KeyRCCustomButton4Down);
        keyList.add(KeyRCPlaybackButtonDown);
        keyList.add(KeyPauseButtonDown);
        keyList.add(KeyBatteryInfo);
        keyList.add(KeySecondBatteryInfo);
        keyList.add(KeyPairingStatus);
        keyList.add(KeyRcControllerMode);
        keyList.add(KeyRcAppWorkStage);
        keyList.add(KeyRcCheckStatus);
        keyList.add(KeyRcGPSInfo);
        keyList.add(KeyChargeMobileMode);
        keyList.add(KeySoftSwitchMode);
        keyList.add(KeyRcLeftStickCalibrationStatus);
        keyList.add(KeyRcRightStickCalibrationStatus);
        keyList.add(KeyRequireIFrame);
        keyList.add(KeyFiveDimensionPressedStatus);
        keyList.add(KeyRcHardwareState);
        keyList.add(KeyMockRcHardwareState);
        keyList.add(KeyRcUnitAndLanguage);
        keyList.add(KeyRcCalibrateNumberOfSegment);
        keyList.add(KeyRcCalibrateAAxisStatus);
        keyList.add(KeyRcCalibrateBAxisStatus);
        keyList.add(KeyRcCalibrateCAxisStatus);
        keyList.add(KeyRcCalibrateDAxisStatus);
        keyList.add(KeyRcCalibrateEAxisStatus);
        keyList.add(KeyRcCalibrateFAxisStatus);
        keyList.add(KeyRcCalibrateGAxisStatus);
        keyList.add(KeyRcCalibrateHAxisStatus);
        keyList.add(KeyRcButtonEventPro);
        keyList.add(KeyRcButtonConfig);
        keyList.add(KeyRcButtonProfileGroups);
        keyList.add(KeyRcSelectButtonProfileGroup);
        keyList.add(KeyRcCustomButtonConfig);
        keyList.add(KeyRcFetchCustomButtonConfig);
        keyList.add(KeyIsStillLinked);
        keyList.add(KeyRcResetButtonConfig);
        keyList.add(KeyMultiControlStatus);
        keyList.add(KeyRcRK3399SirialNumber);
        keyList.add(KeyBatteryBoxSerialNumber);
        keyList.add(KeyRcMachineMode);
        keyList.add(KeyMultiControlGimbalAuthorityOwner);
        keyList.add(KeyMultiControlRequestPairing);
        keyList.add(KeyFpvAuthStatus);
        keyList.add(KeyUavLockStatus);
        keyList.add(KeyUavLockFailReason);
        keyList.add(KeyMultiControlOnlineRcCount);
        keyList.add(KeyMultiControlOnlineAppCount);
        keyList.add(KeyRcMasterSlaveOpen);
        keyList.add(KeyMultiControlIsSupported);
        keyList.add(KeySlaveRCStickMode);
        keyList.add(KeySlaveRCStickChannelMode);
        keyList.add(KeySlaveRCSWheelMode);
        keyList.add(KeyMultiControlAuthorityObtain);
        keyList.add(KeyMultiControlLockAuthority);
        keyList.add(KeyMultiRcSyncData);
        keyList.add(KeyMultiControlFlightControlAuthorityOwner);
        keyList.add(KeyMultiControlFlightControlAuthorityLockStatus);
        keyList.add(KeyMultiControlLostControlNotice);
        keyList.add(KeyMultiControlExecuteFailSafeActionWhenLostControl);
        keyList.add(KeyMultiRCBackgroundDownloadAuthOwner);
        keyList.add(KeyMultiRCExclusiveTaskAuthOwner);
        keyList.add(KeySetBackgroundDownloadAuthOwner);
        keyList.add(KeySetExclusiveTaskAuthOwner);
        keyList.add(KeyCustomBtnFunction);
        keyList.add(KeyFileDownloadInfo);
        keyList.add(KeyDownloadFile);
        keyList.add(KeyFileUpdatingInfo);
        keyList.add(KeyUpdateFile);
        keyList.add(KeyDeviceConfigAction);
        keyList.add(KeyLockShutterAndRecordButton);
        keyList.add(KeyRebootDevice);
        keyList.add(KeyProductSerialNumber);
        keyList.add(KeyRcUpgradeVoiceEnable);
        keyList.add(KeyCommonNetworkSign);
        keyList.add(KeyCommonNetworkPrivateKeyCheck);
        keyList.add(KeyResetFactorySettings);
        keyList.add(KeySetAlternateLandingPoint);
        keyList.add(KeyDroneNestStatus);
        keyList.add(KeyDroneNestPosition);
        keyList.add(KeyDroneNestAlternateLandingPointConfig);
        keyList.add(KeyDroneNestHomeLocation);
        keyList.add(KeyDroneNestAlternateLandingLocation);
        keyList.add(KeyDroneNestAlternateLandingGoHomeHeight);
        keyList.add(KeySSSFN);
        keyList.add(KeyRcSwitchPcMode);
        keyList.add(KeyStartAMTTest);
        keyList.add(KeyModule3399Version);
        keyList.add(KeySwitchRcFirmware);
        keyList.add(KeyRcFirmwareInfo);
        keyList.add(KeyRcFirmwareRole);
        keyList.add(KeyRcFirmwareRoleList);
        keyList.add(KeySdrParameter);
        keyList.add(KeyDeviceSecret);
        keyList.add(KeyFirmwareSupportInfo);
        keyList.add(KeyUsbDeviceAttached);
        keyList.add(KeyCheckExternalDeviceConnected);
        keyList.add(KeyRecordShutterButtonEnable);
        keyList.add(KeyIsLeftHorizontalStickNormal);
        keyList.add(KeyIsLeftVerticalStickNormal);
        keyList.add(KeyIsRightHorizontalStickNormal);
        keyList.add(KeyIsRightVerticalStickNormal);
        keyList.add(KeyTakePhotoButtonWhiteList);
        keyList.add(KeyAPPSilentlyUpgrade);
        keyList.add(KeyV1CmdSetPushEnable);
        keyList.add(KeyGroundDeviceIdentity);
        keyList.add(KeyUAVDeviceIdentity);
        keyList.add(KeyHDVTSDRModeConfig);
        keyList.add(KeyCameraVerifyLost);
        keyList.add(KeyRCSupportedAirlinkBandwidthRange);
        keyList.add(KeyIsSupportDualChannelAssistantLive);
        keyList.add(KeyIsMultiControllerSingleLiveView);
        keyList.add(KeyUpdateRelaySSID);
        keyList.add(KeyUpdateRelayPasswd);
        keyList.add(KeyUpdateRelayBroadcastPeriod);
        keyList.add(KeyUpdateRelayHideBroadcast);
        keyList.add(KeyUpdateRelayEnableBroadcast);
        keyList.add(KeyObtainRelayInfo);
        keyList.add(KeyRelayScanEnable);
        keyList.add(KeyScannedRelays);
        keyList.add(KeyConnectRelay);
        keyList.add(KeyRelayConnectionResult);
        keyList.add(KeyRelayBinSwitchStatus);
        keyList.add(KeyRelaySearchCtrl);
        keyList.add(KeyRelayPasswdHash);
        keyList.add(KeyClearRelayPairInfo);
        keyList.add(KeySupportRelayedByProductTypeRange);
        keyList.add(KeyLidarPointCloudPrediction);
        keyList.add(KeyMGMultiDevicesWorkMode);
        keyList.add(KeyMGMultiDevicesFpvSwitch);
        keyList.add(KeyMGMultiDevicesConnectStatus);
        keyList.add(KeyMGMultiDevicesWorkStatus);
        keyList.add(KeyNotifyDroneTaskState);
        keyList.add(KeyMaintainInfo);
        keyList.add(KeyDroneNestSetMaintainData);
        keyList.add(KeyDroneNestUserImprovementPlan);
        keyList.add(KeyDroneNestDeploymentMode);
        keyList.add(KeyDroneNestSetRelativeAlternateLandingPoint);
        keyList.add(KeyDroneNestGetRelativeAlternateLandingPoint);
        keyList.add(KeyDroneNestMoveState);
        keyList.add(KeyDroneNestDeparturePointOffset);
        keyList.add(KeyDroneNestDeploymentEvaluation);
        keyList.add(KeyMissionCenterShardFileUpload);
        keyList.add(KeyMissionCenterShardFileDelete);
        keyList.add(KeyDeviceID);
        keyList.add(KeyConnection);
        keyList.add(KeyForceUpdateCacheValue);
        keyList.add(KeyCalibrationFileStatus);
        keyList.add(KeyCalibrationFileUpdatingInfo);
        keyList.add(KeyUpdateCalibrationFile);
        keyList.add(KeyUpgradeNotifyInfo);
        keyList.add(KeyEnforceUpgradeEnable);
        keyList.add(KeyIsInEnforceUpgradeStatus);
        keyList.add(KeyIsDirectDevice);
        keyList.add(KeyCommonFileUpdatingInfo);
        keyList.add(KeyStartCommonFileUpdate);
        keyList.add(KeyStopCommonFileUpdate);
        keyList.add(KeySelfDiagnosticMode);
        keyList.add(KeySelfDiagnosticRequest);
        keyList.add(KeySelfDiagnosticCancel);
        keyList.add(KeySelfDiagnosticStatus);
        keyList.add(KeySelfDiagnosticParts);
    }
}

